import type { TutorialLesson } from '../types';

export const advancedLessons: TutorialLesson[] = [
  {
    slug: 'networking-bgp-fundamentals-and-policy',
    title: 'BGP Fundamentals and Policy',
    description: 'Understand path selection and policy-driven routing.',
    level: 'advanced',
    section: 'Internet Edge',
    order: 11,
    minutes: 24,
    content: [
      { type: 'p', text: 'BGP is policy routing between autonomous systems. It exchanges reachability with attributes that influence path choice more than shortest-distance logic.' },
      { type: 'ul', items: ['Common attributes: local-pref, AS path, MED, next-hop.', 'Inbound traffic is hard to control exactly; influence, do not assume.', 'Route filters protect your edge from leaks and hijacks.'] },
      { type: 'warning', text: 'A bad route announcement can blackhole traffic at internet scale. Peer filters and max-prefix guards are mandatory.' },
      { type: 'try', text: 'Design an active/standby edge policy using local-pref and AS path prepending for two upstream providers.' },
      { type: 'keypoints', items: ['BGP is a policy engine, not just routing.', 'Safety controls are as important as reachability.', 'Operational maturity depends on tested rollback plans.'] },
    ],
  },
  {
    slug: 'networking-vpn-and-zero-trust-access',
    title: 'VPN Architecture and Zero Trust',
    description: 'Secure remote access with identity-first design.',
    level: 'advanced',
    section: 'Security Architecture',
    order: 12,
    minutes: 22,
    content: [
      { type: 'p', text: 'Traditional VPN grants broad network access after tunnel establishment. Zero-trust models reduce blast radius by authenticating user, device, and app context continuously.' },
      { type: 'table', headers: ['Model', 'Strength', 'Risk'], rows: [['Full-tunnel VPN', 'Simple central control', 'Large lateral movement surface'], ['Split-tunnel VPN', 'Lower core load', 'Policy drift risk'], ['ZTNA', 'Granular app-level access', 'Higher design complexity']] },
      { type: 'tip', text: 'Bind access to identity + device posture + least-privilege app scopes.' },
      { type: 'try', text: 'Write an access policy for contractors who need one internal app but no subnet-level visibility.' },
      { type: 'keypoints', items: ['Remote access should be least privilege by default.', 'Identity and device health must influence authorization.', 'Segmentation and observability close the loop.'] },
    ],
  },
  {
    slug: 'networking-ddos-resilience-and-rate-limits',
    title: 'DDoS Resilience and Rate Limiting',
    description: 'Build layered defenses for volumetric and app attacks.',
    level: 'advanced',
    section: 'Security Architecture',
    order: 13,
    minutes: 23,
    content: [
      { type: 'p', text: 'No single control stops all denial-of-service attacks. Real resilience combines upstream scrubbing, CDN/WAF controls, edge filtering, autoscaling, and graceful degradation.' },
      { type: 'ul', items: ['L3/L4 flooding: absorb or scrub upstream.', 'L7 abuse: WAF rules, bot controls, challenge flows.', 'Application limits: token buckets, quota, circuit breakers.'] },
      { type: 'code', language: 'txt', title: 'Example API policy', code: 'Per-IP: 120 req/min\nPer-user token: 600 req/min\nBurst window: 30 req/10s\nPriority bypass for internal service accounts' },
      { type: 'try', text: 'Draft a runbook for attack detection, escalation, mitigations, and post-incident metrics.' },
      { type: 'keypoints', items: ['Resilience is layered, not singular.', 'Rate limits should align with product behavior.', 'Runbooks must be rehearsed before incidents happen.'] },
    ],
  },
  {
    slug: 'networking-sdwan-and-multi-region-design',
    title: 'SD-WAN and Multi-Region Design',
    description: 'Connect campuses and clouds with policy-aware routing.',
    level: 'advanced',
    section: 'Distributed Infrastructure',
    order: 14,
    minutes: 24,
    content: [
      { type: 'p', text: 'SD-WAN overlays centralize path policy and link optimization across internet/MPLS links, while multi-region architecture demands traffic steering, failover, and state strategy.' },
      { type: 'ul', items: ['Use application-aware routing by latency/jitter/loss.', 'Separate control-plane from data-plane blast radius.', 'Define RTO/RPO for every critical workload.'] },
      { type: 'note', text: 'Cross-region database writes can dominate latency if consistency strategy is not explicit.' },
      { type: 'try', text: 'Design an architecture for three campuses and two cloud regions with active-active API traffic and active-passive database failover.' },
      { type: 'keypoints', items: ['Policy-driven WAN improves user experience under fluctuating links.', 'Multi-region designs must choose consistency and failover behavior intentionally.', 'Measure, test, and iterate with chaos drills.'] },
    ],
  },
  {
    slug: 'networking-capstone-design-and-troubleshoot-campus-network',
    title: 'Capstone: Design and Troubleshoot a Campus Network',
    description: 'Apply end-to-end networking from architecture to incident response.',
    level: 'advanced',
    section: 'Capstone',
    order: 15,
    minutes: 28,
    content: [
      { type: 'p', text: 'This capstone combines segmentation, routing, DNS, security controls, observability, and resilience. Your output should look like a real engineering handoff.' },
      { type: 'h2', text: 'Deliverables' },
      { type: 'ol', items: ['Logical diagram with VLAN/subnet plan', 'Routing policy and default/failover behavior', 'Firewall matrix for north-south and east-west traffic', 'Monitoring and alert thresholds for latency/loss', 'Incident runbook for total internet edge outage'] },
      { type: 'h3', text: 'Scenario constraints' },
      { type: 'ul', items: ['Two ISPs at HQ, one ISP at each branch', 'Guest Wi-Fi must be isolated from staff systems', 'Learning platform must stay available during one-link failure', 'All critical changes must be reversible within 10 minutes'] },
      { type: 'try', text: 'Present your design decisions and tradeoffs in a one-page architecture memo, then simulate one outage and walk through response.' },
      { type: 'keypoints', items: ['Real networking skill is architecture plus operations.', 'Resilience comes from tested assumptions, not diagrams alone.', 'A good design includes rollback and incident communication paths.'] },
    ],
  },
];
