import type { TutorialLesson } from '../types';

export const beginnerLessons: TutorialLesson[] = [
  {
    slug: 'networking-what-is-a-network',
    title: 'What is a Network?',
    description: 'Understand devices, links, and why networking matters.',
    level: 'beginner',
    section: 'Foundations',
    order: 1,
    minutes: 14,
    content: [
      { type: 'p', text: 'A network is a system of connected devices sharing data through agreed rules. In modern products, networks carry requests, files, calls, streams, logs, and monitoring data.' },
      { type: 'h2', text: 'Core ideas' },
      { type: 'ul', items: ['Nodes: clients, servers, routers, switches', 'Links: cable, fiber, Wi-Fi, cellular', 'Protocols: shared language for communication', 'Addressing: who sends and who receives'] },
      { type: 'note', text: 'Good networking is not only speed. Reliability, security, and observability are equally important.' },
      { type: 'try', text: 'List 5 networked apps you use daily and identify what data each app sends and receives.' },
      { type: 'keypoints', items: ['Networking is shared communication, not just internet browsing.', 'Every app depends on addressing, routing, and protocols.', 'Operations and product quality both rely on network health.'] },
    ],
  },
  {
    slug: 'networking-osi-and-tcpip-models',
    title: 'OSI vs TCP/IP Models',
    description: 'Map networking concepts into practical layers.',
    level: 'beginner',
    section: 'Foundations',
    order: 2,
    minutes: 16,
    content: [
      { type: 'p', text: 'Layered models help you debug faster. Instead of guessing, you isolate where failure lives: physical, addressing, transport, or application.' },
      { type: 'table', headers: ['OSI Layer', 'TCP/IP Mapping', 'Example'], rows: [['L1 Physical', 'Link', 'Cable, RF signal'], ['L2 Data Link', 'Link', 'Ethernet frame, MAC'], ['L3 Network', 'Internet', 'IP packet'], ['L4 Transport', 'Transport', 'TCP, UDP'], ['L7 Application', 'Application', 'HTTP, DNS, SMTP']] },
      { type: 'tip', text: 'When troubleshooting, move bottom-up: link first, then IP, then ports/services.' },
      { type: 'try', text: 'For a failed website request, write one check per layer that can confirm where the problem is.' },
      { type: 'keypoints', items: ['Models are mental tools for troubleshooting.', 'TCP/IP is what you use daily in real systems.', 'Layer boundaries help teams communicate clearly.'] },
    ],
  },
  {
    slug: 'networking-ip-addressing-and-subnets',
    title: 'IP Addressing and Subnet Basics',
    description: 'Read IPv4 addresses, CIDR, and subnet boundaries.',
    level: 'beginner',
    section: 'Addressing',
    order: 3,
    minutes: 18,
    content: [
      { type: 'p', text: 'IP addressing defines network identity and host identity. CIDR notation (like /24) tells you how many bits represent the network.' },
      { type: 'code', language: 'bash', title: 'Quick subnet checks', code: 'ip addr\nip route\n# Example CIDR: 192.168.10.0/24\n# Hosts: 192.168.10.1 - 192.168.10.254' },
      { type: 'h2', text: 'Private IPv4 ranges' },
      { type: 'ul', items: ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16'] },
      { type: 'warning', text: 'Two devices with the same IP in the same subnet will conflict and cause unstable connectivity.' },
      { type: 'try', text: 'Given 10.20.30.44/27, identify network address, broadcast address, and host range.' },
      { type: 'keypoints', items: ['CIDR is essential for cloud and on-prem design.', 'Subnets control broadcast scope and segmentation.', 'Address planning prevents collisions and chaos.'] },
    ],
  },
  {
    slug: 'networking-dns-and-name-resolution',
    title: 'DNS and Name Resolution',
    description: 'Translate names to IPs and diagnose lookup issues.',
    level: 'beginner',
    section: 'Addressing',
    order: 4,
    minutes: 16,
    content: [
      { type: 'p', text: 'DNS is the phonebook of the internet. Applications query DNS before opening most outbound connections.' },
      { type: 'code', language: 'bash', title: 'DNS checks', code: 'nslookup intellex.ai\ndig intellex.ai A +short\n# Reverse lookup\ndig -x 8.8.8.8 +short' },
      { type: 'ul', items: ['A/AAAA records map names to IP addresses.', 'CNAME aliases one name to another name.', 'TTL controls caching duration.'] },
      { type: 'tip', text: 'Always verify DNS response and TTL during incidents before changing app code.' },
      { type: 'try', text: 'Check one production domain and identify its record type chain and TTL values.' },
      { type: 'keypoints', items: ['DNS issues can look like app downtime.', 'Caching and propagation explain many intermittent behaviors.', 'Low TTL helps fast cutovers, but increases query load.'] },
    ],
  },
  {
    slug: 'networking-tcp-udp-and-ports',
    title: 'TCP, UDP, and Ports',
    description: 'Choose transport protocols and inspect sockets.',
    level: 'beginner',
    section: 'Transport Basics',
    order: 5,
    minutes: 18,
    content: [
      { type: 'p', text: 'Transport protocols define delivery behavior. TCP focuses on reliable ordered delivery. UDP favors low overhead and speed where packet loss can be tolerated.' },
      { type: 'table', headers: ['Protocol', 'Strength', 'Common Use'], rows: [['TCP', 'Reliable, ordered', 'HTTP, SSH, databases'], ['UDP', 'Low latency, lightweight', 'VoIP, live streaming, DNS queries']] },
      { type: 'code', language: 'bash', title: 'Inspect listening ports', code: 'ss -tulpen\nnetstat -ano | findstr LISTEN' },
      { type: 'try', text: 'Pick one service on your machine and identify protocol, local port, and owning process.' },
      { type: 'keypoints', items: ['Port numbers identify application endpoints.', 'TCP and UDP trade reliability vs latency differently.', 'Socket inspection is a core debugging skill.'] },
    ],
  },
];
