import type { TutorialLesson } from '../types';

export const intermediateLessons: TutorialLesson[] = [
  {
    slug: 'networking-switching-vlans-and-trunks',
    title: 'Switching, VLANs, and Trunks',
    description: 'Segment L2 domains and carry multiple VLANs safely.',
    level: 'intermediate',
    section: 'LAN Engineering',
    order: 6,
    minutes: 20,
    content: [
      { type: 'p', text: 'VLANs isolate broadcast domains on shared switch hardware. Trunks carry tagged frames across uplinks so segmentation survives hop-to-hop.' },
      { type: 'ul', items: ['Access port: one VLAN, untagged at endpoint.', 'Trunk port: multiple VLANs, tagged with 802.1Q.', 'Native VLAN must be controlled to avoid leaks.'] },
      { type: 'warning', text: 'Mismatched trunk settings cause intermittent packet drops and hard-to-debug cross-VLAN failures.' },
      { type: 'try', text: 'Design VLAN IDs for students, staff, labs, and guest Wi-Fi in a campus with one core switch and three access switches.' },
      { type: 'keypoints', items: ['VLANs are foundational for security boundaries.', 'Trunk consistency is critical for reliability.', 'Segmentation should align with policy and identity.'] },
    ],
  },
  {
    slug: 'networking-routing-static-vs-dynamic',
    title: 'Routing: Static and Dynamic',
    description: 'Decide when to use static routes and dynamic protocols.',
    level: 'intermediate',
    section: 'LAN Engineering',
    order: 7,
    minutes: 19,
    content: [
      { type: 'p', text: 'Routing chooses next-hop paths between subnets and networks. Small environments can use static routes, while larger topologies rely on dynamic convergence.' },
      { type: 'table', headers: ['Approach', 'Best Use', 'Tradeoff'], rows: [['Static routes', 'Small stable topology', 'Manual operations overhead'], ['OSPF/IS-IS', 'Enterprise campus/core', 'Control-plane complexity'], ['BGP', 'Inter-domain and policy routing', 'Steeper learning curve']] },
      { type: 'code', language: 'bash', title: 'Inspect route table', code: 'ip route\nroute -n' },
      { type: 'try', text: 'Explain why default routes alone are insufficient when internal subnets must be reachable from multiple paths.' },
      { type: 'keypoints', items: ['Routing is policy plus topology.', 'Convergence speed and stability matter in production.', 'Always monitor route changes during incident windows.'] },
    ],
  },
  {
    slug: 'networking-nat-firewalls-and-acl',
    title: 'NAT, Firewalls, and ACLs',
    description: 'Control ingress/egress while preserving app connectivity.',
    level: 'intermediate',
    section: 'Security Controls',
    order: 8,
    minutes: 22,
    content: [
      { type: 'p', text: 'NAT rewrites addresses between private and public domains. Firewalls and ACLs enforce policy for which traffic may pass and in what direction.' },
      { type: 'ul', items: ['SNAT: source translation for outbound internet access.', 'DNAT: destination translation for publishing internal services.', 'Stateful firewall tracks sessions and return traffic.'] },
      { type: 'code', language: 'bash', title: 'Linux firewall baseline', code: 'sudo nft list ruleset\n# or\nsudo iptables -S' },
      { type: 'warning', text: 'Overly broad rules like any-any can hide quickly during emergencies but become long-term security debt.' },
      { type: 'try', text: 'Draft a minimal rule set for a web app tier: allow HTTPS in, allow DB only from app subnet, deny all else.' },
      { type: 'keypoints', items: ['Security policy must be explicit and auditable.', 'NAT solves address constraints but complicates tracing.', 'Least privilege is easier to maintain than broad exceptions.'] },
    ],
  },
  {
    slug: 'networking-load-balancing-and-reverse-proxy',
    title: 'Load Balancing and Reverse Proxy',
    description: 'Scale service endpoints and terminate TLS cleanly.',
    level: 'intermediate',
    section: 'Application Delivery',
    order: 9,
    minutes: 20,
    content: [
      { type: 'p', text: 'Reverse proxies and load balancers distribute traffic, terminate TLS, and expose health-aware routing policies for high availability.' },
      { type: 'code', language: 'nginx', title: 'Simple upstream pool', code: 'upstream api_pool {\n  server 10.0.1.10:3000;\n  server 10.0.1.11:3000;\n}\nserver {\n  listen 443 ssl;\n  location / {\n    proxy_pass http://api_pool;\n  }\n}' },
      { type: 'ul', items: ['Round-robin is simple baseline balancing.', 'Health checks remove failing nodes automatically.', 'Sticky sessions may be required for legacy stateful apps.'] },
      { type: 'try', text: 'Define health-check and failover behavior for an API with p95 latency SLO and two regions.' },
      { type: 'keypoints', items: ['Load balancing improves uptime and throughput.', 'Proxies centralize TLS and routing policy.', 'Health signals must be meaningful, not superficial.'] },
    ],
  },
  {
    slug: 'networking-observability-with-ping-traceroute-and-packet-capture',
    title: 'Network Observability Tools',
    description: 'Use ping, traceroute, tcpdump, and Wireshark intentionally.',
    level: 'intermediate',
    section: 'Operations',
    order: 10,
    minutes: 22,
    content: [
      { type: 'p', text: 'Operational networking requires evidence. Use active probes and packet captures to prove or disprove hypotheses quickly.' },
      { type: 'code', language: 'bash', title: 'Troubleshooting toolkit', code: 'ping -c 4 1.1.1.1\ntraceroute 8.8.8.8\ntcpdump -i eth0 port 443 -nn\n# Windows\npathping 8.8.8.8' },
      { type: 'ul', items: ['Ping: reachability + packet loss baseline.', 'Traceroute: path visibility and hop timing.', 'Packet capture: protocol truth during disputed incidents.'] },
      { type: 'tip', text: 'Capture narrowly by host/port/time window to avoid giant traces and noisy conclusions.' },
      { type: 'try', text: 'Capture a failed TLS handshake and identify whether the reset came from client, proxy, or upstream server.' },
      { type: 'keypoints', items: ['Troubleshooting should be evidence-driven.', 'Packet captures settle many "works on my machine" arguments.', 'Observability speed directly impacts downtime duration.'] },
    ],
  },
];
