import type { TutorialLesson } from '../types';

export const advancedLessons: TutorialLesson[] = [
  {
    slug: "cpp-raii",
    title: "RAII Deep Dive",
    description: "Resource acquisition is initialization as a design rule.",
    level: "advanced",
    section: "Systems C++",
    order: 49,
    minutes: 16,
    content: [
      {"type":"p","text":"RAII Deep Dive is a core skill in the C++ path on InTelleX. You will learn raii deep dive with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind RAII Deep Dive","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice raii deep dive with a small exercise of your own."},
      {"type":"keypoints","items":["RAII Deep Dive is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-rule-of-five",
    title: "Rule of Five",
    description: "Copy/move constructors and assignment operators.",
    level: "advanced",
    section: "Systems C++",
    order: 50,
    minutes: 16,
    content: [
      {"type":"p","text":"Rule of Five is a core skill in the C++ path on InTelleX. You will learn rule of five with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Rule of Five","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice rule of five with a small exercise of your own."},
      {"type":"keypoints","items":["Rule of Five is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-const-correctness",
    title: "Const Correctness",
    description: "Design APIs that cannot mutate by accident.",
    level: "advanced",
    section: "Systems C++",
    order: 51,
    minutes: 16,
    content: [
      {"type":"p","text":"Const Correctness is a core skill in the C++ path on InTelleX. You will learn const correctness with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Const Correctness","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice const correctness with a small exercise of your own."},
      {"type":"keypoints","items":["Const Correctness is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-multithreading",
    title: "Threads Basics",
    description: "std::thread and joining workers.",
    level: "advanced",
    section: "Concurrency",
    order: 52,
    minutes: 16,
    content: [
      {"type":"p","text":"Threads Basics is a core skill in the C++ path on InTelleX. You will learn threads basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Threads Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"#include <thread>\nstd::thread t([]{ /* work */ });\nt.join();","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice threads basics with a small exercise of your own."},
      {"type":"keypoints","items":["Threads Basics is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-mutex",
    title: "Mutex & Shared Data",
    description: "Protect critical sections with std::mutex.",
    level: "advanced",
    section: "Concurrency",
    order: 53,
    minutes: 16,
    content: [
      {"type":"p","text":"Mutex & Shared Data is a core skill in the C++ path on InTelleX. You will learn mutex & shared data with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Mutex & Shared Data","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice mutex & shared data with a small exercise of your own."},
      {"type":"keypoints","items":["Mutex & Shared Data is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-atomics",
    title: "Atomics Overview",
    description: "When lock-free counters make sense.",
    level: "advanced",
    section: "Concurrency",
    order: 54,
    minutes: 16,
    content: [
      {"type":"p","text":"Atomics Overview is a core skill in the C++ path on InTelleX. You will learn atomics overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Atomics Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice atomics overview with a small exercise of your own."},
      {"type":"keypoints","items":["Atomics Overview is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-performance",
    title: "Performance Mindset",
    description: "Measure first: cache locality, copies, and allocations.",
    level: "advanced",
    section: "Performance",
    order: 55,
    minutes: 16,
    content: [
      {"type":"p","text":"Performance Mindset is a core skill in the C++ path on InTelleX. You will learn performance mindset with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Performance Mindset","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice performance mindset with a small exercise of your own."},
      {"type":"keypoints","items":["Performance Mindset is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-optimization-flags",
    title: "Compiler Optimization Flags",
    description: "-O2, -O3, and debug vs release builds.",
    level: "advanced",
    section: "Performance",
    order: 56,
    minutes: 16,
    content: [
      {"type":"p","text":"Compiler Optimization Flags is a core skill in the C++ path on InTelleX. You will learn compiler optimization flags with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Compiler Optimization Flags","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice compiler optimization flags with a small exercise of your own."},
      {"type":"keypoints","items":["Compiler Optimization Flags is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-undefined-behavior",
    title: "Undefined Behavior",
    description: "Recognize UB and write defined programs.",
    level: "advanced",
    section: "Reliability Advanced",
    order: 57,
    minutes: 16,
    content: [
      {"type":"p","text":"Undefined Behavior is a core skill in the C++ path on InTelleX. You will learn undefined behavior with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Undefined Behavior","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"warning","text":"UB can appear to work until it does not — never rely on it."},
      {"type":"try","text":"Practice undefined behavior with a small exercise of your own."},
      {"type":"keypoints","items":["Undefined Behavior is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-sanitizers",
    title: "Sanitizers (ASan/UBSan)",
    description: "Catch memory and UB bugs early.",
    level: "advanced",
    section: "Reliability Advanced",
    order: 58,
    minutes: 16,
    content: [
      {"type":"p","text":"Sanitizers (ASan/UBSan) is a core skill in the C++ path on InTelleX. You will learn sanitizers (asan/ubsan) with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Sanitizers (ASan/UBSan)","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"g++ -fsanitize=address,undefined -g main.cpp","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice sanitizers (asan/ubsan) with a small exercise of your own."},
      {"type":"keypoints","items":["Sanitizers (ASan/UBSan) is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-design-patterns",
    title: "Useful Patterns in C++",
    description: "Factory, Strategy, and Observer in practical form.",
    level: "advanced",
    section: "Design",
    order: 59,
    minutes: 16,
    content: [
      {"type":"p","text":"Useful Patterns in C++ is a core skill in the C++ path on InTelleX. You will learn useful patterns in c++ with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Useful Patterns in C++","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice useful patterns in c++ with a small exercise of your own."},
      {"type":"keypoints","items":["Useful Patterns in C++ is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-networking-intro",
    title: "Networking Intro",
    description: "Sockets at a high level for systems apps.",
    level: "advanced",
    section: "Systems Apps",
    order: 60,
    minutes: 16,
    content: [
      {"type":"p","text":"Networking Intro is a core skill in the C++ path on InTelleX. You will learn networking intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Networking Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice networking intro with a small exercise of your own."},
      {"type":"keypoints","items":["Networking Intro is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-embedded-mindset",
    title: "Embedded C++ Mindset",
    description: "Constraints: no heap thrash, careful types, predictability.",
    level: "advanced",
    section: "Systems Apps",
    order: 61,
    minutes: 16,
    content: [
      {"type":"p","text":"Embedded C++ Mindset is a core skill in the C++ path on InTelleX. You will learn embedded c++ mindset with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Embedded C++ Mindset","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice embedded c++ mindset with a small exercise of your own."},
      {"type":"keypoints","items":["Embedded C++ Mindset is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-capstone-http-parser",
    title: "Capstone: Mini HTTP Parser",
    description: "Parse request lines and headers from a buffer.",
    level: "advanced",
    section: "Capstone",
    order: 62,
    minutes: 20,
    content: [
      {"type":"p","text":"Capstone: Mini HTTP Parser is a core skill in the C++ path on InTelleX. You will learn capstone: mini http parser with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Mini HTTP Parser","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice capstone: mini http parser with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Mini HTTP Parser is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-capstone-thread-pool",
    title: "Capstone: Thread Pool",
    description: "Queue tasks and run them on worker threads.",
    level: "advanced",
    section: "Capstone",
    order: 63,
    minutes: 20,
    content: [
      {"type":"p","text":"Capstone: Thread Pool is a core skill in the C++ path on InTelleX. You will learn capstone: thread pool with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Thread Pool","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice capstone: thread pool with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Thread Pool is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-interview-review",
    title: "C++ Interview Review",
    description: "Pointers, OOP, STL, and move semantics checklist.",
    level: "advanced",
    section: "Polish & Next Steps",
    order: 64,
    minutes: 16,
    content: [
      {"type":"p","text":"C++ Interview Review is a core skill in the C++ path on InTelleX. You will learn c++ interview review with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind C++ Interview Review","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice c++ interview review with a small exercise of your own."},
      {"type":"keypoints","items":["C++ Interview Review is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-next-steps",
    title: "Next Steps in C++",
    description: "Where to go: Boost, graphics, embedded, or distributed systems.",
    level: "advanced",
    section: "Polish & Next Steps",
    order: 65,
    minutes: 16,
    content: [
      {"type":"p","text":"Next Steps in C++ is a core skill in the C++ path on InTelleX. You will learn next steps in c++ with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Next Steps in C++","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice next steps in c++ with a small exercise of your own."},
      {"type":"keypoints","items":["Next Steps in C++ is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
