import type { TutorialLesson } from '../types';

export const beginnerLessons: TutorialLesson[] = [
  {
    slug: "welcome-to-cpp",
    title: "Welcome to C++",
    description: "Meet modern C++ and how this InTelleX path is organized.",
    level: "beginner",
    section: "Getting Started",
    order: 1,
    minutes: 11,
    content: [
      {"type":"p","text":"Welcome to C++ is a core skill in the C++ path on InTelleX. C++ powers systems, games, embedded, and high-performance software."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["What C++ is used for","How this tutorial is structured","Tooling overview"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"#include <iostream>\nint main() {\n  std::cout << \"Hello, C++\\n\";\n  return 0;\n}","title":"Hello world","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Install a C++ compiler (g++ or clang++) and compile hello.cpp."},
      {"type":"keypoints","items":["Welcome to C++ is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-setup-compiler",
    title: "Install a C++ Compiler",
    description: "Set up g++/clang++ and verify your toolchain.",
    level: "beginner",
    section: "Getting Started",
    order: 2,
    minutes: 11,
    content: [
      {"type":"p","text":"Install a C++ Compiler is a core skill in the C++ path on InTelleX. You will learn install a c++ compiler with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Install a C++ Compiler","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"g++ --version\ng++ hello.cpp -o hello\n./hello","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice install a c++ compiler with a small exercise of your own."},
      {"type":"keypoints","items":["Install a C++ Compiler is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-first-program",
    title: "Your First C++ Program",
    description: "Write, compile, and run a tiny program end to end.",
    level: "beginner",
    section: "Getting Started",
    order: 3,
    minutes: 11,
    content: [
      {"type":"p","text":"Your First C++ Program is a core skill in the C++ path on InTelleX. You will learn your first c++ program with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Your First C++ Program","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"#include <iostream>\nusing namespace std;\nint main() {\n  cout << \"Intellex C++ lab\\n\";\n}","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice your first c++ program with a small exercise of your own."},
      {"type":"keypoints","items":["Your First C++ Program is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-variables-types",
    title: "Variables & Fundamental Types",
    description: "int, double, char, bool, and type safety basics.",
    level: "beginner",
    section: "Language Basics",
    order: 4,
    minutes: 11,
    content: [
      {"type":"p","text":"Variables & Fundamental Types is a core skill in the C++ path on InTelleX. You will learn variables & fundamental types with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Variables & Fundamental Types","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"int age = 20;\ndouble pi = 3.14159;\nbool ok = true;\nchar grade = 'A';","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice variables & fundamental types with a small exercise of your own."},
      {"type":"keypoints","items":["Variables & Fundamental Types is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-constants",
    title: "Constants & const",
    description: "Use const and constexpr for safer values.",
    level: "beginner",
    section: "Language Basics",
    order: 5,
    minutes: 11,
    content: [
      {"type":"p","text":"Constants & const is a core skill in the C++ path on InTelleX. You will learn constants & const with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Constants & const","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"const int MAX = 100;\nconstexpr double G = 9.81;","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice constants & const with a small exercise of your own."},
      {"type":"keypoints","items":["Constants & const is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-operators",
    title: "Operators & Expressions",
    description: "Arithmetic, comparison, logical, and assignment operators.",
    level: "beginner",
    section: "Language Basics",
    order: 6,
    minutes: 11,
    content: [
      {"type":"p","text":"Operators & Expressions is a core skill in the C++ path on InTelleX. You will learn operators & expressions with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Operators & Expressions","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice operators & expressions with a small exercise of your own."},
      {"type":"keypoints","items":["Operators & Expressions is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-input-output",
    title: "Input & Output with iostream",
    description: "cin, cout, and formatting basics.",
    level: "beginner",
    section: "Language Basics",
    order: 7,
    minutes: 11,
    content: [
      {"type":"p","text":"Input & Output with iostream is a core skill in the C++ path on InTelleX. You will learn input & output with iostream with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Input & Output with iostream","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"int n;\nstd::cin >> n;\nstd::cout << \"You typed \" << n << \"\\n\";","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice input & output with iostream with a small exercise of your own."},
      {"type":"keypoints","items":["Input & Output with iostream is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-conditionals",
    title: "Conditionals",
    description: "if, else if, else, and switch.",
    level: "beginner",
    section: "Control Flow",
    order: 8,
    minutes: 11,
    content: [
      {"type":"p","text":"Conditionals is a core skill in the C++ path on InTelleX. You will learn conditionals with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Conditionals","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"if (score >= 90) grade = 'A';\nelse if (score >= 80) grade = 'B';\nelse grade = 'C';","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice conditionals with a small exercise of your own."},
      {"type":"keypoints","items":["Conditionals is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-loops",
    title: "Loops",
    description: "for, while, and do-while with clear examples.",
    level: "beginner",
    section: "Control Flow",
    order: 9,
    minutes: 11,
    content: [
      {"type":"p","text":"Loops is a core skill in the C++ path on InTelleX. You will learn loops with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Loops","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"for (int i = 0; i < 5; ++i) {\n  std::cout << i << \"\\n\";\n}","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice loops with a small exercise of your own."},
      {"type":"keypoints","items":["Loops is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-functions",
    title: "Functions",
    description: "Declare, define, and call functions with parameters.",
    level: "beginner",
    section: "Functions",
    order: 10,
    minutes: 11,
    content: [
      {"type":"p","text":"Functions is a core skill in the C++ path on InTelleX. You will learn functions with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Functions","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"int add(int a, int b) {\n  return a + b;\n}","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice functions with a small exercise of your own."},
      {"type":"keypoints","items":["Functions is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-overloading",
    title: "Function Overloading",
    description: "Multiple functions with the same name and different signatures.",
    level: "beginner",
    section: "Functions",
    order: 11,
    minutes: 11,
    content: [
      {"type":"p","text":"Function Overloading is a core skill in the C++ path on InTelleX. You will learn function overloading with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Function Overloading","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice function overloading with a small exercise of your own."},
      {"type":"keypoints","items":["Function Overloading is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-default-args",
    title: "Default Arguments",
    description: "Provide optional parameters with defaults.",
    level: "beginner",
    section: "Functions",
    order: 12,
    minutes: 11,
    content: [
      {"type":"p","text":"Default Arguments is a core skill in the C++ path on InTelleX. You will learn default arguments with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Default Arguments","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice default arguments with a small exercise of your own."},
      {"type":"keypoints","items":["Default Arguments is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-arrays",
    title: "Arrays",
    description: "Fixed-size arrays and common pitfalls.",
    level: "beginner",
    section: "Data Structures",
    order: 13,
    minutes: 11,
    content: [
      {"type":"p","text":"Arrays is a core skill in the C++ path on InTelleX. You will learn arrays with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Arrays","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"int nums[5] = {1, 2, 3, 4, 5};\nstd::cout << nums[0];","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice arrays with a small exercise of your own."},
      {"type":"keypoints","items":["Arrays is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-strings",
    title: "std::string",
    description: "Create, concatenate, and inspect strings.",
    level: "beginner",
    section: "Data Structures",
    order: 14,
    minutes: 11,
    content: [
      {"type":"p","text":"std::string is a core skill in the C++ path on InTelleX. You will learn std::string with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind std::string","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"#include <string>\nstd::string name = \"Ada\";\nname += \" Lovelace\";","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice std::string with a small exercise of your own."},
      {"type":"keypoints","items":["std::string is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-vectors",
    title: "std::vector",
    description: "Dynamic arrays with push_back and size.",
    level: "beginner",
    section: "Data Structures",
    order: 15,
    minutes: 11,
    content: [
      {"type":"p","text":"std::vector is a core skill in the C++ path on InTelleX. You will learn std::vector with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind std::vector","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"#include <vector>\nstd::vector<int> v;\nv.push_back(10);\nv.push_back(20);","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice std::vector with a small exercise of your own."},
      {"type":"keypoints","items":["std::vector is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-range-for",
    title: "Range-based for",
    description: "Iterate containers cleanly with for-each style loops.",
    level: "beginner",
    section: "Data Structures",
    order: 16,
    minutes: 11,
    content: [
      {"type":"p","text":"Range-based for is a core skill in the C++ path on InTelleX. You will learn range-based for with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Range-based for","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"for (int x : v) std::cout << x << \" \";","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice range-based for with a small exercise of your own."},
      {"type":"keypoints","items":["Range-based for is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-references",
    title: "References",
    description: "Alias variables and pass by reference.",
    level: "beginner",
    section: "Memory Basics",
    order: 17,
    minutes: 11,
    content: [
      {"type":"p","text":"References is a core skill in the C++ path on InTelleX. You will learn references with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind References","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"void bump(int& n) { n += 1; }","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice references with a small exercise of your own."},
      {"type":"keypoints","items":["References is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-pointers",
    title: "Pointers",
    description: "Addresses, dereference, and nullptr.",
    level: "beginner",
    section: "Memory Basics",
    order: 18,
    minutes: 11,
    content: [
      {"type":"p","text":"Pointers is a core skill in the C++ path on InTelleX. You will learn pointers with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Pointers","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"int x = 5;\nint* p = &x;\nstd::cout << *p;","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice pointers with a small exercise of your own."},
      {"type":"keypoints","items":["Pointers is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-new-delete",
    title: "new and delete",
    description: "Dynamic allocation and why modern C++ prefers RAII.",
    level: "beginner",
    section: "Memory Basics",
    order: 19,
    minutes: 11,
    content: [
      {"type":"p","text":"new and delete is a core skill in the C++ path on InTelleX. You will learn new and delete with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind new and delete","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"warning","text":"Prefer smart pointers in modern code; learn new/delete to understand ownership."},
      {"type":"try","text":"Practice new and delete with a small exercise of your own."},
      {"type":"keypoints","items":["new and delete is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-structs",
    title: "Structs",
    description: "Group related data into simple types.",
    level: "beginner",
    section: "User Types",
    order: 20,
    minutes: 11,
    content: [
      {"type":"p","text":"Structs is a core skill in the C++ path on InTelleX. You will learn structs with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Structs","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"struct Point { double x; double y; };","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice structs with a small exercise of your own."},
      {"type":"keypoints","items":["Structs is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-classes-intro",
    title: "Classes Intro",
    description: "Encapsulation with public and private members.",
    level: "beginner",
    section: "User Types",
    order: 21,
    minutes: 11,
    content: [
      {"type":"p","text":"Classes Intro is a core skill in the C++ path on InTelleX. You will learn classes intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Classes Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"class Counter {\npublic:\n  void inc() { value++; }\n  int get() const { return value; }\nprivate:\n  int value = 0;\n};","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice classes intro with a small exercise of your own."},
      {"type":"keypoints","items":["Classes Intro is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-constructors",
    title: "Constructors & Destructors",
    description: "Initialize objects and clean up resources.",
    level: "beginner",
    section: "User Types",
    order: 22,
    minutes: 11,
    content: [
      {"type":"p","text":"Constructors & Destructors is a core skill in the C++ path on InTelleX. You will learn constructors & destructors with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Constructors & Destructors","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice constructors & destructors with a small exercise of your own."},
      {"type":"keypoints","items":["Constructors & Destructors is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-methods",
    title: "Member Functions",
    description: "Define behavior on your types.",
    level: "beginner",
    section: "User Types",
    order: 23,
    minutes: 11,
    content: [
      {"type":"p","text":"Member Functions is a core skill in the C++ path on InTelleX. You will learn member functions with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Member Functions","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice member functions with a small exercise of your own."},
      {"type":"keypoints","items":["Member Functions is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-header-files",
    title: "Headers & Source Files",
    description: "Split declarations and definitions across files.",
    level: "beginner",
    section: "Projects",
    order: 24,
    minutes: 11,
    content: [
      {"type":"p","text":"Headers & Source Files is a core skill in the C++ path on InTelleX. You will learn headers & source files with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Headers & Source Files","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"// math.hpp\nint square(int x);\n// math.cpp\nint square(int x) { return x * x; }","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice headers & source files with a small exercise of your own."},
      {"type":"keypoints","items":["Headers & Source Files is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-mini-project-cli",
    title: "Project: CLI Calculator",
    description: "Build a small calculator using functions and loops.",
    level: "beginner",
    section: "Projects",
    order: 25,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: CLI Calculator is a core skill in the C++ path on InTelleX. You will learn project: cli calculator with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: CLI Calculator","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice project: cli calculator with a small exercise of your own."},
      {"type":"keypoints","items":["Project: CLI Calculator is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
