import type { TutorialLesson } from '../types';

export const intermediateLessons: TutorialLesson[] = [
  {
    slug: "cpp-oop-encapsulation",
    title: "Encapsulation in Depth",
    description: "Design classes with clear public APIs.",
    level: "intermediate",
    section: "Object-Oriented C++",
    order: 26,
    minutes: 13,
    content: [
      {"type":"p","text":"Encapsulation in Depth is a core skill in the C++ path on InTelleX. You will learn encapsulation in depth with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Encapsulation in Depth","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice encapsulation in depth with a small exercise of your own."},
      {"type":"keypoints","items":["Encapsulation in Depth is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-inheritance",
    title: "Inheritance",
    description: "Derive classes and reuse behavior.",
    level: "intermediate",
    section: "Object-Oriented C++",
    order: 27,
    minutes: 13,
    content: [
      {"type":"p","text":"Inheritance is a core skill in the C++ path on InTelleX. You will learn inheritance with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Inheritance","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"class Animal { public: virtual void speak() {} };\nclass Dog : public Animal { public: void speak() override; };","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice inheritance with a small exercise of your own."},
      {"type":"keypoints","items":["Inheritance is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-polymorphism",
    title: "Polymorphism & virtual",
    description: "Call the right method through base pointers.",
    level: "intermediate",
    section: "Object-Oriented C++",
    order: 28,
    minutes: 13,
    content: [
      {"type":"p","text":"Polymorphism & virtual is a core skill in the C++ path on InTelleX. You will learn polymorphism & virtual with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Polymorphism & virtual","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice polymorphism & virtual with a small exercise of your own."},
      {"type":"keypoints","items":["Polymorphism & virtual is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-abstract-classes",
    title: "Abstract Classes",
    description: "Pure virtual functions and interfaces.",
    level: "intermediate",
    section: "Object-Oriented C++",
    order: 29,
    minutes: 13,
    content: [
      {"type":"p","text":"Abstract Classes is a core skill in the C++ path on InTelleX. You will learn abstract classes with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Abstract Classes","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice abstract classes with a small exercise of your own."},
      {"type":"keypoints","items":["Abstract Classes is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-operator-overloading",
    title: "Operator Overloading",
    description: "Define +, ==, and stream operators carefully.",
    level: "intermediate",
    section: "Object-Oriented C++",
    order: 30,
    minutes: 13,
    content: [
      {"type":"p","text":"Operator Overloading is a core skill in the C++ path on InTelleX. You will learn operator overloading with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Operator Overloading","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice operator overloading with a small exercise of your own."},
      {"type":"keypoints","items":["Operator Overloading is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-stl-overview",
    title: "STL Overview",
    description: "Containers, iterators, and algorithms map.",
    level: "intermediate",
    section: "Standard Library",
    order: 31,
    minutes: 13,
    content: [
      {"type":"p","text":"STL Overview is a core skill in the C++ path on InTelleX. You will learn stl overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind STL Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice stl overview with a small exercise of your own."},
      {"type":"keypoints","items":["STL Overview is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-map-set",
    title: "map & set",
    description: "Associative containers for keys and unique values.",
    level: "intermediate",
    section: "Standard Library",
    order: 32,
    minutes: 13,
    content: [
      {"type":"p","text":"map & set is a core skill in the C++ path on InTelleX. You will learn map & set with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind map & set","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"#include <map>\nstd::map<std::string, int> ages;\nages[\"Ada\"] = 36;","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice map & set with a small exercise of your own."},
      {"type":"keypoints","items":["map & set is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-algorithms",
    title: "STL Algorithms",
    description: "sort, find, accumulate, and transform.",
    level: "intermediate",
    section: "Standard Library",
    order: 33,
    minutes: 13,
    content: [
      {"type":"p","text":"STL Algorithms is a core skill in the C++ path on InTelleX. You will learn stl algorithms with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind STL Algorithms","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"#include <algorithm>\nstd::sort(v.begin(), v.end());","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice stl algorithms with a small exercise of your own."},
      {"type":"keypoints","items":["STL Algorithms is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-iterators",
    title: "Iterators",
    description: "Traverse containers with begin/end idioms.",
    level: "intermediate",
    section: "Standard Library",
    order: 34,
    minutes: 13,
    content: [
      {"type":"p","text":"Iterators is a core skill in the C++ path on InTelleX. You will learn iterators with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Iterators","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice iterators with a small exercise of your own."},
      {"type":"keypoints","items":["Iterators is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-lambdas",
    title: "Lambdas",
    description: "Inline function objects for algorithms.",
    level: "intermediate",
    section: "Modern C++",
    order: 35,
    minutes: 13,
    content: [
      {"type":"p","text":"Lambdas is a core skill in the C++ path on InTelleX. You will learn lambdas with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Lambdas","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"auto add = [](int a, int b) { return a + b; };","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice lambdas with a small exercise of your own."},
      {"type":"keypoints","items":["Lambdas is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-auto-decltype",
    title: "auto & type deduction",
    description: "Let the compiler deduce types safely.",
    level: "intermediate",
    section: "Modern C++",
    order: 36,
    minutes: 13,
    content: [
      {"type":"p","text":"auto & type deduction is a core skill in the C++ path on InTelleX. You will learn auto & type deduction with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind auto & type deduction","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice auto & type deduction with a small exercise of your own."},
      {"type":"keypoints","items":["auto & type deduction is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-smart-pointers",
    title: "unique_ptr & shared_ptr",
    description: "Own resources without manual delete.",
    level: "intermediate",
    section: "Modern C++",
    order: 37,
    minutes: 13,
    content: [
      {"type":"p","text":"unique_ptr & shared_ptr is a core skill in the C++ path on InTelleX. You will learn unique_ptr & shared_ptr with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind unique_ptr & shared_ptr","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"#include <memory>\nauto p = std::make_unique<int>(42);","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice unique_ptr & shared_ptr with a small exercise of your own."},
      {"type":"keypoints","items":["unique_ptr & shared_ptr is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-move-semantics",
    title: "Move Semantics",
    description: "std::move and rvalue references at a practical level.",
    level: "intermediate",
    section: "Modern C++",
    order: 38,
    minutes: 13,
    content: [
      {"type":"p","text":"Move Semantics is a core skill in the C++ path on InTelleX. You will learn move semantics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Move Semantics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice move semantics with a small exercise of your own."},
      {"type":"keypoints","items":["Move Semantics is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-exceptions",
    title: "Exceptions",
    description: "try/catch and when not to throw across APIs.",
    level: "intermediate",
    section: "Reliability",
    order: 39,
    minutes: 13,
    content: [
      {"type":"p","text":"Exceptions is a core skill in the C++ path on InTelleX. You will learn exceptions with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Exceptions","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"try {\n  mightFail();\n} catch (const std::exception& e) {\n  std::cerr << e.what();\n}","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice exceptions with a small exercise of your own."},
      {"type":"keypoints","items":["Exceptions is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-file-io",
    title: "File I/O",
    description: "Read and write text files with fstream.",
    level: "intermediate",
    section: "Reliability",
    order: 40,
    minutes: 13,
    content: [
      {"type":"p","text":"File I/O is a core skill in the C++ path on InTelleX. You will learn file i/o with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind File I/O","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"#include <fstream>\nstd::ofstream out(\"out.txt\");\nout << \"hello\\n\";","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice file i/o with a small exercise of your own."},
      {"type":"keypoints","items":["File I/O is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-namespaces",
    title: "Namespaces",
    description: "Organize symbols and avoid collisions.",
    level: "intermediate",
    section: "Projects",
    order: 41,
    minutes: 13,
    content: [
      {"type":"p","text":"Namespaces is a core skill in the C++ path on InTelleX. You will learn namespaces with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Namespaces","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice namespaces with a small exercise of your own."},
      {"type":"keypoints","items":["Namespaces is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-cmake-basics",
    title: "CMake Basics",
    description: "Build multi-file projects with CMake.",
    level: "intermediate",
    section: "Projects",
    order: 42,
    minutes: 13,
    content: [
      {"type":"p","text":"CMake Basics is a core skill in the C++ path on InTelleX. You will learn cmake basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind CMake Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"cmake_minimum_required(VERSION 3.16)\nproject(demo)\nadd_executable(demo main.cpp)","title":"Example","language":"cmake"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice cmake basics with a small exercise of your own."},
      {"type":"keypoints","items":["CMake Basics is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-debugging",
    title: "Debugging with gdb/lldb",
    description: "Breakpoints, backtraces, and inspecting variables.",
    level: "intermediate",
    section: "Projects",
    order: 43,
    minutes: 13,
    content: [
      {"type":"p","text":"Debugging with gdb/lldb is a core skill in the C++ path on InTelleX. You will learn debugging with gdb/lldb with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Debugging with gdb/lldb","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice debugging with gdb/lldb with a small exercise of your own."},
      {"type":"keypoints","items":["Debugging with gdb/lldb is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-testing-intro",
    title: "Unit Testing Intro",
    description: "Structure small tests for functions and classes.",
    level: "intermediate",
    section: "Projects",
    order: 44,
    minutes: 13,
    content: [
      {"type":"p","text":"Unit Testing Intro is a core skill in the C++ path on InTelleX. You will learn unit testing intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Unit Testing Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice unit testing intro with a small exercise of your own."},
      {"type":"keypoints","items":["Unit Testing Intro is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-templates-intro",
    title: "Function Templates",
    description: "Write generic functions with templates.",
    level: "intermediate",
    section: "Templates",
    order: 45,
    minutes: 13,
    content: [
      {"type":"p","text":"Function Templates is a core skill in the C++ path on InTelleX. You will learn function templates with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Function Templates","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"template <typename T>\nT maxv(T a, T b) { return a > b ? a : b; }","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice function templates with a small exercise of your own."},
      {"type":"keypoints","items":["Function Templates is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-class-templates",
    title: "Class Templates",
    description: "Generic containers and utility types.",
    level: "intermediate",
    section: "Templates",
    order: 46,
    minutes: 13,
    content: [
      {"type":"p","text":"Class Templates is a core skill in the C++ path on InTelleX. You will learn class templates with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Class Templates","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice class templates with a small exercise of your own."},
      {"type":"keypoints","items":["Class Templates is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-project-gradebook",
    title: "Project: Gradebook",
    description: "Build a gradebook with classes, vectors, and file save.",
    level: "intermediate",
    section: "Capstone Labs",
    order: 47,
    minutes: 20,
    content: [
      {"type":"p","text":"Project: Gradebook is a core skill in the C++ path on InTelleX. You will learn project: gradebook with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Gradebook","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice project: gradebook with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Gradebook is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "cpp-project-todo",
    title: "Project: Todo CLI",
    description: "CRUD todos with persistence.",
    level: "intermediate",
    section: "Capstone Labs",
    order: 48,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: Todo CLI is a core skill in the C++ path on InTelleX. You will learn project: todo cli with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Todo CLI","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your C++ lab folder as you go."},
      {"type":"try","text":"Practice project: todo cli with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Todo CLI is an essential C++ skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
