import type { TutorialLesson } from '../types';

export const advancedLessons: TutorialLesson[] = [
  {
    slug: "rust-pin-async-internals-glimpse",
    title: "Pin & Async Internals Glimpse",
    description: "Why Pin exists.",
    level: "advanced",
    section: "Advanced Topics",
    order: 49,
    minutes: 16,
    content: [
      {"type":"p","text":"Pin & Async Internals Glimpse is a core skill in the Rust path on InTelleX. You will learn pin & async internals glimpse with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Pin & Async Internals Glimpse","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice pin & async internals glimpse with a small exercise of your own."},
      {"type":"keypoints","items":["Pin & Async Internals Glimpse is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-capstone-concurrent-crawler",
    title: "Capstone: Concurrent Crawler",
    description: "Fetch URLs with bounded concurrency.",
    level: "advanced",
    section: "Advanced Topics",
    order: 50,
    minutes: 22,
    content: [
      {"type":"p","text":"Capstone: Concurrent Crawler is a core skill in the Rust path on InTelleX. You will learn capstone: concurrent crawler with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Concurrent Crawler","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice capstone: concurrent crawler with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Concurrent Crawler is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-capstone-cli-toolkit",
    title: "Capstone: CLI Toolkit",
    description: "Multi-command tool with clap-style args.",
    level: "advanced",
    section: "Capstone & Career",
    order: 51,
    minutes: 20,
    content: [
      {"type":"p","text":"Capstone: CLI Toolkit is a core skill in the Rust path on InTelleX. You will learn capstone: cli toolkit with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: CLI Toolkit","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice capstone: cli toolkit with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: CLI Toolkit is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-rust-interview-review",
    title: "Rust Interview Review",
    description: "Ownership, traits, Result, concurrency.",
    level: "advanced",
    section: "Capstone & Career",
    order: 52,
    minutes: 16,
    content: [
      {"type":"p","text":"Rust Interview Review is a core skill in the Rust path on InTelleX. You will learn rust interview review with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Rust Interview Review","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice rust interview review with a small exercise of your own."},
      {"type":"keypoints","items":["Rust Interview Review is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-publishing-crates",
    title: "Publishing Crates",
    description: "crates.io overview.",
    level: "advanced",
    section: "Capstone & Career",
    order: 53,
    minutes: 16,
    content: [
      {"type":"p","text":"Publishing Crates is a core skill in the Rust path on InTelleX. You will learn publishing crates with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Publishing Crates","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice publishing crates with a small exercise of your own."},
      {"type":"keypoints","items":["Publishing Crates is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-next-steps",
    title: "Next Steps",
    description: "Web (Axum), embedded, or WASM.",
    level: "advanced",
    section: "Capstone & Career",
    order: 54,
    minutes: 16,
    content: [
      {"type":"p","text":"Next Steps is a core skill in the Rust path on InTelleX. You will learn next steps with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Next Steps","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice next steps with a small exercise of your own."},
      {"type":"keypoints","items":["Next Steps is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-final-challenge",
    title: "Final Challenge",
    description: "Rewrite a Python script in safe Rust.",
    level: "advanced",
    section: "Capstone & Career",
    order: 55,
    minutes: 16,
    content: [
      {"type":"p","text":"Final Challenge is a core skill in the Rust path on InTelleX. You will learn final challenge with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Final Challenge","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice final challenge with a small exercise of your own."},
      {"type":"keypoints","items":["Final Challenge is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-glossary-drill",
    title: "Glossary Drill",
    description: "Ownership, borrowing, lifetime, trait, crate.",
    level: "advanced",
    section: "Capstone & Career",
    order: 56,
    minutes: 16,
    content: [
      {"type":"p","text":"Glossary Drill is a core skill in the Rust path on InTelleX. You will learn glossary drill with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Glossary Drill","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice glossary drill with a small exercise of your own."},
      {"type":"keypoints","items":["Glossary Drill is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-reading-compiler-errors",
    title: "Reading Compiler Errors",
    description: "Turn rustc messages into fixes.",
    level: "advanced",
    section: "Capstone & Career",
    order: 57,
    minutes: 16,
    content: [
      {"type":"p","text":"Reading Compiler Errors is a core skill in the Rust path on InTelleX. You will learn reading compiler errors with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Reading Compiler Errors","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice reading compiler errors with a small exercise of your own."},
      {"type":"keypoints","items":["Reading Compiler Errors is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-performance-checklist",
    title: "Performance Checklist",
    description: "Allocations, clones, and profiles.",
    level: "advanced",
    section: "Capstone & Career",
    order: 58,
    minutes: 16,
    content: [
      {"type":"p","text":"Performance Checklist is a core skill in the Rust path on InTelleX. You will learn performance checklist with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Performance Checklist","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice performance checklist with a small exercise of your own."},
      {"type":"keypoints","items":["Performance Checklist is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-safety-checklist",
    title: "Safety Checklist",
    description: "Avoid unsafe unless measured need.",
    level: "advanced",
    section: "Capstone & Career",
    order: 59,
    minutes: 16,
    content: [
      {"type":"p","text":"Safety Checklist is a core skill in the Rust path on InTelleX. You will learn safety checklist with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Safety Checklist","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice safety checklist with a small exercise of your own."},
      {"type":"keypoints","items":["Safety Checklist is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-portfolio-tips",
    title: "Portfolio Tips",
    description: "Show cargo projects with README and tests.",
    level: "advanced",
    section: "Capstone & Career",
    order: 60,
    minutes: 16,
    content: [
      {"type":"p","text":"Portfolio Tips is a core skill in the Rust path on InTelleX. You will learn portfolio tips with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Portfolio Tips","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice portfolio tips with a small exercise of your own."},
      {"type":"keypoints","items":["Portfolio Tips is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-extra-61",
    title: "Practice Lab 61",
    description: "Hands-on practice lab consolidating earlier rust skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 61,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 61 is a core skill in the Rust path on InTelleX. You will learn practice lab 61 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 61","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 61 is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-extra-62",
    title: "Practice Lab 62",
    description: "Hands-on practice lab consolidating earlier rust skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 62,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 62 is a core skill in the Rust path on InTelleX. You will learn practice lab 62 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 62","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 62 is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-extra-63",
    title: "Practice Lab 63",
    description: "Hands-on practice lab consolidating earlier rust skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 63,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 63 is a core skill in the Rust path on InTelleX. You will learn practice lab 63 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 63","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 63 is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-extra-64",
    title: "Practice Lab 64",
    description: "Hands-on practice lab consolidating earlier rust skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 64,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 64 is a core skill in the Rust path on InTelleX. You will learn practice lab 64 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 64","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 64 is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-extra-65",
    title: "Practice Lab 65",
    description: "Hands-on practice lab consolidating earlier rust skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 65,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 65 is a core skill in the Rust path on InTelleX. You will learn practice lab 65 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 65","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 65 is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
