import type { TutorialLesson } from '../types';

export const beginnerLessons: TutorialLesson[] = [
  {
    slug: "rust-welcome-to-rust",
    title: "Welcome to Rust",
    description: "Safety, speed, and fearless concurrency.",
    level: "beginner",
    section: "Getting Started",
    order: 1,
    minutes: 11,
    content: [
      {"type":"p","text":"Welcome to Rust is a core skill in the Rust path on InTelleX. You will learn welcome to rust with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Welcome to Rust","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"fn main() {\n    println!(\"Hello, Rust\");\n}","title":"Example","language":"rust"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice welcome to rust with a small exercise of your own."},
      {"type":"keypoints","items":["Welcome to Rust is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-install-rustup",
    title: "Install Rustup",
    description: "Install toolchain and cargo.",
    level: "beginner",
    section: "Getting Started",
    order: 2,
    minutes: 11,
    content: [
      {"type":"p","text":"Install Rustup is a core skill in the Rust path on InTelleX. You will learn install rustup with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Install Rustup","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"rustc --version\ncargo --version","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice install rustup with a small exercise of your own."},
      {"type":"keypoints","items":["Install Rustup is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-cargo-new",
    title: "Cargo New",
    description: "Create and run a package.",
    level: "beginner",
    section: "Getting Started",
    order: 3,
    minutes: 11,
    content: [
      {"type":"p","text":"Cargo New is a core skill in the Rust path on InTelleX. You will learn cargo new with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Cargo New","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"cargo new hello\ncd hello\ncargo run","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice cargo new with a small exercise of your own."},
      {"type":"keypoints","items":["Cargo New is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-variables-mutability",
    title: "Variables & Mutability",
    description: "let, mut, and shadowing.",
    level: "beginner",
    section: "Getting Started",
    order: 4,
    minutes: 11,
    content: [
      {"type":"p","text":"Variables & Mutability is a core skill in the Rust path on InTelleX. You will learn variables & mutability with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Variables & Mutability","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"let mut x = 5;\nx += 1;","title":"Example","language":"rust"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice variables & mutability with a small exercise of your own."},
      {"type":"keypoints","items":["Variables & Mutability is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-data-types",
    title: "Data Types",
    description: "Scalars and compounds.",
    level: "beginner",
    section: "Getting Started",
    order: 5,
    minutes: 11,
    content: [
      {"type":"p","text":"Data Types is a core skill in the Rust path on InTelleX. You will learn data types with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Data Types","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"let t: (i32, f64) = (1, 2.0);\nlet a = [1, 2, 3];","title":"Example","language":"rust"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice data types with a small exercise of your own."},
      {"type":"keypoints","items":["Data Types is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-ownership-rules",
    title: "Ownership Rules",
    description: "The heart of Rust memory safety.",
    level: "beginner",
    section: "Ownership",
    order: 6,
    minutes: 11,
    content: [
      {"type":"p","text":"Ownership Rules is a core skill in the Rust path on InTelleX. You will learn ownership rules with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Ownership Rules","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice ownership rules with a small exercise of your own."},
      {"type":"keypoints","items":["Ownership Rules is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-move-semantics",
    title: "Move Semantics",
    description: "What happens when you assign a String.",
    level: "beginner",
    section: "Ownership",
    order: 7,
    minutes: 11,
    content: [
      {"type":"p","text":"Move Semantics is a core skill in the Rust path on InTelleX. You will learn move semantics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Move Semantics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice move semantics with a small exercise of your own."},
      {"type":"keypoints","items":["Move Semantics is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-references-borrowing",
    title: "References & Borrowing",
    description: "Shared and mutable borrows.",
    level: "beginner",
    section: "Ownership",
    order: 8,
    minutes: 11,
    content: [
      {"type":"p","text":"References & Borrowing is a core skill in the Rust path on InTelleX. You will learn references & borrowing with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind References & Borrowing","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"fn len(s: &String) -> usize { s.len() }","title":"Example","language":"rust"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice references & borrowing with a small exercise of your own."},
      {"type":"keypoints","items":["References & Borrowing is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-slices",
    title: "Slices",
    description: "Views into contiguous data.",
    level: "beginner",
    section: "Ownership",
    order: 9,
    minutes: 11,
    content: [
      {"type":"p","text":"Slices is a core skill in the Rust path on InTelleX. You will learn slices with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Slices","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice slices with a small exercise of your own."},
      {"type":"keypoints","items":["Slices is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-ownership-drills",
    title: "Ownership Drills",
    description: "Fix compile errors caused by moves.",
    level: "beginner",
    section: "Ownership",
    order: 10,
    minutes: 14,
    content: [
      {"type":"p","text":"Ownership Drills is a core skill in the Rust path on InTelleX. You will learn ownership drills with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Ownership Drills","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice ownership drills with a small exercise of your own."},
      {"type":"keypoints","items":["Ownership Drills is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-structs",
    title: "Structs",
    description: "Group data with named fields.",
    level: "beginner",
    section: "Structs & Enums",
    order: 11,
    minutes: 11,
    content: [
      {"type":"p","text":"Structs is a core skill in the Rust path on InTelleX. You will learn structs with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Structs","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice structs with a small exercise of your own."},
      {"type":"keypoints","items":["Structs is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-methods-impl",
    title: "Methods & impl",
    description: "Implement behavior on types.",
    level: "beginner",
    section: "Structs & Enums",
    order: 12,
    minutes: 11,
    content: [
      {"type":"p","text":"Methods & impl is a core skill in the Rust path on InTelleX. You will learn methods & impl with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Methods & impl","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice methods & impl with a small exercise of your own."},
      {"type":"keypoints","items":["Methods & impl is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-enums",
    title: "Enums",
    description: "Express variants clearly.",
    level: "beginner",
    section: "Structs & Enums",
    order: 13,
    minutes: 11,
    content: [
      {"type":"p","text":"Enums is a core skill in the Rust path on InTelleX. You will learn enums with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Enums","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice enums with a small exercise of your own."},
      {"type":"keypoints","items":["Enums is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-option-result",
    title: "Option & Result",
    description: "Null-safe and error-aware returns.",
    level: "beginner",
    section: "Structs & Enums",
    order: 14,
    minutes: 11,
    content: [
      {"type":"p","text":"Option & Result is a core skill in the Rust path on InTelleX. You will learn option & result with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Option & Result","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"fn parse(s: &str) -> Result<i32, std::num::ParseIntError> {\n    s.parse()\n}","title":"Example","language":"rust"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice option & result with a small exercise of your own."},
      {"type":"keypoints","items":["Option & Result is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-pattern-matching",
    title: "Pattern Matching",
    description: "match like a pro.",
    level: "beginner",
    section: "Structs & Enums",
    order: 15,
    minutes: 11,
    content: [
      {"type":"p","text":"Pattern Matching is a core skill in the Rust path on InTelleX. You will learn pattern matching with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Pattern Matching","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice pattern matching with a small exercise of your own."},
      {"type":"keypoints","items":["Pattern Matching is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-vec",
    title: "Vec",
    description: "Growable arrays.",
    level: "beginner",
    section: "Collections & Errors",
    order: 16,
    minutes: 11,
    content: [
      {"type":"p","text":"Vec is a core skill in the Rust path on InTelleX. You will learn vec with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Vec","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice vec with a small exercise of your own."},
      {"type":"keypoints","items":["Vec is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-hashmap",
    title: "HashMap",
    description: "Key-value maps.",
    level: "beginner",
    section: "Collections & Errors",
    order: 17,
    minutes: 11,
    content: [
      {"type":"p","text":"HashMap is a core skill in the Rust path on InTelleX. You will learn hashmap with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind HashMap","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice hashmap with a small exercise of your own."},
      {"type":"keypoints","items":["HashMap is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-string-vs-str",
    title: "String vs &str",
    description: "Owned vs borrowed text.",
    level: "beginner",
    section: "Collections & Errors",
    order: 18,
    minutes: 11,
    content: [
      {"type":"p","text":"String vs &str is a core skill in the Rust path on InTelleX. You will learn string vs &str with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind String vs &str","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice string vs &str with a small exercise of your own."},
      {"type":"keypoints","items":["String vs &str is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-error-propagation",
    title: "Error Propagation",
    description: "The ? operator.",
    level: "beginner",
    section: "Collections & Errors",
    order: 19,
    minutes: 11,
    content: [
      {"type":"p","text":"Error Propagation is a core skill in the Rust path on InTelleX. You will learn error propagation with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Error Propagation","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice error propagation with a small exercise of your own."},
      {"type":"keypoints","items":["Error Propagation is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-project-cli-grep-lite",
    title: "Project: CLI Grep Lite",
    description: "Search lines in a file.",
    level: "beginner",
    section: "Collections & Errors",
    order: 20,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: CLI Grep Lite is a core skill in the Rust path on InTelleX. You will learn project: cli grep lite with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: CLI Grep Lite","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice project: cli grep lite with a small exercise of your own."},
      {"type":"keypoints","items":["Project: CLI Grep Lite is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-modules",
    title: "Modules",
    description: "mod, use, and visibility.",
    level: "beginner",
    section: "Modules & Packaging",
    order: 21,
    minutes: 11,
    content: [
      {"type":"p","text":"Modules is a core skill in the Rust path on InTelleX. You will learn modules with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Modules","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice modules with a small exercise of your own."},
      {"type":"keypoints","items":["Modules is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-workspaces",
    title: "Workspaces",
    description: "Multi-crate repos.",
    level: "beginner",
    section: "Modules & Packaging",
    order: 22,
    minutes: 11,
    content: [
      {"type":"p","text":"Workspaces is a core skill in the Rust path on InTelleX. You will learn workspaces with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Workspaces","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice workspaces with a small exercise of your own."},
      {"type":"keypoints","items":["Workspaces is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-traits",
    title: "Traits",
    description: "Shared behavior across types.",
    level: "beginner",
    section: "Modules & Packaging",
    order: 23,
    minutes: 11,
    content: [
      {"type":"p","text":"Traits is a core skill in the Rust path on InTelleX. You will learn traits with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Traits","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice traits with a small exercise of your own."},
      {"type":"keypoints","items":["Traits is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-generics",
    title: "Generics",
    description: "Type parameters done safely.",
    level: "beginner",
    section: "Modules & Packaging",
    order: 24,
    minutes: 11,
    content: [
      {"type":"p","text":"Generics is a core skill in the Rust path on InTelleX. You will learn generics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Generics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice generics with a small exercise of your own."},
      {"type":"keypoints","items":["Generics is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-lifetimes-intro",
    title: "Lifetimes Intro",
    description: "Why the compiler asks about 'a.",
    level: "beginner",
    section: "Modules & Packaging",
    order: 25,
    minutes: 11,
    content: [
      {"type":"p","text":"Lifetimes Intro is a core skill in the Rust path on InTelleX. You will learn lifetimes intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Lifetimes Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice lifetimes intro with a small exercise of your own."},
      {"type":"keypoints","items":["Lifetimes Intro is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
