import type { TutorialLesson } from '../types';

export const intermediateLessons: TutorialLesson[] = [
  {
    slug: "rust-iterators",
    title: "Iterators",
    description: "Lazy adapters and collect.",
    level: "intermediate",
    section: "Intermediate Rust",
    order: 26,
    minutes: 13,
    content: [
      {"type":"p","text":"Iterators is a core skill in the Rust path on InTelleX. You will learn iterators with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Iterators","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice iterators with a small exercise of your own."},
      {"type":"keypoints","items":["Iterators is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-closures",
    title: "Closures",
    description: "Capture environments.",
    level: "intermediate",
    section: "Intermediate Rust",
    order: 27,
    minutes: 13,
    content: [
      {"type":"p","text":"Closures is a core skill in the Rust path on InTelleX. You will learn closures with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Closures","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice closures with a small exercise of your own."},
      {"type":"keypoints","items":["Closures is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-smart-pointers",
    title: "Smart Pointers",
    description: "Box, Rc, RefCell overview.",
    level: "intermediate",
    section: "Intermediate Rust",
    order: 28,
    minutes: 13,
    content: [
      {"type":"p","text":"Smart Pointers is a core skill in the Rust path on InTelleX. You will learn smart pointers with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Smart Pointers","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice smart pointers with a small exercise of your own."},
      {"type":"keypoints","items":["Smart Pointers is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-testing-with-cargo-test",
    title: "Testing with cargo test",
    description: "Unit and integration tests.",
    level: "intermediate",
    section: "Intermediate Rust",
    order: 29,
    minutes: 13,
    content: [
      {"type":"p","text":"Testing with cargo test is a core skill in the Rust path on InTelleX. You will learn testing with cargo test with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Testing with cargo test","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice testing with cargo test with a small exercise of your own."},
      {"type":"keypoints","items":["Testing with cargo test is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-project-json-config-tool",
    title: "Project: JSON Config Tool",
    description: "Read config and validate fields.",
    level: "intermediate",
    section: "Intermediate Rust",
    order: 30,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: JSON Config Tool is a core skill in the Rust path on InTelleX. You will learn project: json config tool with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: JSON Config Tool","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice project: json config tool with a small exercise of your own."},
      {"type":"keypoints","items":["Project: JSON Config Tool is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-threads",
    title: "Threads",
    description: "std::thread basics.",
    level: "intermediate",
    section: "Concurrency",
    order: 31,
    minutes: 13,
    content: [
      {"type":"p","text":"Threads is a core skill in the Rust path on InTelleX. You will learn threads with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Threads","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice threads with a small exercise of your own."},
      {"type":"keypoints","items":["Threads is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-message-passing",
    title: "Message Passing",
    description: "channels for ownership transfer.",
    level: "intermediate",
    section: "Concurrency",
    order: 32,
    minutes: 13,
    content: [
      {"type":"p","text":"Message Passing is a core skill in the Rust path on InTelleX. You will learn message passing with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Message Passing","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice message passing with a small exercise of your own."},
      {"type":"keypoints","items":["Message Passing is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-shared-state",
    title: "Shared State",
    description: "Mutex and Arc.",
    level: "intermediate",
    section: "Concurrency",
    order: 33,
    minutes: 13,
    content: [
      {"type":"p","text":"Shared State is a core skill in the Rust path on InTelleX. You will learn shared state with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Shared State","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice shared state with a small exercise of your own."},
      {"type":"keypoints","items":["Shared State is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-async-preview",
    title: "Async Preview",
    description: "async/await mental model.",
    level: "intermediate",
    section: "Concurrency",
    order: 34,
    minutes: 13,
    content: [
      {"type":"p","text":"Async Preview is a core skill in the Rust path on InTelleX. You will learn async preview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Async Preview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice async preview with a small exercise of your own."},
      {"type":"keypoints","items":["Async Preview is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-project-parallel-map",
    title: "Project: Parallel Map",
    description: "Split work across threads.",
    level: "intermediate",
    section: "Concurrency",
    order: 35,
    minutes: 16,
    content: [
      {"type":"p","text":"Project: Parallel Map is a core skill in the Rust path on InTelleX. You will learn project: parallel map with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Parallel Map","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice project: parallel map with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Parallel Map is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-unsafe-rust-boundaries",
    title: "Unsafe Rust Boundaries",
    description: "When and how to use unsafe carefully.",
    level: "intermediate",
    section: "Systems & FFI",
    order: 36,
    minutes: 13,
    content: [
      {"type":"p","text":"Unsafe Rust Boundaries is a core skill in the Rust path on InTelleX. You will learn unsafe rust boundaries with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Unsafe Rust Boundaries","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice unsafe rust boundaries with a small exercise of your own."},
      {"type":"keypoints","items":["Unsafe Rust Boundaries is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-ffi-overview",
    title: "FFI Overview",
    description: "Call C from Rust.",
    level: "intermediate",
    section: "Systems & FFI",
    order: 37,
    minutes: 13,
    content: [
      {"type":"p","text":"FFI Overview is a core skill in the Rust path on InTelleX. You will learn ffi overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind FFI Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice ffi overview with a small exercise of your own."},
      {"type":"keypoints","items":["FFI Overview is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-no-std-glimpse",
    title: "no_std Glimpse",
    description: "Embedded Rust direction.",
    level: "intermediate",
    section: "Systems & FFI",
    order: 38,
    minutes: 13,
    content: [
      {"type":"p","text":"no_std Glimpse is a core skill in the Rust path on InTelleX. You will learn no_std glimpse with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind no_std Glimpse","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice no_std glimpse with a small exercise of your own."},
      {"type":"keypoints","items":["no_std Glimpse is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-profiling-basics",
    title: "Profiling Basics",
    description: "Measure before optimizing.",
    level: "intermediate",
    section: "Systems & FFI",
    order: 39,
    minutes: 13,
    content: [
      {"type":"p","text":"Profiling Basics is a core skill in the Rust path on InTelleX. You will learn profiling basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Profiling Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice profiling basics with a small exercise of your own."},
      {"type":"keypoints","items":["Profiling Basics is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-project-http-fetcher",
    title: "Project: HTTP Fetcher",
    description: "reqwest-style client sketch.",
    level: "intermediate",
    section: "Systems & FFI",
    order: 40,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: HTTP Fetcher is a core skill in the Rust path on InTelleX. You will learn project: http fetcher with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: HTTP Fetcher","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice project: http fetcher with a small exercise of your own."},
      {"type":"keypoints","items":["Project: HTTP Fetcher is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-clippy-rustfmt",
    title: "Clippy & rustfmt",
    description: "Lint and format automatically.",
    level: "intermediate",
    section: "Idiomatic Rust",
    order: 41,
    minutes: 13,
    content: [
      {"type":"p","text":"Clippy & rustfmt is a core skill in the Rust path on InTelleX. You will learn clippy & rustfmt with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Clippy & rustfmt","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice clippy & rustfmt with a small exercise of your own."},
      {"type":"keypoints","items":["Clippy & rustfmt is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-documentation-tests",
    title: "Documentation Tests",
    description: "Examples that compile in docs.",
    level: "intermediate",
    section: "Idiomatic Rust",
    order: 42,
    minutes: 13,
    content: [
      {"type":"p","text":"Documentation Tests is a core skill in the Rust path on InTelleX. You will learn documentation tests with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Documentation Tests","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice documentation tests with a small exercise of your own."},
      {"type":"keypoints","items":["Documentation Tests is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-error-design",
    title: "Error Design",
    description: "thiserror/anyhow patterns conceptually.",
    level: "intermediate",
    section: "Idiomatic Rust",
    order: 43,
    minutes: 13,
    content: [
      {"type":"p","text":"Error Design is a core skill in the Rust path on InTelleX. You will learn error design with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Error Design","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice error design with a small exercise of your own."},
      {"type":"keypoints","items":["Error Design is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-api-design-tips",
    title: "API Design Tips",
    description: "Ownership-friendly interfaces.",
    level: "intermediate",
    section: "Idiomatic Rust",
    order: 44,
    minutes: 13,
    content: [
      {"type":"p","text":"API Design Tips is a core skill in the Rust path on InTelleX. You will learn api design tips with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind API Design Tips","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice api design tips with a small exercise of your own."},
      {"type":"keypoints","items":["API Design Tips is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-project-mini-database",
    title: "Project: Mini Database",
    description: "In-memory KV with persistence.",
    level: "intermediate",
    section: "Idiomatic Rust",
    order: 45,
    minutes: 20,
    content: [
      {"type":"p","text":"Project: Mini Database is a core skill in the Rust path on InTelleX. You will learn project: mini database with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Mini Database","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice project: mini database with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Mini Database is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-advanced-lifetimes",
    title: "Advanced Lifetimes",
    description: "Structs that hold references.",
    level: "intermediate",
    section: "Advanced Topics",
    order: 46,
    minutes: 13,
    content: [
      {"type":"p","text":"Advanced Lifetimes is a core skill in the Rust path on InTelleX. You will learn advanced lifetimes with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Advanced Lifetimes","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice advanced lifetimes with a small exercise of your own."},
      {"type":"keypoints","items":["Advanced Lifetimes is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-trait-objects",
    title: "Trait Objects",
    description: "dyn Trait for dynamic dispatch.",
    level: "intermediate",
    section: "Advanced Topics",
    order: 47,
    minutes: 13,
    content: [
      {"type":"p","text":"Trait Objects is a core skill in the Rust path on InTelleX. You will learn trait objects with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Trait Objects","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice trait objects with a small exercise of your own."},
      {"type":"keypoints","items":["Trait Objects is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rust-macros-intro",
    title: "Macros Intro",
    description: "Declarative macros overview.",
    level: "intermediate",
    section: "Advanced Topics",
    order: 48,
    minutes: 13,
    content: [
      {"type":"p","text":"Macros Intro is a core skill in the Rust path on InTelleX. You will learn macros intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Macros Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Rust lab folder as you go."},
      {"type":"try","text":"Practice macros intro with a small exercise of your own."},
      {"type":"keypoints","items":["Macros Intro is an essential Rust skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
