import type { TutorialLesson } from '../types';

export const advancedLessons: TutorialLesson[] = [
  {
    slug: "linux-secrets-on-servers",
    title: "Secrets on Servers",
    description: "Never bake secrets into images.",
    level: "advanced",
    section: "Security Hardening",
    order: 49,
    minutes: 16,
    content: [
      {"type":"p","text":"Secrets on Servers is a core skill in the Linux Administration path on InTelleX. You will learn secrets on servers with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Secrets on Servers","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice secrets on servers with a small exercise of your own."},
      {"type":"keypoints","items":["Secrets on Servers is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-project-hardening-checklist",
    title: "Project: Hardening Checklist",
    description: "Apply a 15-point baseline.",
    level: "advanced",
    section: "Security Hardening",
    order: 50,
    minutes: 16,
    content: [
      {"type":"p","text":"Project: Hardening Checklist is a core skill in the Linux Administration path on InTelleX. You will learn project: hardening checklist with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Hardening Checklist","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice project: hardening checklist with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Hardening Checklist is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-capstone-production-like-vm",
    title: "Capstone: Production-like VM",
    description: "Users, firewall, nginx, TLS stub, monitoring.",
    level: "advanced",
    section: "Capstone & Career",
    order: 51,
    minutes: 22,
    content: [
      {"type":"p","text":"Capstone: Production-like VM is a core skill in the Linux Administration path on InTelleX. You will learn capstone: production-like vm with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Production-like VM","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice capstone: production-like vm with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Production-like VM is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-capstone-broken-server-drill",
    title: "Capstone: Broken Server Drill",
    description: "Fix networking/service failures under time.",
    level: "advanced",
    section: "Capstone & Career",
    order: 52,
    minutes: 20,
    content: [
      {"type":"p","text":"Capstone: Broken Server Drill is a core skill in the Linux Administration path on InTelleX. You will learn capstone: broken server drill with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Broken Server Drill","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice capstone: broken server drill with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Broken Server Drill is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-linux-interview-review",
    title: "Linux Interview Review",
    description: "Permissions, processes, systemd, networking.",
    level: "advanced",
    section: "Capstone & Career",
    order: 53,
    minutes: 16,
    content: [
      {"type":"p","text":"Linux Interview Review is a core skill in the Linux Administration path on InTelleX. You will learn linux interview review with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Linux Interview Review","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice linux interview review with a small exercise of your own."},
      {"type":"keypoints","items":["Linux Interview Review is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-next-steps",
    title: "Next Steps",
    description: "SRE, platform engineering, or security ops.",
    level: "advanced",
    section: "Capstone & Career",
    order: 54,
    minutes: 16,
    content: [
      {"type":"p","text":"Next Steps is a core skill in the Linux Administration path on InTelleX. You will learn next steps with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Next Steps","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice next steps with a small exercise of your own."},
      {"type":"keypoints","items":["Next Steps is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-final-challenge",
    title: "Final Challenge",
    description: "Document a runbook for restarting a stack.",
    level: "advanced",
    section: "Capstone & Career",
    order: 55,
    minutes: 16,
    content: [
      {"type":"p","text":"Final Challenge is a core skill in the Linux Administration path on InTelleX. You will learn final challenge with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Final Challenge","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice final challenge with a small exercise of your own."},
      {"type":"keypoints","items":["Final Challenge is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-glossary-drill",
    title: "Glossary Drill",
    description: "inode, daemon, unit, CIDR, journal.",
    level: "advanced",
    section: "Capstone & Career",
    order: 56,
    minutes: 16,
    content: [
      {"type":"p","text":"Glossary Drill is a core skill in the Linux Administration path on InTelleX. You will learn glossary drill with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Glossary Drill","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice glossary drill with a small exercise of your own."},
      {"type":"keypoints","items":["Glossary Drill is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-performance-checklist",
    title: "Performance Checklist",
    description: "CPU, RAM, disk, network bottlenecks.",
    level: "advanced",
    section: "Capstone & Career",
    order: 57,
    minutes: 16,
    content: [
      {"type":"p","text":"Performance Checklist is a core skill in the Linux Administration path on InTelleX. You will learn performance checklist with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Performance Checklist","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice performance checklist with a small exercise of your own."},
      {"type":"keypoints","items":["Performance Checklist is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-disaster-recovery-drill",
    title: "Disaster Recovery Drill",
    description: "Restore from backup successfully.",
    level: "advanced",
    section: "Capstone & Career",
    order: 58,
    minutes: 16,
    content: [
      {"type":"p","text":"Disaster Recovery Drill is a core skill in the Linux Administration path on InTelleX. You will learn disaster recovery drill with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Disaster Recovery Drill","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice disaster recovery drill with a small exercise of your own."},
      {"type":"keypoints","items":["Disaster Recovery Drill is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-portfolio-tips",
    title: "Portfolio Tips",
    description: "Show labs with diagrams and configs.",
    level: "advanced",
    section: "Capstone & Career",
    order: 59,
    minutes: 16,
    content: [
      {"type":"p","text":"Portfolio Tips is a core skill in the Linux Administration path on InTelleX. You will learn portfolio tips with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Portfolio Tips","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice portfolio tips with a small exercise of your own."},
      {"type":"keypoints","items":["Portfolio Tips is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-ethics-responsibility",
    title: "Ethics & Responsibility",
    description: "Admin access is production trust.",
    level: "advanced",
    section: "Capstone & Career",
    order: 60,
    minutes: 16,
    content: [
      {"type":"p","text":"Ethics & Responsibility is a core skill in the Linux Administration path on InTelleX. You will learn ethics & responsibility with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Ethics & Responsibility","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice ethics & responsibility with a small exercise of your own."},
      {"type":"keypoints","items":["Ethics & Responsibility is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-extra-61",
    title: "Practice Lab 61",
    description: "Hands-on practice lab consolidating earlier linux skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 61,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 61 is a core skill in the Linux Administration path on InTelleX. You will learn practice lab 61 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 61","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 61 is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-extra-62",
    title: "Practice Lab 62",
    description: "Hands-on practice lab consolidating earlier linux skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 62,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 62 is a core skill in the Linux Administration path on InTelleX. You will learn practice lab 62 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 62","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 62 is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-extra-63",
    title: "Practice Lab 63",
    description: "Hands-on practice lab consolidating earlier linux skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 63,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 63 is a core skill in the Linux Administration path on InTelleX. You will learn practice lab 63 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 63","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 63 is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-extra-64",
    title: "Practice Lab 64",
    description: "Hands-on practice lab consolidating earlier linux skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 64,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 64 is a core skill in the Linux Administration path on InTelleX. You will learn practice lab 64 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 64","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 64 is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-extra-65",
    title: "Practice Lab 65",
    description: "Hands-on practice lab consolidating earlier linux skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 65,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 65 is a core skill in the Linux Administration path on InTelleX. You will learn practice lab 65 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 65","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 65 is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
