import type { TutorialLesson } from '../types';

export const beginnerLessons: TutorialLesson[] = [
  {
    slug: "linux-welcome-to-linux-administration",
    title: "Welcome to Linux Administration",
    description: "Operate servers with confidence.",
    level: "beginner",
    section: "Getting Started",
    order: 1,
    minutes: 11,
    content: [
      {"type":"p","text":"Welcome to Linux Administration is a core skill in the Linux Administration path on InTelleX. You will learn welcome to linux administration with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Welcome to Linux Administration","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice welcome to linux administration with a small exercise of your own."},
      {"type":"keypoints","items":["Welcome to Linux Administration is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-distributions-overview",
    title: "Distributions Overview",
    description: "Debian/Ubuntu vs RHEL/Fedora families.",
    level: "beginner",
    section: "Getting Started",
    order: 2,
    minutes: 11,
    content: [
      {"type":"p","text":"Distributions Overview is a core skill in the Linux Administration path on InTelleX. You will learn distributions overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Distributions Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice distributions overview with a small exercise of your own."},
      {"type":"keypoints","items":["Distributions Overview is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-install-cloud-vms",
    title: "Install & Cloud VMs",
    description: "Local VM or cloud instance lab setup.",
    level: "beginner",
    section: "Getting Started",
    order: 3,
    minutes: 11,
    content: [
      {"type":"p","text":"Install & Cloud VMs is a core skill in the Linux Administration path on InTelleX. You will learn install & cloud vms with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Install & Cloud VMs","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice install & cloud vms with a small exercise of your own."},
      {"type":"keypoints","items":["Install & Cloud VMs is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-terminal-survival",
    title: "Terminal Survival",
    description: "Shell, prompts, and keyboard fluency.",
    level: "beginner",
    section: "Getting Started",
    order: 4,
    minutes: 11,
    content: [
      {"type":"p","text":"Terminal Survival is a core skill in the Linux Administration path on InTelleX. You will learn terminal survival with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Terminal Survival","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice terminal survival with a small exercise of your own."},
      {"type":"keypoints","items":["Terminal Survival is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-man-help",
    title: "man & --help",
    description: "Learn any command from its docs.",
    level: "beginner",
    section: "Getting Started",
    order: 5,
    minutes: 11,
    content: [
      {"type":"p","text":"man & --help is a core skill in the Linux Administration path on InTelleX. You will learn man & --help with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind man & --help","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"man ls\nls --help | less","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice man & --help with a small exercise of your own."},
      {"type":"keypoints","items":["man & --help is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-filesystem-hierarchy",
    title: "Filesystem Hierarchy",
    description: "/etc, /var, /home, /usr, /opt.",
    level: "beginner",
    section: "Filesystem",
    order: 6,
    minutes: 11,
    content: [
      {"type":"p","text":"Filesystem Hierarchy is a core skill in the Linux Administration path on InTelleX. You will learn filesystem hierarchy with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Filesystem Hierarchy","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice filesystem hierarchy with a small exercise of your own."},
      {"type":"keypoints","items":["Filesystem Hierarchy is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-navigation",
    title: "Navigation",
    description: "cd, ls, pwd, tree.",
    level: "beginner",
    section: "Filesystem",
    order: 7,
    minutes: 11,
    content: [
      {"type":"p","text":"Navigation is a core skill in the Linux Administration path on InTelleX. You will learn navigation with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Navigation","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"pwd\nls -la\ncd /var/log","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice navigation with a small exercise of your own."},
      {"type":"keypoints","items":["Navigation is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-files-directories",
    title: "Files & Directories",
    description: "cp, mv, rm, mkdir, ln.",
    level: "beginner",
    section: "Filesystem",
    order: 8,
    minutes: 11,
    content: [
      {"type":"p","text":"Files & Directories is a core skill in the Linux Administration path on InTelleX. You will learn files & directories with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Files & Directories","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice files & directories with a small exercise of your own."},
      {"type":"keypoints","items":["Files & Directories is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-permissions",
    title: "Permissions",
    description: "rwx, chmod, chown, umask.",
    level: "beginner",
    section: "Filesystem",
    order: 9,
    minutes: 11,
    content: [
      {"type":"p","text":"Permissions is a core skill in the Linux Administration path on InTelleX. You will learn permissions with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Permissions","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"chmod 640 secrets.txt\nchown alice:devs secrets.txt","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice permissions with a small exercise of your own."},
      {"type":"keypoints","items":["Permissions is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-finding-files",
    title: "Finding Files",
    description: "find, locate, which, type.",
    level: "beginner",
    section: "Filesystem",
    order: 10,
    minutes: 11,
    content: [
      {"type":"p","text":"Finding Files is a core skill in the Linux Administration path on InTelleX. You will learn finding files with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Finding Files","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice finding files with a small exercise of your own."},
      {"type":"keypoints","items":["Finding Files is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-users-groups",
    title: "Users & Groups",
    description: "useradd, usermod, /etc/passwd.",
    level: "beginner",
    section: "Users & Processes",
    order: 11,
    minutes: 11,
    content: [
      {"type":"p","text":"Users & Groups is a core skill in the Linux Administration path on InTelleX. You will learn users & groups with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Users & Groups","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice users & groups with a small exercise of your own."},
      {"type":"keypoints","items":["Users & Groups is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-sudo-root",
    title: "sudo & Root",
    description: "Least privilege administration.",
    level: "beginner",
    section: "Users & Processes",
    order: 12,
    minutes: 11,
    content: [
      {"type":"p","text":"sudo & Root is a core skill in the Linux Administration path on InTelleX. You will learn sudo & root with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind sudo & Root","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice sudo & root with a small exercise of your own."},
      {"type":"keypoints","items":["sudo & Root is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-processes",
    title: "Processes",
    description: "ps, top, htop, kill.",
    level: "beginner",
    section: "Users & Processes",
    order: 13,
    minutes: 11,
    content: [
      {"type":"p","text":"Processes is a core skill in the Linux Administration path on InTelleX. You will learn processes with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Processes","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"ps aux | head\ntop","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice processes with a small exercise of your own."},
      {"type":"keypoints","items":["Processes is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-job-control",
    title: "Job Control",
    description: "bg, fg, nohup, disown.",
    level: "beginner",
    section: "Users & Processes",
    order: 14,
    minutes: 11,
    content: [
      {"type":"p","text":"Job Control is a core skill in the Linux Administration path on InTelleX. You will learn job control with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Job Control","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice job control with a small exercise of your own."},
      {"type":"keypoints","items":["Job Control is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-systemd-services",
    title: "systemd Services",
    description: "systemctl start/enable/status.",
    level: "beginner",
    section: "Users & Processes",
    order: 15,
    minutes: 11,
    content: [
      {"type":"p","text":"systemd Services is a core skill in the Linux Administration path on InTelleX. You will learn systemd services with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind systemd Services","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"systemctl status ssh\nsystemctl enable nginx","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice systemd services with a small exercise of your own."},
      {"type":"keypoints","items":["systemd Services is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-apt-basics",
    title: "apt Basics",
    description: "Install and update on Debian/Ubuntu.",
    level: "beginner",
    section: "Packages & Software",
    order: 16,
    minutes: 11,
    content: [
      {"type":"p","text":"apt Basics is a core skill in the Linux Administration path on InTelleX. You will learn apt basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind apt Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"sudo apt update\nsudo apt install nginx","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice apt basics with a small exercise of your own."},
      {"type":"keypoints","items":["apt Basics is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-dnf-yum-basics",
    title: "dnf/yum Basics",
    description: "RHEL-family package workflow.",
    level: "beginner",
    section: "Packages & Software",
    order: 17,
    minutes: 11,
    content: [
      {"type":"p","text":"dnf/yum Basics is a core skill in the Linux Administration path on InTelleX. You will learn dnf/yum basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind dnf/yum Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice dnf/yum basics with a small exercise of your own."},
      {"type":"keypoints","items":["dnf/yum Basics is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-snaps-flatpaks-overview",
    title: "Snaps/Flatpaks Overview",
    description: "Alternative packaging systems.",
    level: "beginner",
    section: "Packages & Software",
    order: 18,
    minutes: 11,
    content: [
      {"type":"p","text":"Snaps/Flatpaks Overview is a core skill in the Linux Administration path on InTelleX. You will learn snaps/flatpaks overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Snaps/Flatpaks Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice snaps/flatpaks overview with a small exercise of your own."},
      {"type":"keypoints","items":["Snaps/Flatpaks Overview is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-compiling-from-source",
    title: "Compiling From Source",
    description: "When packages are not enough.",
    level: "beginner",
    section: "Packages & Software",
    order: 19,
    minutes: 11,
    content: [
      {"type":"p","text":"Compiling From Source is a core skill in the Linux Administration path on InTelleX. You will learn compiling from source with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Compiling From Source","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice compiling from source with a small exercise of your own."},
      {"type":"keypoints","items":["Compiling From Source is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-project-web-server-box",
    title: "Project: Web Server Box",
    description: "Install and serve a static site.",
    level: "beginner",
    section: "Packages & Software",
    order: 20,
    minutes: 16,
    content: [
      {"type":"p","text":"Project: Web Server Box is a core skill in the Linux Administration path on InTelleX. You will learn project: web server box with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Web Server Box","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice project: web server box with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Web Server Box is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-ip-addressing",
    title: "IP Addressing",
    description: "ip addr, routes, DNS basics.",
    level: "beginner",
    section: "Networking",
    order: 21,
    minutes: 11,
    content: [
      {"type":"p","text":"IP Addressing is a core skill in the Linux Administration path on InTelleX. You will learn ip addressing with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind IP Addressing","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice ip addressing with a small exercise of your own."},
      {"type":"keypoints","items":["IP Addressing is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-ss-listening-ports",
    title: "ss & Listening Ports",
    description: "See what is bound.",
    level: "beginner",
    section: "Networking",
    order: 22,
    minutes: 11,
    content: [
      {"type":"p","text":"ss & Listening Ports is a core skill in the Linux Administration path on InTelleX. You will learn ss & listening ports with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind ss & Listening Ports","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"ss -tulpn","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice ss & listening ports with a small exercise of your own."},
      {"type":"keypoints","items":["ss & Listening Ports is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-firewall-intro",
    title: "Firewall Intro",
    description: "ufw/firewalld mental model.",
    level: "beginner",
    section: "Networking",
    order: 23,
    minutes: 11,
    content: [
      {"type":"p","text":"Firewall Intro is a core skill in the Linux Administration path on InTelleX. You will learn firewall intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Firewall Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice firewall intro with a small exercise of your own."},
      {"type":"keypoints","items":["Firewall Intro is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-ssh-hardening",
    title: "SSH Hardening",
    description: "Keys, disable password, config.",
    level: "beginner",
    section: "Networking",
    order: 24,
    minutes: 11,
    content: [
      {"type":"p","text":"SSH Hardening is a core skill in the Linux Administration path on InTelleX. You will learn ssh hardening with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind SSH Hardening","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"ssh-keygen -t ed25519\nssh -i ~/.ssh/id_ed25519 user@host","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice ssh hardening with a small exercise of your own."},
      {"type":"keypoints","items":["SSH Hardening is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-project-secure-ssh-access",
    title: "Project: Secure SSH Access",
    description: "Key-only login checklist.",
    level: "beginner",
    section: "Networking",
    order: 25,
    minutes: 14,
    content: [
      {"type":"p","text":"Project: Secure SSH Access is a core skill in the Linux Administration path on InTelleX. You will learn project: secure ssh access with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Secure SSH Access","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice project: secure ssh access with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Secure SSH Access is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
