import type { TutorialLesson } from '../types';

export const intermediateLessons: TutorialLesson[] = [
  {
    slug: "linux-disks-partitions",
    title: "Disks & Partitions",
    description: "lsblk, fdisk overview.",
    level: "intermediate",
    section: "Storage",
    order: 26,
    minutes: 13,
    content: [
      {"type":"p","text":"Disks & Partitions is a core skill in the Linux Administration path on InTelleX. You will learn disks & partitions with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Disks & Partitions","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice disks & partitions with a small exercise of your own."},
      {"type":"keypoints","items":["Disks & Partitions is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-filesystems-mounts",
    title: "Filesystems & Mounts",
    description: "mkfs, mount, /etc/fstab.",
    level: "intermediate",
    section: "Storage",
    order: 27,
    minutes: 13,
    content: [
      {"type":"p","text":"Filesystems & Mounts is a core skill in the Linux Administration path on InTelleX. You will learn filesystems & mounts with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Filesystems & Mounts","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice filesystems & mounts with a small exercise of your own."},
      {"type":"keypoints","items":["Filesystems & Mounts is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-lvm-intro",
    title: "LVM Intro",
    description: "Flexible volume management.",
    level: "intermediate",
    section: "Storage",
    order: 28,
    minutes: 13,
    content: [
      {"type":"p","text":"LVM Intro is a core skill in the Linux Administration path on InTelleX. You will learn lvm intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind LVM Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice lvm intro with a small exercise of your own."},
      {"type":"keypoints","items":["LVM Intro is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-quotas-overview",
    title: "Quotas Overview",
    description: "Limit user disk usage.",
    level: "intermediate",
    section: "Storage",
    order: 29,
    minutes: 13,
    content: [
      {"type":"p","text":"Quotas Overview is a core skill in the Linux Administration path on InTelleX. You will learn quotas overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Quotas Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice quotas overview with a small exercise of your own."},
      {"type":"keypoints","items":["Quotas Overview is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-backups-mindset",
    title: "Backups Mindset",
    description: "3-2-1 and restore testing.",
    level: "intermediate",
    section: "Storage",
    order: 30,
    minutes: 13,
    content: [
      {"type":"p","text":"Backups Mindset is a core skill in the Linux Administration path on InTelleX. You will learn backups mindset with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Backups Mindset","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice backups mindset with a small exercise of your own."},
      {"type":"keypoints","items":["Backups Mindset is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-journalctl",
    title: "journalctl",
    description: "Query systemd logs.",
    level: "intermediate",
    section: "Logs & Monitoring",
    order: 31,
    minutes: 13,
    content: [
      {"type":"p","text":"journalctl is a core skill in the Linux Administration path on InTelleX. You will learn journalctl with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind journalctl","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"journalctl -u nginx -f","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice journalctl with a small exercise of your own."},
      {"type":"keypoints","items":["journalctl is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-var-log",
    title: "/var/log",
    description: "Classic log files still matter.",
    level: "intermediate",
    section: "Logs & Monitoring",
    order: 32,
    minutes: 13,
    content: [
      {"type":"p","text":"/var/log is a core skill in the Linux Administration path on InTelleX. You will learn /var/log with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind /var/log","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice /var/log with a small exercise of your own."},
      {"type":"keypoints","items":["/var/log is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-logrotate",
    title: "logrotate",
    description: "Prevent disks filling with logs.",
    level: "intermediate",
    section: "Logs & Monitoring",
    order: 33,
    minutes: 13,
    content: [
      {"type":"p","text":"logrotate is a core skill in the Linux Administration path on InTelleX. You will learn logrotate with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind logrotate","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice logrotate with a small exercise of your own."},
      {"type":"keypoints","items":["logrotate is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-resource-monitoring",
    title: "Resource Monitoring",
    description: "free, df, iostat, vmstat.",
    level: "intermediate",
    section: "Logs & Monitoring",
    order: 34,
    minutes: 13,
    content: [
      {"type":"p","text":"Resource Monitoring is a core skill in the Linux Administration path on InTelleX. You will learn resource monitoring with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Resource Monitoring","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice resource monitoring with a small exercise of your own."},
      {"type":"keypoints","items":["Resource Monitoring is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-project-incident-triage",
    title: "Project: Incident Triage",
    description: "Diagnose a full disk or high CPU.",
    level: "intermediate",
    section: "Logs & Monitoring",
    order: 35,
    minutes: 16,
    content: [
      {"type":"p","text":"Project: Incident Triage is a core skill in the Linux Administration path on InTelleX. You will learn project: incident triage with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Incident Triage","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice project: incident triage with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Incident Triage is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-cron-timers",
    title: "Cron & Timers",
    description: "Schedule admin tasks.",
    level: "intermediate",
    section: "Automation & Config",
    order: 36,
    minutes: 13,
    content: [
      {"type":"p","text":"Cron & Timers is a core skill in the Linux Administration path on InTelleX. You will learn cron & timers with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Cron & Timers","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice cron & timers with a small exercise of your own."},
      {"type":"keypoints","items":["Cron & Timers is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-shell-scripting-for-admins",
    title: "Shell Scripting for Admins",
    description: "Safe scripts with set -euo pipefail.",
    level: "intermediate",
    section: "Automation & Config",
    order: 37,
    minutes: 13,
    content: [
      {"type":"p","text":"Shell Scripting for Admins is a core skill in the Linux Administration path on InTelleX. You will learn shell scripting for admins with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Shell Scripting for Admins","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice shell scripting for admins with a small exercise of your own."},
      {"type":"keypoints","items":["Shell Scripting for Admins is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-configuration-management-preview",
    title: "Configuration Management Preview",
    description: "Ansible mental model.",
    level: "intermediate",
    section: "Automation & Config",
    order: 38,
    minutes: 13,
    content: [
      {"type":"p","text":"Configuration Management Preview is a core skill in the Linux Administration path on InTelleX. You will learn configuration management preview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Configuration Management Preview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice configuration management preview with a small exercise of your own."},
      {"type":"keypoints","items":["Configuration Management Preview is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-infrastructure-as-code-preview",
    title: "Infrastructure as Code Preview",
    description: "Terraform direction.",
    level: "intermediate",
    section: "Automation & Config",
    order: 39,
    minutes: 13,
    content: [
      {"type":"p","text":"Infrastructure as Code Preview is a core skill in the Linux Administration path on InTelleX. You will learn infrastructure as code preview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Infrastructure as Code Preview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice infrastructure as code preview with a small exercise of your own."},
      {"type":"keypoints","items":["Infrastructure as Code Preview is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-project-bootstrap-script",
    title: "Project: Bootstrap Script",
    description: "Idempotent server setup script.",
    level: "intermediate",
    section: "Automation & Config",
    order: 40,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: Bootstrap Script is a core skill in the Linux Administration path on InTelleX. You will learn project: bootstrap script with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Bootstrap Script","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice project: bootstrap script with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Bootstrap Script is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-docker-on-linux",
    title: "Docker on Linux",
    description: "Engine install and first container.",
    level: "intermediate",
    section: "Containers & Cloud",
    order: 41,
    minutes: 13,
    content: [
      {"type":"p","text":"Docker on Linux is a core skill in the Linux Administration path on InTelleX. You will learn docker on linux with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Docker on Linux","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice docker on linux with a small exercise of your own."},
      {"type":"keypoints","items":["Docker on Linux is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-systemd-docker",
    title: "systemd + Docker",
    description: "Restart policies and services.",
    level: "intermediate",
    section: "Containers & Cloud",
    order: 42,
    minutes: 13,
    content: [
      {"type":"p","text":"systemd + Docker is a core skill in the Linux Administration path on InTelleX. You will learn systemd + docker with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind systemd + Docker","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice systemd + docker with a small exercise of your own."},
      {"type":"keypoints","items":["systemd + Docker is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-cloud-metadata",
    title: "Cloud Metadata",
    description: "Think like a cloud admin.",
    level: "intermediate",
    section: "Containers & Cloud",
    order: 43,
    minutes: 13,
    content: [
      {"type":"p","text":"Cloud Metadata is a core skill in the Linux Administration path on InTelleX. You will learn cloud metadata with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Cloud Metadata","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice cloud metadata with a small exercise of your own."},
      {"type":"keypoints","items":["Cloud Metadata is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-object-storage-concepts",
    title: "Object Storage Concepts",
    description: "S3-compatible backups.",
    level: "intermediate",
    section: "Containers & Cloud",
    order: 44,
    minutes: 13,
    content: [
      {"type":"p","text":"Object Storage Concepts is a core skill in the Linux Administration path on InTelleX. You will learn object storage concepts with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Object Storage Concepts","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice object storage concepts with a small exercise of your own."},
      {"type":"keypoints","items":["Object Storage Concepts is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-project-containerized-app-host",
    title: "Project: Containerized App Host",
    description: "Run nginx reverse proxy to an app.",
    level: "intermediate",
    section: "Containers & Cloud",
    order: 45,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: Containerized App Host is a core skill in the Linux Administration path on InTelleX. You will learn project: containerized app host with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Containerized App Host","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice project: containerized app host with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Containerized App Host is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-updates-cve-hygiene",
    title: "Updates & CVE Hygiene",
    description: "Patch cadence that is real.",
    level: "intermediate",
    section: "Security Hardening",
    order: 46,
    minutes: 13,
    content: [
      {"type":"p","text":"Updates & CVE Hygiene is a core skill in the Linux Administration path on InTelleX. You will learn updates & cve hygiene with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Updates & CVE Hygiene","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice updates & cve hygiene with a small exercise of your own."},
      {"type":"keypoints","items":["Updates & CVE Hygiene is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-fail2ban-intrusion-basics",
    title: "Fail2ban / Intrusion Basics",
    description: "Reduce noisy attacks.",
    level: "intermediate",
    section: "Security Hardening",
    order: 47,
    minutes: 13,
    content: [
      {"type":"p","text":"Fail2ban / Intrusion Basics is a core skill in the Linux Administration path on InTelleX. You will learn fail2ban / intrusion basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Fail2ban / Intrusion Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice fail2ban / intrusion basics with a small exercise of your own."},
      {"type":"keypoints","items":["Fail2ban / Intrusion Basics is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "linux-selinux-apparmor-overview",
    title: "SELinux/AppArmor Overview",
    description: "Mandatory access control ideas.",
    level: "intermediate",
    section: "Security Hardening",
    order: 48,
    minutes: 13,
    content: [
      {"type":"p","text":"SELinux/AppArmor Overview is a core skill in the Linux Administration path on InTelleX. You will learn selinux/apparmor overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind SELinux/AppArmor Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Linux Administration lab folder as you go."},
      {"type":"try","text":"Practice selinux/apparmor overview with a small exercise of your own."},
      {"type":"keypoints","items":["SELinux/AppArmor Overview is an essential Linux Administration skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
