import type { TutorialLesson } from '../types';

export const advancedLessons: TutorialLesson[] = [
  {
    slug: "rails-internationalization",
    title: "Internationalization",
    description: "I18n for multi-language UI.",
    level: "advanced",
    section: "Advanced Rails",
    order: 49,
    minutes: 16,
    content: [
      {"type":"p","text":"Internationalization is a core skill in the Ruby on Rails path on InTelleX. You will learn internationalization with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Internationalization","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice internationalization with a small exercise of your own."},
      {"type":"keypoints","items":["Internationalization is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-capstone-marketplace-mvp",
    title: "Capstone: Marketplace MVP",
    description: "Users, listings, and basic auth.",
    level: "advanced",
    section: "Advanced Rails",
    order: 50,
    minutes: 22,
    content: [
      {"type":"p","text":"Capstone: Marketplace MVP is a core skill in the Ruby on Rails path on InTelleX. You will learn capstone: marketplace mvp with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Marketplace MVP","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice capstone: marketplace mvp with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Marketplace MVP is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-capstone-saas-skeleton",
    title: "Capstone: SaaS Skeleton",
    description: "Teams, billing stub, dashboards.",
    level: "advanced",
    section: "Capstone & Career",
    order: 51,
    minutes: 22,
    content: [
      {"type":"p","text":"Capstone: SaaS Skeleton is a core skill in the Ruby on Rails path on InTelleX. You will learn capstone: saas skeleton with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: SaaS Skeleton","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice capstone: saas skeleton with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: SaaS Skeleton is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-rails-interview-review",
    title: "Rails Interview Review",
    description: "MVC, AR, routing, security.",
    level: "advanced",
    section: "Capstone & Career",
    order: 52,
    minutes: 16,
    content: [
      {"type":"p","text":"Rails Interview Review is a core skill in the Ruby on Rails path on InTelleX. You will learn rails interview review with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Rails Interview Review","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice rails interview review with a small exercise of your own."},
      {"type":"keypoints","items":["Rails Interview Review is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-next-steps",
    title: "Next Steps",
    description: "Hotwire mastery or API+React.",
    level: "advanced",
    section: "Capstone & Career",
    order: 53,
    minutes: 16,
    content: [
      {"type":"p","text":"Next Steps is a core skill in the Ruby on Rails path on InTelleX. You will learn next steps with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Next Steps","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice next steps with a small exercise of your own."},
      {"type":"keypoints","items":["Next Steps is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-final-challenge",
    title: "Final Challenge",
    description: "Ship a CRUD app with auth and tests.",
    level: "advanced",
    section: "Capstone & Career",
    order: 54,
    minutes: 16,
    content: [
      {"type":"p","text":"Final Challenge is a core skill in the Ruby on Rails path on InTelleX. You will learn final challenge with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Final Challenge","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice final challenge with a small exercise of your own."},
      {"type":"keypoints","items":["Final Challenge is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-glossary-drill",
    title: "Glossary Drill",
    description: "MVC, migration, callback, concern, job.",
    level: "advanced",
    section: "Capstone & Career",
    order: 55,
    minutes: 16,
    content: [
      {"type":"p","text":"Glossary Drill is a core skill in the Ruby on Rails path on InTelleX. You will learn glossary drill with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Glossary Drill","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice glossary drill with a small exercise of your own."},
      {"type":"keypoints","items":["Glossary Drill is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-reading-logs",
    title: "Reading Logs",
    description: "Debug request cycles from server logs.",
    level: "advanced",
    section: "Capstone & Career",
    order: 56,
    minutes: 16,
    content: [
      {"type":"p","text":"Reading Logs is a core skill in the Ruby on Rails path on InTelleX. You will learn reading logs with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Reading Logs","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice reading logs with a small exercise of your own."},
      {"type":"keypoints","items":["Reading Logs is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-database-indexes",
    title: "Database Indexes",
    description: "Speed up common queries.",
    level: "advanced",
    section: "Capstone & Career",
    order: 57,
    minutes: 16,
    content: [
      {"type":"p","text":"Database Indexes is a core skill in the Ruby on Rails path on InTelleX. You will learn database indexes with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Database Indexes","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice database indexes with a small exercise of your own."},
      {"type":"keypoints","items":["Database Indexes is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-background-job-pitfalls",
    title: "Background Job Pitfalls",
    description: "Idempotency and retries.",
    level: "advanced",
    section: "Capstone & Career",
    order: 58,
    minutes: 16,
    content: [
      {"type":"p","text":"Background Job Pitfalls is a core skill in the Ruby on Rails path on InTelleX. You will learn background job pitfalls with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Background Job Pitfalls","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice background job pitfalls with a small exercise of your own."},
      {"type":"keypoints","items":["Background Job Pitfalls is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-portfolio-tips",
    title: "Portfolio Tips",
    description: "README, screenshots, seed data.",
    level: "advanced",
    section: "Capstone & Career",
    order: 59,
    minutes: 16,
    content: [
      {"type":"p","text":"Portfolio Tips is a core skill in the Ruby on Rails path on InTelleX. You will learn portfolio tips with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Portfolio Tips","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice portfolio tips with a small exercise of your own."},
      {"type":"keypoints","items":["Portfolio Tips is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-community-gems",
    title: "Community & Gems",
    description: "Evaluate dependencies wisely.",
    level: "advanced",
    section: "Capstone & Career",
    order: 60,
    minutes: 16,
    content: [
      {"type":"p","text":"Community & Gems is a core skill in the Ruby on Rails path on InTelleX. You will learn community & gems with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Community & Gems","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice community & gems with a small exercise of your own."},
      {"type":"keypoints","items":["Community & Gems is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-extra-61",
    title: "Practice Lab 61",
    description: "Hands-on practice lab consolidating earlier rails skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 61,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 61 is a core skill in the Ruby on Rails path on InTelleX. You will learn practice lab 61 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 61","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 61 is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-extra-62",
    title: "Practice Lab 62",
    description: "Hands-on practice lab consolidating earlier rails skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 62,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 62 is a core skill in the Ruby on Rails path on InTelleX. You will learn practice lab 62 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 62","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 62 is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-extra-63",
    title: "Practice Lab 63",
    description: "Hands-on practice lab consolidating earlier rails skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 63,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 63 is a core skill in the Ruby on Rails path on InTelleX. You will learn practice lab 63 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 63","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 63 is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-extra-64",
    title: "Practice Lab 64",
    description: "Hands-on practice lab consolidating earlier rails skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 64,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 64 is a core skill in the Ruby on Rails path on InTelleX. You will learn practice lab 64 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 64","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 64 is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-extra-65",
    title: "Practice Lab 65",
    description: "Hands-on practice lab consolidating earlier rails skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 65,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 65 is a core skill in the Ruby on Rails path on InTelleX. You will learn practice lab 65 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 65","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 65 is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
