import type { TutorialLesson } from '../types';

export const beginnerLessons: TutorialLesson[] = [
  {
    slug: "rails-welcome-to-ruby-on-rails",
    title: "Welcome to Ruby on Rails",
    description: "Convention over configuration for web apps.",
    level: "beginner",
    section: "Getting Started",
    order: 1,
    minutes: 11,
    content: [
      {"type":"p","text":"Welcome to Ruby on Rails is a core skill in the Ruby on Rails path on InTelleX. You will learn welcome to ruby on rails with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Welcome to Ruby on Rails","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice welcome to ruby on rails with a small exercise of your own."},
      {"type":"keypoints","items":["Welcome to Ruby on Rails is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-ruby-quickstart",
    title: "Ruby Quickstart",
    description: "Just enough Ruby syntax for Rails.",
    level: "beginner",
    section: "Getting Started",
    order: 2,
    minutes: 11,
    content: [
      {"type":"p","text":"Ruby Quickstart is a core skill in the Ruby on Rails path on InTelleX. You will learn ruby quickstart with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Ruby Quickstart","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"def greet(name)\n  \"Hello, #{name}\"\nend\nputs greet(\"Ada\")","title":"Example","language":"ruby"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice ruby quickstart with a small exercise of your own."},
      {"type":"keypoints","items":["Ruby Quickstart is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-install-ruby-rails",
    title: "Install Ruby & Rails",
    description: "Tooling for a fresh environment.",
    level: "beginner",
    section: "Getting Started",
    order: 3,
    minutes: 11,
    content: [
      {"type":"p","text":"Install Ruby & Rails is a core skill in the Ruby on Rails path on InTelleX. You will learn install ruby & rails with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Install Ruby & Rails","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice install ruby & rails with a small exercise of your own."},
      {"type":"keypoints","items":["Install Ruby & Rails is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-rails-new",
    title: "rails new",
    description: "Generate an application skeleton.",
    level: "beginner",
    section: "Getting Started",
    order: 4,
    minutes: 11,
    content: [
      {"type":"p","text":"rails new is a core skill in the Ruby on Rails path on InTelleX. You will learn rails new with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind rails new","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"rails new blog --database=postgresql\ncd blog\nbundle install","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice rails new with a small exercise of your own."},
      {"type":"keypoints","items":["rails new is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-mvc-mental-model",
    title: "MVC Mental Model",
    description: "Models, views, controllers, routes.",
    level: "beginner",
    section: "Getting Started",
    order: 5,
    minutes: 11,
    content: [
      {"type":"p","text":"MVC Mental Model is a core skill in the Ruby on Rails path on InTelleX. You will learn mvc mental model with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind MVC Mental Model","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice mvc mental model with a small exercise of your own."},
      {"type":"keypoints","items":["MVC Mental Model is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-routes-basics",
    title: "Routes Basics",
    description: "config/routes.rb essentials.",
    level: "beginner",
    section: "Routing & Controllers",
    order: 6,
    minutes: 11,
    content: [
      {"type":"p","text":"Routes Basics is a core skill in the Ruby on Rails path on InTelleX. You will learn routes basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Routes Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"Rails.application.routes.draw do\n  root \"home#index\"\n  resources :posts\nend","title":"Example","language":"ruby"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice routes basics with a small exercise of your own."},
      {"type":"keypoints","items":["Routes Basics is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-controllers",
    title: "Controllers",
    description: "Actions, params, and redirects.",
    level: "beginner",
    section: "Routing & Controllers",
    order: 7,
    minutes: 11,
    content: [
      {"type":"p","text":"Controllers is a core skill in the Ruby on Rails path on InTelleX. You will learn controllers with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Controllers","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice controllers with a small exercise of your own."},
      {"type":"keypoints","items":["Controllers is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-views-erb",
    title: "Views & ERB",
    description: "Embed Ruby in HTML templates.",
    level: "beginner",
    section: "Routing & Controllers",
    order: 8,
    minutes: 11,
    content: [
      {"type":"p","text":"Views & ERB is a core skill in the Ruby on Rails path on InTelleX. You will learn views & erb with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Views & ERB","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice views & erb with a small exercise of your own."},
      {"type":"keypoints","items":["Views & ERB is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-layouts-partials",
    title: "Layouts & Partials",
    description: "Reuse UI pieces.",
    level: "beginner",
    section: "Routing & Controllers",
    order: 9,
    minutes: 11,
    content: [
      {"type":"p","text":"Layouts & Partials is a core skill in the Ruby on Rails path on InTelleX. You will learn layouts & partials with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Layouts & Partials","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice layouts & partials with a small exercise of your own."},
      {"type":"keypoints","items":["Layouts & Partials is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-strong-parameters",
    title: "Strong Parameters",
    description: "Permit only safe input.",
    level: "beginner",
    section: "Routing & Controllers",
    order: 10,
    minutes: 11,
    content: [
      {"type":"p","text":"Strong Parameters is a core skill in the Ruby on Rails path on InTelleX. You will learn strong parameters with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Strong Parameters","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice strong parameters with a small exercise of your own."},
      {"type":"keypoints","items":["Strong Parameters is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-models-migrations",
    title: "Models & Migrations",
    description: "Create tables the Rails way.",
    level: "beginner",
    section: "Active Record",
    order: 11,
    minutes: 11,
    content: [
      {"type":"p","text":"Models & Migrations is a core skill in the Ruby on Rails path on InTelleX. You will learn models & migrations with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Models & Migrations","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"rails generate model Post title:string body:text\nrails db:migrate","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice models & migrations with a small exercise of your own."},
      {"type":"keypoints","items":["Models & Migrations is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-crud-with-active-record",
    title: "CRUD with Active Record",
    description: "create, read, update, destroy.",
    level: "beginner",
    section: "Active Record",
    order: 12,
    minutes: 11,
    content: [
      {"type":"p","text":"CRUD with Active Record is a core skill in the Ruby on Rails path on InTelleX. You will learn crud with active record with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind CRUD with Active Record","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice crud with active record with a small exercise of your own."},
      {"type":"keypoints","items":["CRUD with Active Record is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-validations",
    title: "Validations",
    description: "Keep bad data out.",
    level: "beginner",
    section: "Active Record",
    order: 13,
    minutes: 11,
    content: [
      {"type":"p","text":"Validations is a core skill in the Ruby on Rails path on InTelleX. You will learn validations with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Validations","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice validations with a small exercise of your own."},
      {"type":"keypoints","items":["Validations is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-associations",
    title: "Associations",
    description: "has_many, belongs_to, and friends.",
    level: "beginner",
    section: "Active Record",
    order: 14,
    minutes: 11,
    content: [
      {"type":"p","text":"Associations is a core skill in the Ruby on Rails path on InTelleX. You will learn associations with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Associations","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice associations with a small exercise of your own."},
      {"type":"keypoints","items":["Associations is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-query-interface",
    title: "Query Interface",
    description: "where, order, includes.",
    level: "beginner",
    section: "Active Record",
    order: 15,
    minutes: 11,
    content: [
      {"type":"p","text":"Query Interface is a core skill in the Ruby on Rails path on InTelleX. You will learn query interface with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Query Interface","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice query interface with a small exercise of your own."},
      {"type":"keypoints","items":["Query Interface is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-form-helpers",
    title: "Form Helpers",
    description: "form_with and f.text_field.",
    level: "beginner",
    section: "Forms & UX",
    order: 16,
    minutes: 11,
    content: [
      {"type":"p","text":"Form Helpers is a core skill in the Ruby on Rails path on InTelleX. You will learn form helpers with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Form Helpers","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice form helpers with a small exercise of your own."},
      {"type":"keypoints","items":["Form Helpers is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-flash-messages",
    title: "Flash Messages",
    description: "notice and alert patterns.",
    level: "beginner",
    section: "Forms & UX",
    order: 17,
    minutes: 11,
    content: [
      {"type":"p","text":"Flash Messages is a core skill in the Ruby on Rails path on InTelleX. You will learn flash messages with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Flash Messages","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice flash messages with a small exercise of your own."},
      {"type":"keypoints","items":["Flash Messages is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-asset-pipeline-importmaps",
    title: "Asset Pipeline / Importmaps",
    description: "Modern Rails front-end defaults.",
    level: "beginner",
    section: "Forms & UX",
    order: 18,
    minutes: 11,
    content: [
      {"type":"p","text":"Asset Pipeline / Importmaps is a core skill in the Ruby on Rails path on InTelleX. You will learn asset pipeline / importmaps with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Asset Pipeline / Importmaps","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice asset pipeline / importmaps with a small exercise of your own."},
      {"type":"keypoints","items":["Asset Pipeline / Importmaps is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-hotwire-turbo-preview",
    title: "Hotwire Turbo Preview",
    description: "Faster navigation with less custom JS.",
    level: "beginner",
    section: "Forms & UX",
    order: 19,
    minutes: 11,
    content: [
      {"type":"p","text":"Hotwire Turbo Preview is a core skill in the Ruby on Rails path on InTelleX. You will learn hotwire turbo preview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Hotwire Turbo Preview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice hotwire turbo preview with a small exercise of your own."},
      {"type":"keypoints","items":["Hotwire Turbo Preview is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-project-blog-crud",
    title: "Project: Blog CRUD",
    description: "Posts with validation and index/show.",
    level: "beginner",
    section: "Forms & UX",
    order: 20,
    minutes: 20,
    content: [
      {"type":"p","text":"Project: Blog CRUD is a core skill in the Ruby on Rails path on InTelleX. You will learn project: blog crud with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Blog CRUD","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice project: blog crud with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Blog CRUD is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-sessions-primer",
    title: "Sessions Primer",
    description: "Cookies and login state.",
    level: "beginner",
    section: "Authentication & Authorization",
    order: 21,
    minutes: 11,
    content: [
      {"type":"p","text":"Sessions Primer is a core skill in the Ruby on Rails path on InTelleX. You will learn sessions primer with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Sessions Primer","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice sessions primer with a small exercise of your own."},
      {"type":"keypoints","items":["Sessions Primer is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-has-secure-password",
    title: "has_secure_password",
    description: "Password hashing built-in.",
    level: "beginner",
    section: "Authentication & Authorization",
    order: 22,
    minutes: 11,
    content: [
      {"type":"p","text":"has_secure_password is a core skill in the Ruby on Rails path on InTelleX. You will learn has_secure_password with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind has_secure_password","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice has_secure_password with a small exercise of your own."},
      {"type":"keypoints","items":["has_secure_password is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-authentication-from-scratch",
    title: "Authentication From Scratch",
    description: "Sign up / login / logout flow.",
    level: "beginner",
    section: "Authentication & Authorization",
    order: 23,
    minutes: 11,
    content: [
      {"type":"p","text":"Authentication From Scratch is a core skill in the Ruby on Rails path on InTelleX. You will learn authentication from scratch with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Authentication From Scratch","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice authentication from scratch with a small exercise of your own."},
      {"type":"keypoints","items":["Authentication From Scratch is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-authorization-patterns",
    title: "Authorization Patterns",
    description: "Pundit/CanCanCan concepts.",
    level: "beginner",
    section: "Authentication & Authorization",
    order: 24,
    minutes: 11,
    content: [
      {"type":"p","text":"Authorization Patterns is a core skill in the Ruby on Rails path on InTelleX. You will learn authorization patterns with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Authorization Patterns","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice authorization patterns with a small exercise of your own."},
      {"type":"keypoints","items":["Authorization Patterns is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-project-auth-blog",
    title: "Project: Auth Blog",
    description: "Only authors edit their posts.",
    level: "beginner",
    section: "Authentication & Authorization",
    order: 25,
    minutes: 20,
    content: [
      {"type":"p","text":"Project: Auth Blog is a core skill in the Ruby on Rails path on InTelleX. You will learn project: auth blog with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Auth Blog","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice project: auth blog with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Auth Blog is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
