import type { TutorialLesson } from '../types';

export const intermediateLessons: TutorialLesson[] = [
  {
    slug: "rails-nested-resources",
    title: "Nested Resources",
    description: "Comments under posts.",
    level: "intermediate",
    section: "Intermediate Rails",
    order: 26,
    minutes: 13,
    content: [
      {"type":"p","text":"Nested Resources is a core skill in the Ruby on Rails path on InTelleX. You will learn nested resources with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Nested Resources","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice nested resources with a small exercise of your own."},
      {"type":"keypoints","items":["Nested Resources is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-concerns",
    title: "Concerns",
    description: "Share model/controller code.",
    level: "intermediate",
    section: "Intermediate Rails",
    order: 27,
    minutes: 13,
    content: [
      {"type":"p","text":"Concerns is a core skill in the Ruby on Rails path on InTelleX. You will learn concerns with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Concerns","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice concerns with a small exercise of your own."},
      {"type":"keypoints","items":["Concerns is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-background-jobs",
    title: "Background Jobs",
    description: "Active Job mental model.",
    level: "intermediate",
    section: "Intermediate Rails",
    order: 28,
    minutes: 13,
    content: [
      {"type":"p","text":"Background Jobs is a core skill in the Ruby on Rails path on InTelleX. You will learn background jobs with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Background Jobs","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice background jobs with a small exercise of your own."},
      {"type":"keypoints","items":["Background Jobs is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-action-mailer",
    title: "Action Mailer",
    description: "Send email from the app.",
    level: "intermediate",
    section: "Intermediate Rails",
    order: 29,
    minutes: 13,
    content: [
      {"type":"p","text":"Action Mailer is a core skill in the Ruby on Rails path on InTelleX. You will learn action mailer with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Action Mailer","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice action mailer with a small exercise of your own."},
      {"type":"keypoints","items":["Action Mailer is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-file-uploads",
    title: "File Uploads",
    description: "Active Storage overview.",
    level: "intermediate",
    section: "Intermediate Rails",
    order: 30,
    minutes: 13,
    content: [
      {"type":"p","text":"File Uploads is a core skill in the Ruby on Rails path on InTelleX. You will learn file uploads with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind File Uploads","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice file uploads with a small exercise of your own."},
      {"type":"keypoints","items":["File Uploads is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-api-only-mode",
    title: "API-only Mode",
    description: "Rails as a JSON backend.",
    level: "intermediate",
    section: "APIs",
    order: 31,
    minutes: 13,
    content: [
      {"type":"p","text":"API-only Mode is a core skill in the Ruby on Rails path on InTelleX. You will learn api-only mode with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind API-only Mode","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice api-only mode with a small exercise of your own."},
      {"type":"keypoints","items":["API-only Mode is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-serialization",
    title: "Serialization",
    description: "jbuilder / Alba patterns.",
    level: "intermediate",
    section: "APIs",
    order: 32,
    minutes: 13,
    content: [
      {"type":"p","text":"Serialization is a core skill in the Ruby on Rails path on InTelleX. You will learn serialization with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Serialization","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice serialization with a small exercise of your own."},
      {"type":"keypoints","items":["Serialization is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-api-authentication",
    title: "API Authentication",
    description: "Tokens and headers overview.",
    level: "intermediate",
    section: "APIs",
    order: 33,
    minutes: 13,
    content: [
      {"type":"p","text":"API Authentication is a core skill in the Ruby on Rails path on InTelleX. You will learn api authentication with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind API Authentication","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice api authentication with a small exercise of your own."},
      {"type":"keypoints","items":["API Authentication is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-versioning-apis",
    title: "Versioning APIs",
    description: "Keep clients stable.",
    level: "intermediate",
    section: "APIs",
    order: 34,
    minutes: 13,
    content: [
      {"type":"p","text":"Versioning APIs is a core skill in the Ruby on Rails path on InTelleX. You will learn versioning apis with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Versioning APIs","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice versioning apis with a small exercise of your own."},
      {"type":"keypoints","items":["Versioning APIs is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-project-json-posts-api",
    title: "Project: JSON Posts API",
    description: "Index/create endpoints with tests.",
    level: "intermediate",
    section: "APIs",
    order: 35,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: JSON Posts API is a core skill in the Ruby on Rails path on InTelleX. You will learn project: json posts api with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: JSON Posts API","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice project: json posts api with a small exercise of your own."},
      {"type":"keypoints","items":["Project: JSON Posts API is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-minitest-or-rspec",
    title: "Minitest or RSpec",
    description: "Pick a stack and write model tests.",
    level: "intermediate",
    section: "Testing",
    order: 36,
    minutes: 13,
    content: [
      {"type":"p","text":"Minitest or RSpec is a core skill in the Ruby on Rails path on InTelleX. You will learn minitest or rspec with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Minitest or RSpec","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice minitest or rspec with a small exercise of your own."},
      {"type":"keypoints","items":["Minitest or RSpec is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-request-specs",
    title: "Request Specs",
    description: "Exercise HTTP endpoints.",
    level: "intermediate",
    section: "Testing",
    order: 37,
    minutes: 13,
    content: [
      {"type":"p","text":"Request Specs is a core skill in the Ruby on Rails path on InTelleX. You will learn request specs with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Request Specs","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice request specs with a small exercise of your own."},
      {"type":"keypoints","items":["Request Specs is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-fixtures-factories",
    title: "Fixtures & Factories",
    description: "Reusable test data.",
    level: "intermediate",
    section: "Testing",
    order: 38,
    minutes: 13,
    content: [
      {"type":"p","text":"Fixtures & Factories is a core skill in the Ruby on Rails path on InTelleX. You will learn fixtures & factories with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Fixtures & Factories","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice fixtures & factories with a small exercise of your own."},
      {"type":"keypoints","items":["Fixtures & Factories is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-system-tests",
    title: "System Tests",
    description: "Browser-level coverage overview.",
    level: "intermediate",
    section: "Testing",
    order: 39,
    minutes: 13,
    content: [
      {"type":"p","text":"System Tests is a core skill in the Ruby on Rails path on InTelleX. You will learn system tests with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind System Tests","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice system tests with a small exercise of your own."},
      {"type":"keypoints","items":["System Tests is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-project-test-the-blog",
    title: "Project: Test the Blog",
    description: "Cover validations and happy paths.",
    level: "intermediate",
    section: "Testing",
    order: 40,
    minutes: 16,
    content: [
      {"type":"p","text":"Project: Test the Blog is a core skill in the Ruby on Rails path on InTelleX. You will learn project: test the blog with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Test the Blog","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice project: test the blog with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Test the Blog is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-environments",
    title: "Environments",
    description: "development, test, production.",
    level: "intermediate",
    section: "Production",
    order: 41,
    minutes: 13,
    content: [
      {"type":"p","text":"Environments is a core skill in the Ruby on Rails path on InTelleX. You will learn environments with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Environments","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice environments with a small exercise of your own."},
      {"type":"keypoints","items":["Environments is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-credentials-env",
    title: "Credentials & ENV",
    description: "Secrets management.",
    level: "intermediate",
    section: "Production",
    order: 42,
    minutes: 13,
    content: [
      {"type":"p","text":"Credentials & ENV is a core skill in the Ruby on Rails path on InTelleX. You will learn credentials & env with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Credentials & ENV","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice credentials & env with a small exercise of your own."},
      {"type":"keypoints","items":["Credentials & ENV is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-deploy-overview",
    title: "Deploy Overview",
    description: "Render/Fly/Heroku-style deploys.",
    level: "intermediate",
    section: "Production",
    order: 43,
    minutes: 13,
    content: [
      {"type":"p","text":"Deploy Overview is a core skill in the Ruby on Rails path on InTelleX. You will learn deploy overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Deploy Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice deploy overview with a small exercise of your own."},
      {"type":"keypoints","items":["Deploy Overview is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-performance-basics",
    title: "Performance Basics",
    description: "N+1 queries and caching.",
    level: "intermediate",
    section: "Production",
    order: 44,
    minutes: 13,
    content: [
      {"type":"p","text":"Performance Basics is a core skill in the Ruby on Rails path on InTelleX. You will learn performance basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Performance Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice performance basics with a small exercise of your own."},
      {"type":"keypoints","items":["Performance Basics is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-security-checklist",
    title: "Security Checklist",
    description: "CSRF, XSS, mass assignment.",
    level: "intermediate",
    section: "Production",
    order: 45,
    minutes: 13,
    content: [
      {"type":"p","text":"Security Checklist is a core skill in the Ruby on Rails path on InTelleX. You will learn security checklist with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Security Checklist","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice security checklist with a small exercise of your own."},
      {"type":"keypoints","items":["Security Checklist is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-engines-overview",
    title: "Engines Overview",
    description: "Mountable mini-apps.",
    level: "intermediate",
    section: "Advanced Rails",
    order: 46,
    minutes: 13,
    content: [
      {"type":"p","text":"Engines Overview is a core skill in the Ruby on Rails path on InTelleX. You will learn engines overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Engines Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice engines overview with a small exercise of your own."},
      {"type":"keypoints","items":["Engines Overview is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-custom-middleware",
    title: "Custom Middleware",
    description: "Rack awareness.",
    level: "intermediate",
    section: "Advanced Rails",
    order: 47,
    minutes: 13,
    content: [
      {"type":"p","text":"Custom Middleware is a core skill in the Ruby on Rails path on InTelleX. You will learn custom middleware with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Custom Middleware","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice custom middleware with a small exercise of your own."},
      {"type":"keypoints","items":["Custom Middleware is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "rails-multi-db-glimpse",
    title: "Multi-db Glimpse",
    description: "Primary/replica concepts.",
    level: "intermediate",
    section: "Advanced Rails",
    order: 48,
    minutes: 13,
    content: [
      {"type":"p","text":"Multi-db Glimpse is a core skill in the Ruby on Rails path on InTelleX. You will learn multi-db glimpse with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Multi-db Glimpse","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Ruby on Rails lab folder as you go."},
      {"type":"try","text":"Practice multi-db glimpse with a small exercise of your own."},
      {"type":"keypoints","items":["Multi-db Glimpse is an essential Ruby on Rails skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
