import type { TutorialLesson } from '../types';

export const advancedLessons: TutorialLesson[] = [
  {
    slug: "virtual-memory-and-page-tables",
    title: "Virtual Memory & Page Tables",
    description: "Separate virtual from physical addresses and walk the role of page tables in translation.",
    level: "advanced",
    section: "Virtual Memory & I/O",
    order: 49,
    minutes: 14,
    content: [
      {"type":"p","text":"Virtual memory gives each process a clean address space, enables isolation, and lets disks back infrequently used pages."},
      {"type":"h2","text":"Core ideas"},
      {"type":"ul","items":["Virtual page number (VPN) + page offset","Page table maps VPN → physical frame (or fault)","Page faults invoke OS to load from disk","Protection bits: read/write/exec/user"]},
      {"type":"code","code":"virtual addr: [ VPN | offset ]\nphys addr:    [ PFN | offset ]  # offset unchanged","title":"Translation structure","language":"text"},
      {"type":"try","text":"For 4 KiB pages, how many offset bits? If VPN has 20 bits, how large is the virtual space?"},
      {"type":"keypoints","items":["VM translates VPN to physical frame.","Page tables store the mapping + permissions.","Faults are expensive - locality still rules."]},
    ],
  },
  {
    slug: "tlb-address-translation",
    title: "TLBs & Fast Address Translation",
    description: "Use Translation Lookaside Buffers to avoid walking page tables on every access.",
    level: "advanced",
    section: "Virtual Memory & I/O",
    order: 50,
    minutes: 13,
    content: [
      {"type":"p","text":"A TLB caches recent VPN→PFN translations. Hit: translate in ~1 cycle. Miss: walk tables (hardware or software), then refill."},
      {"type":"table","headers":["Event","Cost intuition"],"rows":[["TLB hit","Cheap - almost like no VM"],["TLB miss + PT hit in cache","Moderate"],["Page fault to disk","Enormous (ms)"]]},
      {"type":"tip","text":"AMAT-style reasoning extends to TLB miss rates too."},
      {"type":"try","text":"Explain why large pages (e.g., 2 MiB) can raise TLB reach."},
      {"type":"keypoints","items":["TLBs make virtual memory practical.","Misses invoke page-table walks.","Page size affects TLB coverage."]},
    ],
  },
  {
    slug: "memory-mapped-io",
    title: "Memory-Mapped I/O",
    description: "Control devices by reading/writing reserved addresses - unify CPU access paths.",
    level: "advanced",
    section: "Virtual Memory & I/O",
    order: 51,
    minutes: 11,
    content: [
      {"type":"p","text":"With memory-mapped I/O, device registers appear as addresses. Loads/stores become device control and status queries."},
      {"type":"code","code":"STORE #CMD_START → DEVICE_CMD_REG\nLOAD  DEVICE_STATUS   # poll ready bit\nLOAD  DEVICE_DATA","title":"MMIO sketch","language":"text"},
      {"type":"note","text":"Alternative: separate I/O instructions (port-mapped I/O). Many teaching systems emphasize MMIO."},
      {"type":"try","text":"List three fields you would place in a toy UART’s MMIO register map."},
      {"type":"keypoints","items":["MMIO reuses load/store for device control.","Address decode steers CPU to devices vs memory.","Ordering and volatility matter for device regs."]},
    ],
  },
  {
    slug: "interrupts-vs-polling",
    title: "Interrupts vs Polling",
    description: "Compare busy-wait device service with interrupt-driven I/O and when each is appropriate.",
    level: "advanced",
    section: "Virtual Memory & I/O",
    order: 52,
    minutes: 12,
    content: [
      {"type":"p","text":"Polling repeatedly asks \"ready yet?\" Interrupts let devices signal the CPU when service is needed."},
      {"type":"table","headers":["Approach","CPU overhead","Latency predictability"],"rows":[["Polling","High if frequent","Can be very responsive"],["Interrupts","Low when idle","Handler + nesting complexity"]]},
      {"type":"tip","text":"Real systems mix both: poll in tight device drivers, interrupt for sparse events."},
      {"type":"try","text":"Describe a sensor sampling case where polling wins, and a keyboard case where interrupts win."},
      {"type":"keypoints","items":["Polling wastes cycles waiting.","Interrupts free the CPU until events arrive.","Handler design is part of system architecture."]},
    ],
  },
  {
    slug: "direct-memory-access",
    title: "Direct Memory Access (DMA)",
    description: "Let devices transfer bulk data to memory without per-word CPU babysitting.",
    level: "advanced",
    section: "Virtual Memory & I/O",
    order: 53,
    minutes: 13,
    content: [
      {"type":"p","text":"DMA engines move blocks between devices and memory. The CPU sets up a transfer descriptor, then continues useful work until an interrupt signals completion."},
      {"type":"h2","text":"Setup flow"},
      {"type":"ol","items":["CPU programs source, destination, size, direction","DMA requests the bus / memory","Transfer proceeds (possibly stealing cycles)","DMA interrupts CPU on completion / error"]},
      {"type":"warning","text":"Cache coherence with DMA is a real hazard: memory may change under a cache. Systems flush/invalidate or use coherent interconnects."},
      {"type":"try","text":"Write a sequence diagram: CPU, DMA, device, memory for a 4 KiB disk read."},
      {"type":"keypoints","items":["DMA offloads bulk transfer from the CPU.","Completion is usually interrupt-driven.","Coherence and permissions must be designed carefully."]},
    ],
  },
  {
    slug: "dma-controller-simulator",
    title: "Project: DMA Controller Simulator",
    description: "Build an automated transfer module that models DMA setup, bus grant, and completion interrupt.",
    level: "advanced",
    section: "Virtual Memory & I/O",
    order: 54,
    minutes: 18,
    content: [
      {"type":"p","text":"Week 9 project: The DMA Controller Simulator - show that bulk transfers need not poll every word in software."},
      {"type":"h2","text":"Simulator entities"},
      {"type":"ul","items":["CPU (program & interrupt)","DMA engine","Device buffer","Memory array","Simple bus arbiter"]},
      {"type":"code","code":"dma.program(src=dev, dst=mem+0x1000, n=1024)\ndma.start()\n# CPU continues other work\nonInterrupt:\n  assert memSliceEquals(devBuffer)","title":"Acceptance test sketch","language":"text"},
      {"type":"try","text":"Define states: Idle, WaitBus, Transferring, Complete. List transitions."},
      {"type":"keypoints","items":["Model DMA as a state machine sharing the bus.","Prove correctness with memory compares.","Discuss CPU cycles saved vs polling."]},
    ],
  },
  {
    slug: "amdahls-law",
    title: "Amdahl's Law",
    description: "Quantify the speedup ceiling when only part of a workload can be parallelized.",
    level: "advanced",
    section: "Multicore & Parallelism",
    order: 55,
    minutes: 12,
    content: [
      {"type":"p","text":"Amdahl's Law is the cold water for multicore dreams: serial fractions dominate the limit."},
      {"type":"code","code":"Speedup ≤ 1 / ( (1 - P) + P / N )\n\nP = parallelizable fraction\nN = number of processors","title":"Amdahl","language":"text"},
      {"type":"h2","text":"Example"},
      {"type":"p","text":"If 10% of runtime is serial, even infinite cores cannot beat 10× speedup."},
      {"type":"try","text":"Compute max speedup for P=0.8 with N=4 and N=64."},
      {"type":"keypoints","items":["Serial bottlenecks cap parallel speedup.","Optimize the non-parallelizable part too.","Use Amdahl before buying \"more cores\" as a strategy."]},
    ],
  },
  {
    slug: "flynns-taxonomy",
    title: "Flynn's Taxonomy",
    description: "Classify SISD, SIMD, MISD, and MIMD - and map them to CPUs, GPUs, and clusters.",
    level: "advanced",
    section: "Multicore & Parallelism",
    order: 56,
    minutes: 12,
    content: [
      {"type":"p","text":"Flynn classified computers by instruction and data streams."},
      {"type":"table","headers":["Class","Instruction streams","Data streams","Examples"],"rows":[["SISD","1","1","Classic uniprocessor"],["SIMD","1","Many","Vector units, GPUs (wide)"],["MISD","Many","1","Rare / specialized"],["MIMD","Many","Many","Multicore CPUs, clusters"]]},
      {"type":"try","text":"Label a 4-core phone CPU and a GPU warp/wavefront using Flynn classes."},
      {"type":"keypoints","items":["SISD/SIMD/MISD/MIMD organize parallel hardware.","Modern chips mix classes (SIMD units inside MIMD cores).","Pick algorithms that match the machine class."]},
    ],
  },
  {
    slug: "simd-mimd-multicore",
    title: "SIMD, MIMD & Multicore Processors",
    description: "Differentiate data-level parallelism from thread-level parallelism in practical terms.",
    level: "advanced",
    section: "Multicore & Parallelism",
    order: 57,
    minutes: 13,
    content: [
      {"type":"p","text":"SIMD applies one operation to many data lanes. MIMD runs independent instruction streams - multicore CPUs are MIMD with shared memory."},
      {"type":"ul","items":["DLP - data-level parallelism (SIMD/vectors)","TLP - thread-level parallelism (multicore/multi-thread)","ILP - instruction-level parallelism (pipelines/superscalar)"]},
      {"type":"tip","text":"Great software uses all three levels carefully - compilers for ILP/SIMD, OS/runtime for threads."},
      {"type":"try","text":"Give one workload best for SIMD and one best for MIMD threads."},
      {"type":"keypoints","items":["SIMD = same op, many data.","MIMD = independent workers.","Multicore sharing raises coherence questions next."]},
    ],
  },
  {
    slug: "cache-coherence-msi-mesi",
    title: "Cache Coherence: MSI & MESI",
    description: "Track shared line states across cores so every reader sees a consistent memory story.",
    level: "advanced",
    section: "Multicore & Parallelism",
    order: 58,
    minutes: 15,
    content: [
      {"type":"p","text":"Private caches multiply the coherence problem: which core owns the latest value of a line?"},
      {"type":"h2","text":"MSI states"},
      {"type":"ul","items":["M - Modified (dirty, unique)","S - Shared (clean, may be multi-cached)","I - Invalid"]},
      {"type":"h2","text":"MESI adds Exclusive"},
      {"type":"p","text":"E - Exclusive clean unique. Allows silent upgrade to Modified without a bus upgrade in many protocols - an optimization over MSI."},
      {"type":"warning","text":"Coherence ≠ synchronization. Atomics/locks still needed for higher-level races."},
      {"type":"try","text":"Walk a line from I → E → M → S across two cores with a read/write storyboard."},
      {"type":"keypoints","items":["MSI/MESI track ownership and sharing of cache lines.","Exclusive state reduces upgrade traffic.","Coherence protocols are the multicore memory backbone."]},
    ],
  },
  {
    slug: "coherence-arbiter-project",
    title: "Project: The Coherence Arbiter",
    description: "Simulate a multi-core environment tracking shared line state changes across processing cores.",
    level: "advanced",
    section: "Multicore & Parallelism",
    order: 59,
    minutes: 18,
    content: [
      {"type":"p","text":"Week 10 project: The Coherence Arbiter. Model 2-4 cores, a shared bus or directory stub, and MESI transitions for one cache line."},
      {"type":"h2","text":"Minimum events"},
      {"type":"ul","items":["PrRd","PrWr","BusRd","BusRdX / BusUpgr","Flush"]},
      {"type":"code","code":"on(event, core):\n  state[core] = transition(state[core], event)\n  for other in cores:\n    state[other] = snoop(state[other], event)\n  log(cycle, states)","title":"Arbiter loop","language":"text"},
      {"type":"try","text":"Simulate: Core0 read, Core1 read, Core0 write. Show states after each step."},
      {"type":"keypoints","items":["Coherence sims make protocol transitions concrete.","Logging every bus event is part of the report.","Extend later with more lines and false sharing demos."]},
    ],
  },
  {
    slug: "hardware-software-co-design",
    title: "Hardware-Software Co-Design",
    description: "Think jointly about ISA, compiler scheduling, and microarchitecture when chasing performance per watt.",
    level: "advanced",
    section: "Capstone & Exam Prep",
    order: 60,
    minutes: 12,
    content: [
      {"type":"p","text":"CSE 203 ends where engineering begins: hardware and software must be designed together. Compilers schedule for pipelines; ISAs expose useful ops; microarchitects implement efficient paths."},
      {"type":"ul","items":["Software: algorithms, data layout, instruction scheduling","ISA: dense vs simple ops, vector extensions","Microarchitecture: caches, predictors, cores"]},
      {"type":"try","text":"Pick a slow loop you know. Propose one software change and one hardware feature that would each help."},
      {"type":"keypoints","items":["Performance is a co-design surface.","Blaming only software or only hardware is incomplete.","Document trade-offs like an engineer, not a tourist."]},
    ],
  },
  {
    slug: "time-space-power-tradeoffs",
    title: "Time-Space-Power Trade-offs",
    description: "Practice SIU engineering discipline: every design choice balances latency, area, and energy.",
    level: "advanced",
    section: "Capstone & Exam Prep",
    order: 61,
    minutes: 12,
    content: [
      {"type":"p","text":"Architectural professionalism means justifying trade-offs. A CLA is faster than ripple-carry but costs gates and wire. A write-back cache saves bandwidth but needs dirty-bit logic."},
      {"type":"table","headers":["Knob","Pushing it up often…","Costs"],"rows":[["Speed","Raises frequency / lowers CPI","Power, area, complexity"],["Area","More ALUs, bigger caches","Chip cost, leakage"],["Energy","Simpler paths, dark silicon strategies","May reduce peak performance"]]},
      {"type":"try","text":"For your Custom ALU project, write a 5-line trade-off paragraph: what you optimized and what you sacrificed."},
      {"type":"keypoints","items":["No free lunch across time, space, and power.","Reports must quantify or at least qualitatively justify trade-offs.","This mindset is part of the CSE 203 CLO on engineering discipline."]},
    ],
  },
  {
    slug: "grand-challenges-multicore",
    title: "Grand Challenges in Multicore Scaling",
    description: "Tackle memory bus contention, synchronization overhead, and diminishing returns at scale.",
    level: "advanced",
    section: "Capstone & Exam Prep",
    order: 62,
    minutes: 13,
    content: [
      {"type":"p","text":"More cores help only when work, memory bandwidth, and synchronization allow it. Bus contention and lock convoys can erase theoretical speedups."},
      {"type":"h2","text":"Challenge prompts"},
      {"type":"ol","items":["A workload with P=0.95 hits a memory bandwidth wall at N=16 - why?","False sharing turns a parallel array update pathological - explain","Where does Amdahl still bite a microservice fan-out on one chip?"]},
      {"type":"try","text":"Write a short “architecture memo” proposing one fix for false sharing (padding, privatization, …)."},
      {"type":"keypoints","items":["Scaling limits are often memory and sync, not ALU count.","False sharing is a coherence performance bug.","Measure before celebrating core counts."]},
    ],
  },
  {
    slug: "final-exam-assembly-review",
    title: "Final Review: Assembly & Datapath",
    description: "Comprehensive drill on ISA encodings, hand translation, and single-cycle control before the final.",
    level: "advanced",
    section: "Capstone & Exam Prep",
    order: 63,
    minutes: 15,
    content: [
      {"type":"p","text":"Final exams weave assembly abstractions with hardware metrics. Rehearse under time pressure."},
      {"type":"ul","items":["Disassemble one R and one I instruction from fields","Translate a nested if/loop to assembly","Fill control signals for lw/sw/beq/add","Trace 10 instructions including a store and branch"]},
      {"type":"try","text":"Create a 45-minute mock exam from these bullets and take it cold."},
      {"type":"keypoints","items":["Finals reward fluent tracing and control tables.","Connect assembly choices to datapath events.","No emulator - paper discipline wins."]},
    ],
  },
  {
    slug: "final-exam-pipeline-cache-review",
    title: "Final Review: Pipelines, Hazards & Caches",
    description: "Drill hazard charts, forwarding, AMAT, and associativity questions for the comprehensive final.",
    level: "advanced",
    section: "Capstone & Exam Prep",
    order: 64,
    minutes: 16,
    content: [
      {"type":"p","text":"Pipeline + memory questions dominate advanced finals. Mix charts with numeric AMAT."},
      {"type":"h2","text":"Must-hit skills"},
      {"type":"ol","items":["Draw a pipeline chart with one load-use stall and forwarding","Identify RAW pairs and name forward paths","Compute AMAT for 1- and 2-level caches","Simulate 8 accesses on a small set-associative cache","Explain MESI transition on a remote write"]},
      {"type":"try","text":"Score yourself /10 on the must-hit list. Restudy any item below 8."},
      {"type":"keypoints","items":["Charts + AMAT + coherence are high-value final topics.","Show work: bitfields, indexes, tags.","Explain why, not only what."]},
    ],
  },
  {
    slug: "architecture-capstone-synthesis",
    title: "Capstone: Architecture Synthesis",
    description: "Integrate ISA, datapath, pipeline, cache, and I/O into one coherent system narrative and portfolio packet.",
    level: "advanced",
    section: "Capstone & Exam Prep",
    order: 65,
    minutes: 20,
    content: [
      {"type":"p","text":"Close the course by synthesizing every major artifact into one architectural story: a mini processor + memory system you can explain end-to-end."},
      {"type":"h2","text":"Portfolio packet"},
      {"type":"ol","items":["ISA subset + disassembler notes (Native Translator)","ALU diagram + test vectors (Custom ALU)","Single-cycle blueprint + control table","Pipeline stage monitor frames + hazard detector sample","Cache configurator results + AMAT commentary","DMA or coherence sim highlight","Trade-off essay (time/space/power) - 1 page"]},
      {"type":"tip","text":"If you can teach your design to a peer without slides, you own it."},
      {"type":"note","text":"Academic integrity reminder: every mux path, register assignment, and pipeline stage you claim must be understood and justifiable. Copying assembly or circuits without comprehension fails the engineering standard."},
      {"type":"try","text":"Record a 5-minute voice memo walking from an instruction fetch to a cache hit on your design. Listen for gaps."},
      {"type":"keypoints","items":["Synthesis proves the CLOs, not isolated facts.","Your projects become the Hardware DNA portfolio.","You now reason about how hardware executes - not only how code runs."]},
    ],
  },
];
