import type { TutorialLesson } from '../types';

export const beginnerLessons: TutorialLesson[] = [
  {
    slug: "welcome-to-computer-architecture",
    title: "Welcome to Computer Architecture",
    description: "Meet CSE 203 — why hardware DNA matters for every software engineer, and how this InTelleX path is organized.",
    level: "beginner",
    section: "Course Orientation",
    order: 1,
    minutes: 12,
    content: [
      {"type":"p","text":"Computer Architecture and Organization (CSE 203) teaches the structural and logical frameworks that turn high-level code into electronic execution. At InTelleX, this path follows a university-grade curriculum: Instruction Set Architecture, ALU design, single-cycle and pipelined datapaths, hazards, caches, virtual memory, I/O, and multicore systems."},
      {"type":"p","text":"The goal is not memorizing jargon. You will learn to think in clock cycles, instruction-level parallelism, and memory locality — so you can explain why a program is slow, and what hardware choices set the performance ceiling."},
      {"type":"h2","text":"What you will master"},
      {"type":"ul","items":["Translate high-level constructs into RISC-V / MIPS-style assembly","Design and reason about ALUs, registers, and datapaths","Model a 5-stage pipeline and resolve hazards","Analyze cache mapping and Average Memory Access Time (AMAT)","Explain DMA, interrupts, virtual memory, and multicore coherence"]},
      {"type":"h2","text":"How this tutorial is structured"},
      {"type":"table","headers":["Level","Focus","Curriculum weeks"],"rows":[["Beginner","Abstraction, ISA, ALU, single-cycle datapath","Weeks 1–4"],["Intermediate","Pipelines, hazards, caches","Weeks 5–8"],["Advanced","VM, I/O, DMA, multicore, synthesis","Weeks 9–10"]]},
      {"type":"note","text":"Required textbook mindset: Computer Organization and Design (Patterson & Hennessy), RISC-V or MIPS edition. Tools: Venus (RISC-V) or MARS (MIPS), plus Logisim-Evolution for digital logic."},
      {"type":"tip","text":"Professionalism here means architectural optimization. A design that wastes clock cycles or ignores hazards fails the engineering standard — even if it \"works.\""},
      {"type":"try","text":"Write one sentence: \"I want to understand how my code becomes electrical signals on silicon.\" Keep it as your north star for this course."},
      {"type":"keypoints","items":["Architecture bridges abstract software and physical hardware.","This path mirrors CSE 203 across ISA, datapath, pipeline, memory, and multicore.","You will reason in cycles, hazards, and locality — not only in source code.","Tools: Venus/MARS for assembly, Logisim for digital logic."]},
    ],
  },
  {
    slug: "course-map-and-tools",
    title: "Course Map, Labs & Tools",
    description: "Set up your mental map of CSE 203 activities: Assembly Duel, Bottleneck Audit, Hardware Visualization, and Clock-Cycle Stress Test.",
    level: "beginner",
    section: "Course Orientation",
    order: 2,
    minutes: 11,
    content: [
      {"type":"p","text":"CSE 203 uses active learning. Every week you practice tracing, measuring, and redesigning — not only reading theory."},
      {"type":"h2","text":"Signature activities"},
      {"type":"ul","items":["Assembly Duel — manually trace registers and memory without an IDE","Bottleneck Audit — find pipeline stalls in compiled assembly and reschedule instructions","Hardware Visualization Labs — follow data through datapath diagrams / Logisim","Clock-Cycle Stress Test — feed complex instruction streams into a datapath and find where hazards break timing"]},
      {"type":"h2","text":"Recommended toolchain"},
      {"type":"code","code":"Venus (RISC-V)   — browser/desktop assembler & simulator\nMARS (MIPS)     — classic MIPS assembler & runtime\nLogisim-Evol.   — combinational & sequential circuit design\nPencil + paper  — still the best tool for pipeline timing charts","title":"Tool stack","language":"text"},
      {"type":"h2","text":"Assessment mindset (for context)"},
      {"type":"table","headers":["Component","Weight"],"rows":[["Lab participation & punctuality","10%"],["Assignments & architectural reports","20%"],["Mid-term exam","30%"],["Final exam","40%"]]},
      {"type":"note","text":"On InTelleX you learn the same content self-paced. Treat each \"Project Focus\" lesson as a portfolio artifact."},
      {"type":"try","text":"Install or open Venus (or MARS). Run a 3-instruction program that adds two numbers into a register. Confirm you can single-step."},
      {"type":"keypoints","items":["Active labs: Assembly Duel, Bottleneck Audit, visualization, stress tests.","Venus/MARS + Logisim cover assembly and digital logic practice.","Project lessons become your hardware-thinking portfolio."]},
    ],
  },
  {
    slug: "von-neumann-vs-harvard",
    title: "Von Neumann vs Harvard Architecture",
    description: "Compare the classic stored-program model with Harvard separation of instruction and data memory.",
    level: "beginner",
    section: "Architecture of Abstraction",
    order: 3,
    minutes: 12,
    content: [
      {"type":"p","text":"Every modern computer is built around a small set of functional components: processor (CPU), memory, and I/O — connected by buses. Two foundational organization models are Von Neumann and Harvard."},
      {"type":"h2","text":"Von Neumann (stored-program)"},
      {"type":"p","text":"Instructions and data share the same memory space and typically the same bus path to the CPU. This is flexible and simple, but contention between instruction fetch and data access can limit bandwidth — the classic \"Von Neumann bottleneck.\""},
      {"type":"code","code":"CPU  <──bus──>  Unified Memory\n                 [instructions + data]","title":"Von Neumann sketch","language":"text"},
      {"type":"h2","text":"Harvard architecture"},
      {"type":"p","text":"Instructions and data live in separate memories with separate pathways. Embedded DSPs and many microcontrollers use Harvard (or modified Harvard) so instruction fetch and data access can happen in parallel."},
      {"type":"table","headers":["Aspect","Von Neumann","Harvard"],"rows":[["Memory spaces","Unified","Separate I & D"],["Bus contention","Higher risk","Lower for fetch vs data"],["Flexibility","High","More rigid"],["Common in","General-purpose CPUs (conceptually)","DSPs, MCUs, caches as modified Harvard"]]},
      {"type":"tip","text":"Modern CPUs look Von Neumann at the ISA level but often use Harvard-style split caches (I-cache / D-cache) — a modified Harvard design."},
      {"type":"try","text":"Draw both organizations on paper. Label where a load instruction would travel in each model."},
      {"type":"keypoints","items":["Von Neumann stores instructions and data in one address space.","Harvard separates instruction and data memories/paths.","Real CPUs often blend both ideas with split caches."]},
    ],
  },
  {
    slug: "levels-of-program-abstraction",
    title: "Levels of Program Abstraction",
    description: "Walk the stack from problem statement through HLL, assembly, machine code, microarchitecture, and digital logic.",
    level: "beginner",
    section: "Architecture of Abstraction",
    order: 4,
    minutes: 11,
    content: [
      {"type":"p","text":"Software engineers usually live at high levels of abstraction. Architects must see every layer beneath — because each layer hides costs that show up as CPI, stalls, and energy."},
      {"type":"h2","text":"The abstraction tower"},
      {"type":"ol","items":["Problem / algorithm","High-level language (C, Python, …)","Assembly language (ISA interface)","Machine code (binary encodings)","Microarchitecture (pipelines, ALUs, caches)","Digital logic (gates, flip-flops)","Devices & circuits (transistors)"]},
      {"type":"code","code":"int sum = a + b;          // HLL\nadd  x5, x10, x11         // assembly (RISC-V style)\n0x00b505b3                // machine word (example encoding)\n  → ALU add in EX stage   // microarchitecture\n  → XOR/AND gate network  // logic","title":"Same idea, five layers","language":"text"},
      {"type":"note","text":"The ISA is the contract between software and hardware. Compilers target the ISA; microarchitects implement it."},
      {"type":"try","text":"Pick a one-line C statement. Name which layers change if you switch from x86 to RISC-V."},
      {"type":"keypoints","items":["Programs exist at many abstraction layers.","The ISA is the software–hardware contract.","Performance bugs often hide in layers below your source code."]},
    ],
  },
  {
    slug: "iron-law-of-performance",
    title: "The Iron Law of Performance",
    description: "Master CPU time = Instruction Count × CPI × Clock Period — and what each term really means.",
    level: "beginner",
    section: "Architecture of Abstraction",
    order: 5,
    minutes: 13,
    content: [
      {"type":"p","text":"The Iron Law of Processor Performance is the backbone of architectural reasoning. Every optimization must improve at least one factor without destroying the others."},
      {"type":"h2","text":"The equation"},
      {"type":"code","code":"CPU_time = IC × CPI × T\nwhere\n  IC  = instruction count\n  CPI = average clock cycles per instruction\n  T   = clock period (1 / frequency)","title":"Iron Law","language":"text"},
      {"type":"h2","text":"What moves each dial"},
      {"type":"table","headers":["Factor","Improved by","Made worse by"],"rows":[["IC","Better algorithms, smarter ISA","Verbose ISA use, poor compilers"],["CPI","Pipelining, caches, ILP","Hazards, misses, stalls"],["T","Faster technology, shorter critical path","Deeper logic in one cycle"]]},
      {"type":"warning","text":"Faster GHz does not always mean faster programs. Higher frequency with much worse CPI can lose."},
      {"type":"h2","text":"Worked example"},
      {"type":"code","code":"Program A: IC=1e9, CPI=2.0, f=2 GHz → T=0.5 ns\nCPU_time = 1e9 × 2.0 × 0.5e-9 = 1.0 s\n\nProgram B: IC=1.2e9, CPI=1.2, f=2 GHz\nCPU_time = 1.2e9 × 1.2 × 0.5e-9 = 0.72 s  (faster despite more instructions)","title":"Comparing two runs","language":"text"},
      {"type":"try","text":"Invent two machines with different CPI and frequency. Compute which finishes a 500 million instruction program first."},
      {"type":"keypoints","items":["CPU time = IC × CPI × clock period.","Architecture work targets CPI and critical path; software targets IC.","Always compare using the full product, not one metric alone."]},
    ],
  },
  {
    slug: "cpi-clock-cycles-execution-time",
    title: "CPI, Clock Cycles & Execution Time",
    description: "Calculate total cycles, effective CPI for mixed instruction mixes, and wall-clock execution time.",
    level: "beginner",
    section: "Architecture of Abstraction",
    order: 6,
    minutes: 12,
    content: [
      {"type":"p","text":"Real programs are mixes of instruction classes. Effective CPI is a weighted average over that mix."},
      {"type":"h2","text":"Effective CPI"},
      {"type":"code","code":"CPI_eff = Σ (CPI_i × fraction_i)\n\nExample mix:\n  ALU   50% @ 1 cycle\n  Load  20% @ 5 cycles\n  Store 10% @ 4 cycles\n  Branch 20% @ 2 cycles\n\nCPI_eff = 0.5*1 + 0.2*5 + 0.1*4 + 0.2*2 = 2.3","title":"Weighted CPI","language":"text"},
      {"type":"h2","text":"Total cycles and time"},
      {"type":"ul","items":["Clock cycles = IC × CPI_eff","Execution time = clock cycles × clock period","Throughput ≈ frequency / CPI for sustained pipelines (idealized)"]},
      {"type":"tip","text":"When you later study caches, miss penalties show up as extra cycles that inflate CPI."},
      {"type":"try","text":"A loop is 40% loads (CPI 4), 40% ALU (CPI 1), 20% branches (CPI 2). Find CPI_eff."},
      {"type":"keypoints","items":["Effective CPI is a mix-weighted average.","Total cycles = IC × CPI_eff.","Misses and stalls increase effective CPI."]},
    ],
  },
  {
    slug: "architectural-profiler-lab",
    title: "Project: The Architectural Profiler",
    description: "Design a lightweight profiler concept that tracks instruction mixes and graphs CPI for software blocks.",
    level: "beginner",
    section: "Architecture of Abstraction",
    order: 7,
    minutes: 16,
    content: [
      {"type":"p","text":"Week 1 project focus: The Architectural Profiler. You will outline a tool that tracks instruction counts by class, estimates CPI, and compares blocks of code."},
      {"type":"h2","text":"What the profiler reports"},
      {"type":"ul","items":["Instruction count per basic block","Mix percentages: ALU / Load / Store / Branch","Estimated CPI using a simple cost model","Estimated CPU time for a given clock frequency"]},
      {"type":"h2","text":"Minimal data model"},
      {"type":"code","code":"{\n  \"block\": \"matmul_inner\",\n  \"ic\": 1200000,\n  \"mix\": { \"alu\": 0.55, \"load\": 0.25, \"store\": 0.10, \"branch\": 0.10 },\n  \"cpiModel\": { \"alu\": 1, \"load\": 5, \"store\": 4, \"branch\": 2 },\n  \"frequencyHz\": 2000000000\n}","title":"Profiler sample record (JSON)","language":"json"},
      {"type":"h2","text":"Analysis you must write"},
      {"type":"ol","items":["Compute CPI_eff and CPU_time for the block","Identify which instruction class dominates time","Propose one software change that could cut IC or improve locality"]},
      {"type":"try","text":"Profile (manually) a short loop: count instruction classes for 10 iterations. Fill the JSON model and compute CPI_eff."},
      {"type":"keypoints","items":["Profilers connect software structure to Iron Law metrics.","Instruction mix drives effective CPI.","Document assumptions in your architectural report."]},
    ],
  },
  {
    slug: "what-is-an-isa",
    title: "What Is an Instruction Set Architecture?",
    description: "Define the ISA as the hardware/software interface: operations, registers, memory model, and encodings.",
    level: "beginner",
    section: "Instruction Set Architecture",
    order: 8,
    minutes: 12,
    content: [
      {"type":"p","text":"An Instruction Set Architecture (ISA) is the visible interface a program uses to talk to a processor. Microarchitecture can change; the ISA stays the compatibility surface."},
      {"type":"h2","text":"What an ISA specifies"},
      {"type":"ul","items":["Operations (add, load, branch, …)","Data types and sizes","Register set and naming","Memory model and addressing","Instruction encodings (binary formats)","Exception / interrupt behavior (at a high level)"]},
      {"type":"code","code":"Software (compiler / assembly)\n        │  uses\n        ▼\n   ┌─────────┐\n   │   ISA   │  ← contract\n   └─────────┘\n        │  implemented by\n        ▼\n Microarchitecture (pipeline, caches, …)","title":"ISA as contract","language":"text"},
      {"type":"note","text":"RISC-V and MIPS are teaching-friendly RISC ISAs used throughout this course."},
      {"type":"try","text":"List five instructions you expect every general-purpose ISA to provide."},
      {"type":"keypoints","items":["ISA is the software-visible processor interface.","Same ISA can have many microarchitectures.","This course emphasizes RISC-V / MIPS style ISAs."]},
    ],
  },
  {
    slug: "risc-vs-cisc",
    title: "RISC vs CISC Philosophies",
    description: "Contrast Reduced vs Complex Instruction Set designs and why modern machines borrow from both.",
    level: "beginner",
    section: "Instruction Set Architecture",
    order: 9,
    minutes: 12,
    content: [
      {"type":"p","text":"RISC aims for simple, regular instructions that pipeline cleanly. CISC historically packed more work into each instruction to save memory and programmer effort."},
      {"type":"table","headers":["Idea","RISC","CISC"],"rows":[["Instruction complexity","Simple, fixed-ish formats","Varied, sometimes dense"],["Memory ops","Usually load/store only","Many ops may touch memory"],["Pipelining","Easier to decode & schedule","Harder historically"],["Examples","MIPS, RISC-V, ARM (RISC roots)","x86 legacy surface"]]},
      {"type":"tip","text":"Modern high-performance x86 cores translate CISC ops into RISC-like micro-ops internally — CISC outside, RISC-like inside."},
      {"type":"try","text":"Argue in three sentences why a teaching course prefers RISC for pipeline labs."},
      {"type":"keypoints","items":["RISC favors simplicity and pipeline-friendly instructions.","CISC densifies work per instruction at the cost of complexity.","Implementations may blur the line with micro-ops."]},
    ],
  },
  {
    slug: "registers-and-operands",
    title: "Registers, Operands & Calling Conventions",
    description: "Learn register files, operand types, and the RISC-V / MIPS calling convention essentials.",
    level: "beginner",
    section: "Instruction Set Architecture",
    order: 10,
    minutes: 13,
    content: [
      {"type":"p","text":"Registers are the fastest storage the ISA exposes. Most ALU ops work on register operands; memory is accessed via loads and stores."},
      {"type":"h2","text":"RISC-V register sketch (user-level)"},
      {"type":"code","code":"x0  (zero)  — hardwired 0\nx1  (ra)    — return address\nx2  (sp)    — stack pointer\nx5–x7 / x28–x31 — temporaries (t0–t6)\nx8–x9 / x18–x27 — saved (s0–s11)\nx10–x17 — arguments / return (a0–a7)","title":"Common RISC-V ABI names","language":"text"},
      {"type":"h2","text":"Operand kinds"},
      {"type":"ul","items":["Register — value already in the register file","Immediate — constant encoded in the instruction","Memory — address computed, then load/store"]},
      {"type":"warning","text":"x0 is always zero. Writing to it is discarded — a useful architectural trick."},
      {"type":"try","text":"Write a 4-instruction RISC-V-style sequence that computes y = (a + b) - c using only registers."},
      {"type":"keypoints","items":["Registers dominate ALU operand access.","Calling conventions assign roles (args, temps, saved, sp, ra).","Immediates encode constants; memory needs load/store."]},
    ],
  },
  {
    slug: "riscv-instruction-formats",
    title: "RISC-V Instruction Formats",
    description: "Decode R-Type, I-Type, S-Type (and friends): fields, opcodes, and why formats stay regular.",
    level: "beginner",
    section: "Instruction Set Architecture",
    order: 11,
    minutes: 14,
    content: [
      {"type":"p","text":"RISC-V keeps encodings regular so hardware decode stays simple — essential for pipelined control."},
      {"type":"h2","text":"Core formats you must know"},
      {"type":"table","headers":["Format","Typical use","Key fields"],"rows":[["R-Type","reg-reg ALU (add, sub, and)","opcode, rd, funct3, rs1, rs2, funct7"],["I-Type","immediates, loads, jalr","opcode, rd, funct3, rs1, imm"],["S-Type","stores","opcode, funct3, rs1, rs2, imm (split)"],["B-Type","branches","rs1, rs2, imm (PC-relative)"],["U/J-Type","lui / auipc / jal","rd + large immediate"]]},
      {"type":"code","code":"add  rd, rs1, rs2     # R-Type: rd = rs1 + rs2\naddi rd, rs1, imm     # I-Type: rd = rs1 + imm\nlw   rd, off(rs1)     # I-Type load\nsw   rs2, off(rs1)    # S-Type store\nbeq  rs1, rs2, label  # B-Type branch","title":"Assembly ↔ format mapping","language":"asm"},
      {"type":"note","text":"Immediate bits are often scrambled in the encoding to keep register fields in fixed positions — a hardware-friendly choice."},
      {"type":"try","text":"For `lw x5, 8(x10)`, name the format and which register is base vs destination."},
      {"type":"keypoints","items":["R/I/S/B/U/J formats cover common RISC-V ops.","Fixed field positions simplify decode hardware.","Stores and branches place immediates differently than R-Type."]},
    ],
  },
  {
    slug: "memory-addressing-modes",
    title: "Memory Addressing Modes",
    description: "Understand base+offset addressing, alignment, and how addressing modes affect hardware complexity.",
    level: "beginner",
    section: "Instruction Set Architecture",
    order: 12,
    minutes: 11,
    content: [
      {"type":"p","text":"Addressing modes describe how an instruction forms a memory address. RISC ISAs keep modes few and regular."},
      {"type":"h2","text":"Dominant RISC mode: base + offset"},
      {"type":"code","code":"address = R[rs1] + sign_extend(offset)\nlw rd, offset(rs1)\nsw rs2, offset(rs1)","title":"Base+displacement","language":"asm"},
      {"type":"ul","items":["Register indirect — offset 0","Displacement — nonzero offset (struct fields, stack slots)","PC-relative — branches and some data references"]},
      {"type":"warning","text":"Misaligned accesses may trap or be slow depending on the implementation. Prefer naturally aligned loads/stores."},
      {"type":"try","text":"Given `sp = 0x1000`, what address does `lw x5, 12(sp)` access?"},
      {"type":"keypoints","items":["RISC memory ops mostly use base+offset.","Fewer modes → simpler, faster address hardware.","Alignment matters for correctness and speed."]},
    ],
  },
  {
    slug: "translating-c-to-assembly",
    title: "Translating C into RISC-V Assembly",
    description: "Compile nested loops and conditionals by hand into clean assembly with minimal redundant instructions.",
    level: "beginner",
    section: "Instruction Set Architecture",
    order: 13,
    minutes: 15,
    content: [
      {"type":"p","text":"Hand translation builds ISA fluency. Aim for O(1) waste — no redundant loads, no dead moves."},
      {"type":"h2","text":"Example: sum an array"},
      {"type":"code","code":"// C\nint sum = 0;\nfor (int i = 0; i < n; i++)\n  sum += a[i];","title":"Source","language":"c"},
      {"type":"code","code":"# a0 = &a[0], a1 = n\n    li   t0, 0          # sum\n    li   t1, 0          # i\nloop:\n    bge  t1, a1, done\n    slli t2, t1, 2      # i * 4\n    add  t2, a0, t2\n    lw   t3, 0(t2)\n    add  t0, t0, t3\n    addi t1, t1, 1\n    j    loop\ndone:\n    mv   a0, t0         # return sum","title":"RISC-V style assembly","language":"asm"},
      {"type":"tip","text":"Keep induction variables in registers across the loop. Reloading them from memory every iteration is an architectural foul."},
      {"type":"try","text":"Translate `if (x < y) z = x; else z = y;` into branch-based assembly without unnecessary instructions."},
      {"type":"keypoints","items":["Map variables to registers; memory only when needed.","Loops become labels + conditional branches.","Eliminate redundant loads/stores for clean CPI."]},
    ],
  },
  {
    slug: "assembly-duel-register-tracing",
    title: "Lab: The Assembly Duel",
    description: "Manually trace register state and memory contents step-by-step — no emulator crutches.",
    level: "beginner",
    section: "Instruction Set Architecture",
    order: 14,
    minutes: 14,
    content: [
      {"type":"p","text":"In the Assembly Duel you prove you can simulate the machine in your head. This skill feeds every later datapath and hazard lesson."},
      {"type":"h2","text":"Trace table template"},
      {"type":"code","code":"PC   | Instruction        | x5 | x6 | x7 | Mem notes\n100  | addi x5, x0, 4     | 4  |  ? |  ? |\n104  | addi x6, x0, 7     | 4  |  7 |  ? |\n108  | add  x7, x5, x6    | 4  |  7 | 11 |\n10C  | sw   x7, 0(x10)    | 4  |  7 | 11 | MEM[x10]=11","title":"Register/memory trace","language":"text"},
      {"type":"h2","text":"Rules of engagement"},
      {"type":"ol","items":["Update only the destination the instruction defines","For loads/stores, compute the effective address explicitly","Branches: decide taken/not-taken before updating PC","Never skip a row — silent mistakes hide here"]},
      {"type":"try","text":"Trace this sequence on paper starting with all regs 0, x10=0x200: addi x5,x0,3; slli x6,x5,2; add x7,x5,x6; sw x7,0(x10); lw x8,0(x10)."},
      {"type":"keypoints","items":["Manual tracing builds trustworthy hardware intuition.","Record PC, regs, and memory side effects each step.","This is exam-critical skill for mid-term and final."]},
    ],
  },
  {
    slug: "native-translator-project",
    title: "Project: The Native Translator",
    description: "Design a lightweight disassembler that maps binary machine words to human-readable assembly.",
    level: "beginner",
    section: "Instruction Set Architecture",
    order: 15,
    minutes: 16,
    content: [
      {"type":"p","text":"Week 2 project: The Native Translator. Given a 32-bit RISC-V word, decode fields and emit assembly text."},
      {"type":"h2","text":"Decode pipeline"},
      {"type":"ol","items":["Extract opcode (bits 6:0)","Classify format (R/I/S/B/U/J)","Extract rd/rs1/rs2/funct3/funct7/imm as needed","Map to mnemonic via opcode+funct tables","Pretty-print with ABI register names"]},
      {"type":"code","code":"function disassemble(word32):\n  opcode = word32 & 0x7f\n  if opcode == 0x33:  # OP\n    funct3 = ...\n    funct7 = ...\n    return f\"{mnem} {rd}, {rs1}, {rs2}\"\n  if opcode == 0x13:  # OP-IMM\n    ...\n  ...","title":"Disassembler sketch","language":"text"},
      {"type":"note","text":"Start with a subset: add, addi, lw, sw, beq. Expand after the subset is solid."},
      {"type":"try","text":"Hand-decode one R-Type add and one I-Type addi bitfield by bitfield. Write the assembly line."},
      {"type":"keypoints","items":["Disassembly is reverse encoding using fixed field positions.","Opcode selects format; funct fields refine the mnemonic.","Subset-first keeps the project testable."]},
    ],
  },
  {
    slug: "fixed-point-and-signed-numbers",
    title: "Fixed-Point & Signed Number Systems",
    description: "Represent unsigned and signed integers, two's complement, and overflow conditions.",
    level: "beginner",
    section: "ALU & Binary Logic",
    order: 16,
    minutes: 12,
    content: [
      {"type":"p","text":"Before building ALUs, nail number representation. Hardware does not know \"integers\" — it knows bit patterns and rules."},
      {"type":"h2","text":"Two's complement"},
      {"type":"ul","items":["Positive numbers look like unsigned","Negate by invert bits + 1","Range for n bits: −2^(n−1) … 2^(n−1)−1"]},
      {"type":"code","code":"8-bit examples\n  5  = 0000_0101\n -5  = 1111_1011\n -1  = 1111_1111\n127  = 0111_1111\n-128 = 1000_0000","title":"Two's complement patterns","language":"text"},
      {"type":"warning","text":"Overflow ≠ carry out. Signed overflow occurs when carry into the sign bit differs from carry out of the sign bit."},
      {"type":"try","text":"Show the 8-bit two's complement for −20. Add 20 + (−20) and confirm you get 0."},
      {"type":"keypoints","items":["Two's complement unifies add/sub hardware.","Know the representable range for n bits.","Detect signed overflow carefully."]},
    ],
  },
  {
    slug: "binary-arithmetic-basics",
    title: "Binary Addition, Subtraction & Logic Ops",
    description: "Build intuition for full adders, subtract-via-negate, AND/OR/XOR, and shifts as ALU building blocks.",
    level: "beginner",
    section: "ALU & Binary Logic",
    order: 17,
    minutes: 12,
    content: [
      {"type":"p","text":"An ALU is a multiplexed collection of arithmetic and logic circuits. Start with the 1-bit full adder and scale up."},
      {"type":"code","code":"Full adder:\n  sum   = a XOR b XOR cin\n  cout  = majority(a, b, cin)\n\nSubtraction:\n  a - b = a + (~b + 1)","title":"Adder fundamentals","language":"text"},
      {"type":"h2","text":"Logic & shifts"},
      {"type":"ul","items":["AND / OR / XOR — bitwise parallel gates","Logical shift — fill with zeros","Arithmetic shift right — sign-extend","Rotate — optional; not always in base ISA"]},
      {"type":"tip","text":"Shifters can be barrel shifters (fast, more hardware) or iterative (cheap, slower)."},
      {"type":"try","text":"Compute 0b0110_1100 AND 0b1010_1010 and a logical shift left by 2."},
      {"type":"keypoints","items":["Full adders compose into n-bit adders.","Subtraction reuses the adder with invert+cin.","ALU ops are selected by control multiplexers."]},
    ],
  },
  {
    slug: "carry-lookahead-adders",
    title: "Carry-Lookahead Adders",
    description: "Design faster addition with generate/propagate signals — escape the ripple-carry bottleneck.",
    level: "beginner",
    section: "ALU & Binary Logic",
    order: 18,
    minutes: 14,
    content: [
      {"type":"p","text":"Ripple-carry adders are simple but slow: carry may traverse every bit. Carry-lookahead (CLA) computes carries in parallel using generate and propagate."},
      {"type":"code","code":"g_i = a_i AND b_i          # generate\np_i = a_i XOR b_i          # propagate\nc_{i+1} = g_i OR (p_i AND c_i)\n\nCLA expands this into non-recursive forms\nso high carries do not wait on long ripples.","title":"Generate / propagate","language":"text"},
      {"type":"h2","text":"Trade-off"},
      {"type":"table","headers":["Adder","Speed","Hardware cost"],"rows":[["Ripple-carry","O(n)","Low"],["Carry-lookahead","≈O(log n) with hierarchy","Higher gate count / wiring"]]},
      {"type":"note","text":"Week 3 activity: design an 8-bit CLA and compare critical path to ripple-carry."},
      {"type":"try","text":"For bits a=1,b=1 and a=1,b=0, compute g and p. Explain whether carry is generated or only propagated."},
      {"type":"keypoints","items":["CLA uses generate/propagate to speed carries.","You trade silicon area/wiring for lower latency.","Hierarchical CLA scales beyond 4–8 bits cleanly."]},
    ],
  },
  {
    slug: "multipliers-wallace-tree",
    title: "Multipliers & Wallace Trees",
    description: "See how array multipliers and Wallace trees compress partial products for high-speed multiply.",
    level: "beginner",
    section: "ALU & Binary Logic",
    order: 19,
    minutes: 13,
    content: [
      {"type":"p","text":"Multiplication forms partial products, then sums them. Naive array multipliers are regular; Wallace trees reduce critical path by compressing columns with CSA (carry-save adders)."},
      {"type":"h2","text":"Mental model"},
      {"type":"ol","items":["Form partial products (AND of multiplicand by each multiplier bit)","Reduce columns with half/full adders (Wallace) or arrays","Final CPA (carry-propagate adder) produces the product"]},
      {"type":"tip","text":"In processors, multiplies may take multiple pipeline cycles or use dedicated multiply units."},
      {"type":"try","text":"On paper, multiply 6 × 5 in binary showing partial products. Count how many rows you add."},
      {"type":"keypoints","items":["Multiply = partial products + reduction + final add.","Wallace trees target shorter critical paths.","Hardware cost rises quickly with operand width."]},
    ],
  },
  {
    slug: "ieee-754-floating-point",
    title: "IEEE 754 Floating-Point Arithmetic",
    description: "Decode sign, exponent, mantissa; normalize; and handle corner cases that break naive intuition.",
    level: "beginner",
    section: "ALU & Binary Logic",
    order: 20,
    minutes: 15,
    content: [
      {"type":"p","text":"Floating-point approximates real numbers with sign, biased exponent, and fraction. IEEE 754 is the universal contract."},
      {"type":"h2","text":"Binary32 layout"},
      {"type":"code","code":"1 sign | 8 exponent (bias 127) | 23 fraction\nvalue ≈ (-1)^s × 1.frac × 2^(exp-bias)   # normals\nsubnormals, ±inf, NaN are special cases","title":"IEEE 754 single","language":"text"},
      {"type":"h2","text":"Corner cases to trace"},
      {"type":"ul","items":["Overflow → infinity","Underflow → subnormal or zero","NaN propagation from invalid ops","Rounding modes (round-to-nearest-even default)"]},
      {"type":"warning","text":"Floating-point addition is not associative. Architecture and compilers must respect that."},
      {"type":"try","text":"Decode the sign/exponent/fraction story for 1.0 and 0.5 in binary32 (conceptually)."},
      {"type":"keypoints","items":["IEEE 754 defines binary floating formats and specials.","Normalization and rounding are part of correct FP ALUs.","Never assume FP ops behave like exact real arithmetic."]},
    ],
  },
  {
    slug: "custom-alu-project",
    title: "Project: The Custom ALU",
    description: "Specify a simulated ALU supporting arithmetic, logic, and shifts with clear control encodings.",
    level: "beginner",
    section: "ALU & Binary Logic",
    order: 21,
    minutes: 18,
    content: [
      {"type":"p","text":"Week 3 project: The Custom ALU. Implement (in Logisim, HDL, or a software model) an ALU with a documented control interface."},
      {"type":"h2","text":"Required operations"},
      {"type":"ul","items":["ADD","SUB","AND","OR","XOR","SLT","SLL","SRL","SRA"]},
      {"type":"h2","text":"Control sketch"},
      {"type":"code","code":"ALUControl | Result\n0000       | A AND B\n0001       | A OR  B\n0010       | A + B\n0110       | A - B\n0111       | SLT\n1100       | NOR (optional)","title":"Example ALU control map","language":"text"},
      {"type":"h2","text":"Report requirements"},
      {"type":"ol","items":["Block diagram of muxing and adder path","Critical-path discussion (what limits clock if single-cycle?)","Test vectors proving each op, including overflow flags if implemented"]},
      {"type":"try","text":"Write 8 test vectors (A, B, control → expected). Include at least one signed overflow case for ADD."},
      {"type":"keypoints","items":["ALU = ops + multiplexer + flags.","Document control encodings like a hardware API.","Tests are part of architectural professionalism."]},
    ],
  },
  {
    slug: "datapath-elements",
    title: "Datapath Elements",
    description: "Identify PC, instruction memory, register file, ALU, data memory, and the muxes that steer them.",
    level: "beginner",
    section: "Single-Cycle Datapath",
    order: 22,
    minutes: 12,
    content: [
      {"type":"p","text":"A datapath is the set of functional units and wires that move and transform instruction data. Control tells it what to do each cycle."},
      {"type":"h2","text":"Core elements"},
      {"type":"ul","items":["Program Counter (PC)","Instruction memory","Register file (2 read, 1 write typically)","ALU (+ maybe shifter)","Data memory","Sign/immediate extender","Multiplexers for ALU src, writeback, next PC"]},
      {"type":"code","code":"PC → Imem → fields\n           ↘ RegFile → ALU → Dmem → writeback mux → RegFile\n           ↘ ImmGen ↗","title":"Single-cycle dataflow sketch","language":"text"},
      {"type":"try","text":"On a blank page, place the seven elements and draw arrows for a `lw` instruction path."},
      {"type":"keypoints","items":["Datapath elements are shared resources steered by muxes.","Instruction fields feed control and register addresses.","Loads exercise the longest typical path in single-cycle designs."]},
    ],
  },
  {
    slug: "fetch-decode-execute-memory-writeback",
    title: "The Instruction Execution Cycle",
    description: "Trace Fetch → Decode → Execute → Memory → Writeback for ALU, load, store, and branch instructions.",
    level: "beginner",
    section: "Single-Cycle Datapath",
    order: 23,
    minutes: 14,
    content: [
      {"type":"p","text":"Even in a single-cycle machine, we describe instruction flow in five logical stages. Later, pipelining will overlap them in time."},
      {"type":"table","headers":["Stage","What happens"],"rows":[["IF","Fetch instruction at PC; compute PC+4"],["ID","Decode opcode; read registers; extend immediates"],["EX","ALU op / address / branch compare"],["MEM","Access data memory if load/store"],["WB","Write result to register file if needed"]]},
      {"type":"h2","text":"Different instructions, different paths"},
      {"type":"ul","items":["R-Type: IF–ID–EX–WB (skip MEM)","Load: all five stages","Store: IF–ID–EX–MEM (no reg write)","Branch: IF–ID–EX (next PC select)"]},
      {"type":"try","text":"List which stages are active for `beq` vs `add` vs `sw`."},
      {"type":"keypoints","items":["Five-stage vocabulary applies even before pipelining.","Not every instruction uses every stage.","Control signals enable only the needed paths."]},
    ],
  },
  {
    slug: "control-unit-hardwired-vs-microprogrammed",
    title: "Control Units: Hardwired vs Microprogrammed",
    description: "Compare hardwired combinational control with microprogrammed control stores and when each shines.",
    level: "beginner",
    section: "Single-Cycle Datapath",
    order: 24,
    minutes: 12,
    content: [
      {"type":"p","text":"The control unit turns opcodes (and funct fields) into datapath enable signals: RegWrite, ALUSrc, MemRead, MemWrite, Branch, ALUOp, …"},
      {"type":"table","headers":["Style","How it works","Pros / cons"],"rows":[["Hardwired","Combinational logic / PLA from opcode","Fast, less flexible"],["Microprogrammed","Microcode ROM sequences control words","Flexible, historically slower"]]},
      {"type":"code","code":"opcode → Control\n  RegWrite, ALUSrc, ALUOp,\n  MemRead, MemWrite, MemToReg, Branch, Jump","title":"Typical single-cycle control outputs","language":"text"},
      {"type":"tip","text":"RISC single-cycle/pipeline labs almost always use hardwired control for clarity."},
      {"type":"try","text":"Fill a control-signal table row for `lw` and `sw` (which signals asserted?)."},
      {"type":"keypoints","items":["Control decodes ISA bits into datapath enables.","Hardwired control fits RISC teaching datapaths.","Microcode trades flexibility for complexity/latency."]},
    ],
  },
  {
    slug: "blueprint-simulator-project",
    title: "Project: The Blueprint Simulator",
    description: "Model a single-cycle datapath that routes data correctly from opcode-driven control signals.",
    level: "beginner",
    section: "Single-Cycle Datapath",
    order: 25,
    minutes: 18,
    content: [
      {"type":"p","text":"Week 4 project: The Blueprint Simulator. Simulate (diagram + truth tables + optional code) a single-cycle machine for a subset ISA."},
      {"type":"h2","text":"Minimum instruction subset"},
      {"type":"ul","items":["add","addi","lw","sw","beq"]},
      {"type":"h2","text":"Deliverables"},
      {"type":"ol","items":["Labeled datapath diagram with mux select meanings","Control signal table for each instruction","Cycle-by-cycle (logically) walkthrough of one load and one branch","Critical path note: which instruction limits the clock?"]},
      {"type":"warning","text":"In a true single-cycle CPU, clock period ≥ longest instruction path. Loads usually dominate."},
      {"type":"try","text":"Identify the longest path for `lw` through your diagram. List the units on that path in order."},
      {"type":"keypoints","items":["Single-cycle: one instruction completes per cycle.","Control must correctly steer every mux.","Clock is limited by the slowest instruction path."]},
    ],
  },
];
