import type { TutorialLesson } from '../types';

export const intermediateLessons: TutorialLesson[] = [
  {
    slug: "why-pipelining",
    title: "Why Pipelining? Instruction-Level Parallelism",
    description: "See how overlapping instruction stages multiplies throughput without magically shortening individual instruction latency.",
    level: "intermediate",
    section: "Pipeline Paradigm",
    order: 26,
    minutes: 12,
    content: [
      {"type":"p","text":"Pipelining is the assembly line of processors. Multiple instructions occupy different stages at once, raising instruction throughput."},
      {"type":"h2","text":"Latency vs throughput"},
      {"type":"ul","items":["Latency - time for one instruction end-to-end (may stay similar)","Throughput - instructions finished per unit time (rises with pipeline)"]},
      {"type":"code","code":"Ideal speedup ≈ number of stages\n(when stages balanced and no hazards)\n\nReality: hazards, uneven stages, overhead → less than ideal","title":"Idealized view","language":"text"},
      {"type":"try","text":"If a non-pipelined CPI=5 and a perfect 5-stage pipeline approaches CPI≈1, what speedup do you expect before hazards?"},
      {"type":"keypoints","items":["Pipelining overlaps ILP in time.","Throughput gains are the main win.","Hazards will tax ideal speedup - next weeks."]},
    ],
  },
  {
    slug: "five-stage-pipeline",
    title: "The Classic 5-Stage Pipeline",
    description: "Map IF, ID, EX, MEM, WB onto hardware resources and pipeline registers between stages.",
    level: "intermediate",
    section: "Pipeline Paradigm",
    order: 27,
    minutes: 13,
    content: [
      {"type":"p","text":"The MIPS/RISC-V teaching pipeline splits work into five stages separated by pipeline registers that capture intermediate results each clock."},
      {"type":"code","code":"IF | ID | EX | MEM | WB\n ▲    ▲    ▲     ▲\n pipeline registers between stages","title":"Stage boundaries","language":"text"},
      {"type":"h2","text":"What each stage owns"},
      {"type":"table","headers":["Stage","Primary resources"],"rows":[["IF","PC, instruction memory"],["ID","Register file read, decode, imm"],["EX","ALU, branch address"],["MEM","Data memory"],["WB","Register file write"]]},
      {"type":"note","text":"Pipeline registers grow the hardware but enable higher clock rates by shortening the work per cycle."},
      {"type":"try","text":"Draw five boxes and label which memory (I vs D) each stage may touch."},
      {"type":"keypoints","items":["Five stages: IF ID EX MEM WB.","Pipeline registers isolate stage timing.","Resource usage per stage drives structural hazard analysis."]},
    ],
  },
  {
    slug: "pipeline-performance-throughput",
    title: "Pipeline Performance & Throughput",
    description: "Compute pipelined speedup, pipeline CPI with stalls, and the cost of unbalanced stages.",
    level: "intermediate",
    section: "Pipeline Paradigm",
    order: 28,
    minutes: 12,
    content: [
      {"type":"p","text":"Performance math returns - now with stall cycles baked into effective CPI."},
      {"type":"code","code":"CPI_pipeline ≈ 1 + stall_cycles_per_instruction\nSpeedup ≈ (CPI_nonpipe × T_nonpipe) / (CPI_pipe × T_pipe)\n\nOften T_pipe < T_nonpipe because each stage is shorter.","title":"Pipeline performance","language":"text"},
      {"type":"tip","text":"Unbalanced stages waste time every cycle. Architects split or merge work to balance the pipeline."},
      {"type":"try","text":"Non-pipe: 800 ps/instruction. Pipe: 200 ps clock, 0.3 stalls/instr. Estimate speedup."},
      {"type":"keypoints","items":["Stalls raise pipeline CPI above 1.","Clock may be faster than single-cycle.","Balance stages to avoid idle time."]},
    ],
  },
  {
    slug: "pipeline-factory-lab",
    title: "Lab: The Pipeline Factory",
    description: "Manually plot multi-cycle execution charts and calculate speedup versus non-pipelined execution.",
    level: "intermediate",
    section: "Pipeline Paradigm",
    order: 29,
    minutes: 15,
    content: [
      {"type":"p","text":"Plot instructions vs time (cycle numbers). Each instruction occupies one stage cell per cycle - the classic pipeline diagram."},
      {"type":"code","code":"Cycle:  1   2   3   4   5   6   7\nI1:    IF  ID  EX  MEM WB\nI2:        IF  ID  EX  MEM WB\nI3:            IF  ID  EX  MEM WB","title":"Happy-path chart","language":"text"},
      {"type":"h2","text":"Your factory task"},
      {"type":"ol","items":["Chart 6 independent instructions with no hazards","Count total cycles vs non-pipelined 5×6 = 30","Compute speedup","Then insert one stall bubble and recompute"]},
      {"type":"try","text":"Build both charts on paper and write the two speedup numbers."},
      {"type":"keypoints","items":["Pipeline charts make ILP visible.","Bubbles stretch the chart and cut speedup.","This lab feeds hazard mitigation intuition."]},
    ],
  },
  {
    slug: "stage-monitor-project",
    title: "Project: The Stage Monitor",
    description: "Specify a visualization that shows instructions propagating through a 5-stage pipeline in real time.",
    level: "intermediate",
    section: "Pipeline Paradigm",
    order: 30,
    minutes: 16,
    content: [
      {"type":"p","text":"Week 5 project: The Stage Monitor - a UI or console renderer for pipeline occupancy."},
      {"type":"h2","text":"Features"},
      {"type":"ul","items":["Show five stage slots each cycle","Display PC/mnemonic occupying each slot","Advance on a clock tick (manual button fine)","Highlight bubbles as NOP / stall"]},
      {"type":"code","code":"state = { IF: instr1, ID: instr0, EX: null, MEM: null, WB: null }\nonClock():\n  WB  = MEM\n  MEM = EX\n  EX  = ID   # unless stall\n  ID  = IF   # unless stall\n  IF  = fetch(nextPC)","title":"Monitor state machine sketch","language":"text"},
      {"type":"try","text":"Storyboard 8 cycles of your monitor for a 3-instruction program. Note when WB first writes."},
      {"type":"keypoints","items":["Stage monitors teach timing visually.","State is the contents of pipeline registers.","Stalls freeze some transfers while IF may insert NOP."]},
    ],
  },
  {
    slug: "midterm-review-digital-logic",
    title: "Mid-Term Review: Digital Logic & ALU",
    description: "Consolidate adders, number systems, FP basics, and ALU control before the mid-term checkpoint.",
    level: "intermediate",
    section: "Mid-Term Checkpoint",
    order: 31,
    minutes: 14,
    content: [
      {"type":"p","text":"Week 6 mid-term focus areas include digital logic and ALU architectures. Use this lesson as a structured self-exam."},
      {"type":"h2","text":"Drill list"},
      {"type":"ol","items":["Convert ± values to two's complement","Explain CLA generate/propagate","Sketch ALU with op mux","Decode a simple IEEE 754 value conceptually","State overflow vs carry differences"]},
      {"type":"try","text":"Write a 20-minute mini-quiz for yourself from the drill list. Grade ruthlessly."},
      {"type":"keypoints","items":["Mid-term weights logic, ISA, assembly, ALU, basic datapath.","Active recall beats rereading notes.","Be fluent in representations and adder trade-offs."]},
    ],
  },
  {
    slug: "midterm-review-isa-assembly",
    title: "Mid-Term Review: ISA & Assembly",
    description: "Rehearse formats, addressing, and hand translation under timed conditions.",
    level: "intermediate",
    section: "Mid-Term Checkpoint",
    order: 32,
    minutes: 14,
    content: [
      {"type":"p","text":"Flush ISA skills: formats, registers, loads/stores, branches, and tracing."},
      {"type":"h2","text":"Timed drills"},
      {"type":"ul","items":["Identify format from an assembly line in 10 seconds","Translate a 5-line C fragment in under 8 minutes","Complete a full register trace for 8 instructions"]},
      {"type":"warning","text":"Do not rely on an emulator during drill - exams will not."},
      {"type":"try","text":"Pick prior Assembly Duel exercises and redo them cold."},
      {"type":"keypoints","items":["Speed and accuracy both matter on exams.","Tracing without tools is a graded skill.","Formats + calling roles are high-frequency questions."]},
    ],
  },
  {
    slug: "midterm-review-datapath",
    title: "Mid-Term Review: Datapath & Control",
    description: "Trace control signals and mux settings for core instructions on a single-cycle blueprint.",
    level: "intermediate",
    section: "Mid-Term Checkpoint",
    order: 33,
    minutes: 13,
    content: [
      {"type":"p","text":"Expect questions that ask: for instruction X, which control lines are asserted, and which mux inputs are selected?"},
      {"type":"table","headers":["Instr","MemRead","MemWrite","RegWrite","ALUSrc","Branch"],"rows":[["add","0","0","1","0","0"],["lw","1","0","1","1","0"],["sw","0","1","0","1","0"],["beq","0","0","0","0","1"]]},
      {"type":"try","text":"Cover the table and recreate it from memory. Fix any mismatch."},
      {"type":"keypoints","items":["Control tables are exam favorites.","Know why stores do not RegWrite.","Branches redirect Next-PC selection."]},
    ],
  },
  {
    slug: "structural-hazards",
    title: "Structural Hazards",
    description: "Recognize resource conflicts when two stages need the same hardware in one cycle.",
    level: "intermediate",
    section: "Pipeline Hazards",
    order: 34,
    minutes: 11,
    content: [
      {"type":"p","text":"A structural hazard occurs when the pipeline architecture lacks enough hardware to support all overlapping stages."},
      {"type":"h2","text":"Classic examples"},
      {"type":"ul","items":["Unified memory for instructions and data in the same cycle","Single-port register file that cannot read and write as required"]},
      {"type":"tip","text":"Teaching pipelines often assume separate I-mem and D-mem (or caches) to remove the memory structural hazard."},
      {"type":"try","text":"Explain how a modified Harvard split cache avoids a fetch/load structural clash."},
      {"type":"keypoints","items":["Structural hazards = resource collisions.","Duplication or multiporting removes them.","ISA-friendly microarchitecture design prevents many clashes."]},
    ],
  },
  {
    slug: "data-hazards-raw-war-waw",
    title: "Data Hazards: RAW, WAR, WAW",
    description: "Classify read-after-write, write-after-read, and write-after-write dependencies in pipelines.",
    level: "intermediate",
    section: "Pipeline Hazards",
    order: 35,
    minutes: 13,
    content: [
      {"type":"p","text":"Data hazards arise from dependencies between instructions that are in flight together."},
      {"type":"table","headers":["Hazard","Meaning","In 5-stage in-order?"],"rows":[["RAW","Read After Write (true dependence)","Yes - primary concern"],["WAR","Write After Read (anti)","Mostly avoided by fixed WB timing"],["WAW","Write After Write (output)","Mostly avoided in simple pipelines"]]},
      {"type":"code","code":"add  x5, x1, x2\nsub  x8, x5, x3   # RAW on x5 - needs x5 from add","title":"Classic RAW","language":"asm"},
      {"type":"try","text":"Label every dependence in a 4-instruction block you write with at least one RAW chain."},
      {"type":"keypoints","items":["RAW is the true dependence pipelines must handle.","WAR/WAW matter more with out-of-order & renaming.","Always name the register that causes the hazard."]},
    ],
  },
  {
    slug: "control-hazards",
    title: "Control Hazards",
    description: "See why branches disrupt the pipeline and how delay slots or prediction respond.",
    level: "intermediate",
    section: "Pipeline Hazards",
    order: 36,
    minutes: 12,
    content: [
      {"type":"p","text":"Control hazards occur because the next PC depends on an earlier instruction’s outcome - often known late (EX stage compare)."},
      {"type":"ul","items":["Fetched instructions after a branch may be wrong-path","Must squash (flush) or prevent fetch until resolved","Branch prediction guesses to keep the pipe full"]},
      {"type":"warning","text":"Wrong-path instructions must not commit architectural state."},
      {"type":"try","text":"In a 5-stage pipe deciding branches in EX, how many following instructions may be in flight incorrectly?"},
      {"type":"keypoints","items":["Branches create control hazards.","Flush or predict to manage next-PC uncertainty.","Never let wrong-path ops write registers/memory."]},
    ],
  },
  {
    slug: "forwarding-and-bypassing",
    title: "Forwarding & Bypassing",
    description: "Wire EX/MEM and MEM/WB results back to ALU inputs to slash many RAW stalls.",
    level: "intermediate",
    section: "Pipeline Hazards",
    order: 37,
    minutes: 14,
    content: [
      {"type":"p","text":"Forwarding (bypassing) routes newly computed values to earlier stages before they are written back to the register file."},
      {"type":"code","code":"add x5, x1, x2\nsub x6, x5, x3   # forward x5 from EX/MEM → ALU input","title":"Forwarding case","language":"asm"},
      {"type":"h2","text":"What forwarding cannot fix alone"},
      {"type":"p","text":"A load followed immediately by a use needs the memory stage result - typically still requires a one-cycle load-use stall plus forwarding."},
      {"type":"tip","text":"Draw forwarding paths on your datapath diagram; exams love those arrows."},
      {"type":"try","text":"Show with a pipeline chart how forwarding removes a stall between add and sub."},
      {"type":"keypoints","items":["Forwarding feeds results early via muxes.","Load-use hazards still need a stall bubble.","Hazard detection logic controls forward selects + stalls."]},
    ],
  },
  {
    slug: "stalls-and-bubbles",
    title: "Pipeline Stalls & Bubbles",
    description: "Insert NOPs / freeze pipeline registers safely when forwarding is not enough.",
    level: "intermediate",
    section: "Pipeline Hazards",
    order: 38,
    minutes: 11,
    content: [
      {"type":"p","text":"A stall holds younger instructions and inserts a bubble (NOP) into downstream stages so wrong data is not used."},
      {"type":"code","code":"lw  x5, 0(x10)\nsub x6, x5, x7   # load-use: stall 1, then forward from MEM/WB","title":"Load-use pattern","language":"asm"},
      {"type":"ul","items":["Freeze PC and IF/ID","Inject bubble into ID/EX control","Let EX/MEM/WB continue"]},
      {"type":"try","text":"Rewrite a pipeline chart for the load-use pair with exactly one bubble."},
      {"type":"keypoints","items":["Bubbles are intentional NOPs in the pipe.","Stalls preserve correctness when data is not ready.","Minimize stalls via scheduling and caching (later)."]},
    ],
  },
  {
    slug: "branch-prediction",
    title: "Branch Prediction Basics",
    description: "Compare predict-not-taken, static predictors, and 1-bit/2-bit dynamic predictors.",
    level: "intermediate",
    section: "Pipeline Hazards",
    order: 39,
    minutes: 13,
    content: [
      {"type":"p","text":"Branch predictors guess direction (and sometimes target) so the pipeline keeps fetching useful instructions."},
      {"type":"table","headers":["Strategy","Idea","Weakness"],"rows":[["Predict not-taken","Always fall through","Loops hurt"],["Predict taken","Good for many loops","Fails on rare exits"],["1-bit","Remember last outcome","Mispredicts loop exit/entry twice"],["2-bit saturating","Need two fails to flip","More stable for loops"]]},
      {"type":"tip","text":"BTFNT (backwards taken, forwards not-taken) is a strong static heuristic for compiled loops."},
      {"type":"try","text":"Simulate a 1-bit predictor on T,T,T,N for a loop. Count mispredicts."},
      {"type":"keypoints","items":["Prediction hides control hazard latency.","2-bit predictors handle loop patterns better than 1-bit.","Mispredicts flush speculative work."]},
    ],
  },
  {
    slug: "bottleneck-audit-lab",
    title: "Lab: The Bottleneck Audit",
    description: "Analyze assembly for stalls and reschedule instructions to improve throughput.",
    level: "intermediate",
    section: "Pipeline Hazards",
    order: 40,
    minutes: 15,
    content: [
      {"type":"p","text":"Bottleneck Audit: find load-use pairs and long dependence chains, then reorder independent instructions to fill delay slots / reduce stalls."},
      {"type":"code","code":"# Before (load-use stall likely)\nlw  t0, 0(a0)\nadd t1, t0, t2\nlw  t3, 0(a1)\nadd t4, t3, t2\n\n# After (independent lw scheduled earlier)\nlw  t0, 0(a0)\nlw  t3, 0(a1)\nadd t1, t0, t2\nadd t4, t3, t2","title":"Instruction scheduling","language":"asm"},
      {"type":"try","text":"Take a 10-instruction block from your earlier loop and schedule it to minimize assumed load-use stalls."},
      {"type":"keypoints","items":["Compilers and humans both schedule around hazards.","Independent instructions are gold between dependents.","Measure success with fewer bubbles in your chart."]},
    ],
  },
  {
    slug: "hazard-detector-project",
    title: "Project: The Hazard Detector",
    description: "Design a module that scans assembly, flags dependencies, and proposes forwarding paths.",
    level: "intermediate",
    section: "Pipeline Hazards",
    order: 41,
    minutes: 18,
    content: [
      {"type":"p","text":"Week 7 project: The Hazard Detector. Parse a simple assembly subset and report RAW pairs with recommended forwarding or stall."},
      {"type":"h2","text":"Detector output example"},
      {"type":"code","code":"[\n  {\"consumer\": 3, \"producer\": 1, \"reg\": \"x5\",\n   \"distance\": 2, \"action\": \"forward:EX/MEM\"},\n  {\"consumer\": 5, \"producer\": 4, \"reg\": \"x8\",\n   \"distance\": 1, \"action\": \"stall:load-use + forward:MEM/WB\"}\n]","title":"Sample diagnostic JSON","language":"json"},
      {"type":"ol","items":["Parse opcodes and destination/source regs","For each instr, look back at prior destinations still in flight","Emit action: forward path or stall"]},
      {"type":"try","text":"Hand-run your algorithm on a 6-line assembly snippet and produce the JSON list."},
      {"type":"keypoints","items":["Hazard detection is systematic dependence analysis.","Distance in the pipe chooses forward vs stall.","Document assumptions about stage timing."]},
    ],
  },
  {
    slug: "principle-of-locality",
    title: "Principle of Locality",
    description: "Explain temporal and spatial locality - the reason caches and hierarchies work.",
    level: "intermediate",
    section: "Memory Hierarchy",
    order: 42,
    minutes: 11,
    content: [
      {"type":"p","text":"Programs do not access memory uniformly. They reuse recent data (temporal) and touch nearby addresses (spatial). Hierarchies exploit both."},
      {"type":"table","headers":["Locality","Meaning","Hardware help"],"rows":[["Temporal","Reuse same address soon","Keep blocks in cache"],["Spatial","Use nearby addresses soon","Fetch full cache lines"]]},
      {"type":"try","text":"Name one loop in your past code with strong spatial locality and one with poor locality (random pointer chasing)."},
      {"type":"keypoints","items":["Locality makes small fast memories effective.","Cache lines capture spatial locality.","Algorithms can be rewritten to improve locality."]},
    ],
  },
  {
    slug: "cache-direct-mapped",
    title: "Direct-Mapped Caches",
    description: "Map addresses to a single set: tag, index, offset - and compute hits/misses.",
    level: "intermediate",
    section: "Memory Hierarchy",
    order: 43,
    minutes: 14,
    content: [
      {"type":"p","text":"In a direct-mapped cache, each block of main memory maps to exactly one cache line."},
      {"type":"code","code":"address bits → [ tag | index | block offset ]\n\nHit if valid && tag matches at index.","title":"Address breakup","language":"text"},
      {"type":"h2","text":"Conflict misses"},
      {"type":"p","text":"Two active blocks that map to the same index thrash each other - even if the cache is mostly empty. Associativity (next lesson) reduces this."},
      {"type":"try","text":"For an 8-line cache with 4-word blocks, find index/offset/tag bit counts for 32-bit addresses (word-addressed carefully - state assumptions)."},
      {"type":"keypoints","items":["Direct-mapped: one place for each block.","Index selects line; tag identifies identity.","Conflicts cause misses despite free capacity."]},
    ],
  },
  {
    slug: "associative-caches",
    title: "Set-Associative & Fully Associative Caches",
    description: "Compare associativity levels, replacement policies, and the hit-rate vs hardware cost trade-off.",
    level: "intermediate",
    section: "Memory Hierarchy",
    order: 44,
    minutes: 13,
    content: [
      {"type":"p","text":"An N-way set-associative cache lets a block live in any of N ways inside its set. Fully associative means one set with all lines as ways."},
      {"type":"table","headers":["Organization","Flexibility","Compare hardware"],"rows":[["Direct-mapped","Lowest","1 tag compare"],["2/4-way set-assoc","Medium","N comparators"],["Fully associative","Highest","Compare all tags"]]},
      {"type":"tip","text":"LRU, pseudo-LRU, and random are common replacement policies when a set is full."},
      {"type":"try","text":"Explain why increasing associativity often cuts conflict misses but may lengthen hit time."},
      {"type":"keypoints","items":["Associativity reduces conflict misses.","More ways → more comparators / energy.","Replacement policy matters when sets fill."]},
    ],
  },
  {
    slug: "write-policies",
    title: "Write-Through vs Write-Back",
    description: "Choose write policies and write-allocate vs no-write-allocate strategies with clear trade-offs.",
    level: "intermediate",
    section: "Memory Hierarchy",
    order: 45,
    minutes: 12,
    content: [
      {"type":"p","text":"Stores must keep memory hierarchy consistent. Policy choices affect bandwidth, complexity, and AMAT."},
      {"type":"table","headers":["Policy","On hit write","Notes"],"rows":[["Write-through","Update cache + lower level","Simpler; more memory traffic"],["Write-back","Update cache; dirty bit","Write to memory on eviction"]]},
      {"type":"ul","items":["Write-allocate - bring block in on write miss","No-write-allocate - write around to lower level"]},
      {"type":"try","text":"Pick a write-back + write-allocate cache. Describe steps for a store miss."},
      {"type":"keypoints","items":["Write-through vs write-back trade traffic vs complexity.","Dirty bits track write-back lines.","Allocate policies change miss handling for stores."]},
    ],
  },
  {
    slug: "amat-and-miss-rates",
    title: "AMAT & Miss Rate Analysis",
    description: "Compute Average Memory Access Time from hit time, miss rate, and miss penalty - including multilevel caches.",
    level: "intermediate",
    section: "Memory Hierarchy",
    order: 46,
    minutes: 13,
    content: [
      {"type":"p","text":"AMAT summarizes memory performance the way CPI summarizes processor performance."},
      {"type":"code","code":"AMAT = HitTime + MissRate × MissPenalty\n\nTwo-level:\nAMAT = HT1 + MR1 × (HT2 + MR2 × PenaltyMem)","title":"AMAT formulas","language":"text"},
      {"type":"warning","text":"Miss rate ≠ miss penalty. A rare miss that costs 200 cycles can dominate."},
      {"type":"try","text":"HT=2, MR=5%, Penalty=100. Compute AMAT. Then cut MR to 2% and recompute."},
      {"type":"keypoints","items":["AMAT = hit time + miss rate × miss penalty.","Multilevel caches nest the formula.","Optimize the product, not one term blindly."]},
    ],
  },
  {
    slug: "hit-or-miss-lab",
    title: "Lab: Hit or Miss",
    description: "Walk address streams through a small cache, counting hits/misses and tracking line updates.",
    level: "intermediate",
    section: "Memory Hierarchy",
    order: 47,
    minutes: 15,
    content: [
      {"type":"p","text":"Simulate a tiny direct-mapped cache by hand on a fixed address trace."},
      {"type":"h2","text":"Setup"},
      {"type":"code","code":"Cache: 4 lines, block size 1 word (word addresses)\nTrace: 0, 1, 2, 3, 0, 4, 0, 1, 2, 8","title":"Lab configuration","language":"text"},
      {"type":"ol","items":["For each address: compute index = addr mod 4, tag = floor(addr / 4)","Record hit/miss and final tag in each line","Compute miss rate"]},
      {"type":"try","text":"Complete the table for all 10 accesses. Circle compulsory vs conflict misses."},
      {"type":"keypoints","items":["Hand simulation cements cache mechanics.","Classify compulsory, conflict, capacity misses (3 Cs).","Traces reveal thrashing patterns."]},
    ],
  },
  {
    slug: "cache-configurator-project",
    title: "Project: The Cache Configurator",
    description: "Build an algorithmic cache simulator to sweep line size and associativity against AMAT.",
    level: "intermediate",
    section: "Memory Hierarchy",
    order: 48,
    minutes: 18,
    content: [
      {"type":"p","text":"Week 8 project: The Cache Configurator. Parameterize capacity, block size, and associativity; run a trace; report hit rate and AMAT."},
      {"type":"h2","text":"Parameters to sweep"},
      {"type":"ul","items":["Total size","Block size","1/2/4/8-way","Write policy (fix for V1)"]},
      {"type":"code","code":"for config in sweep:\n  sim = Cache(config)\n  for addr in trace:\n    sim.access(addr)\n  report(config, sim.hitRate, sim.amat(ht, penalty))","title":"Sweep harness","language":"text"},
      {"type":"note","text":"Include a short report: which config won and why (locality of your trace)."},
      {"type":"try","text":"Define two configs and predict a winner before simulating. Then verify."},
      {"type":"keypoints","items":["Simulators quantify hierarchy trade-offs.","Block size vs associativity interact with the trace.","Always state hit time / penalty assumptions."]},
    ],
  },
];
