import type { TutorialLesson } from '../types';

export const advancedLessons: TutorialLesson[] = [
  {
    slug: "java-jvm-memory",
    title: "JVM Memory Model Basics",
    description: "Heap, stack, GC at a practical level.",
    level: "advanced",
    section: "JVM Internals",
    order: 49,
    minutes: 16,
    content: [
      {"type":"p","text":"JVM Memory Model Basics is a core skill in the Java path on InTelleX. You will learn jvm memory model basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind JVM Memory Model Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice jvm memory model basics with a small exercise of your own."},
      {"type":"keypoints","items":["JVM Memory Model Basics is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-gc-overview",
    title: "Garbage Collection Overview",
    description: "Why GC pauses matter and how to observe them.",
    level: "advanced",
    section: "JVM Internals",
    order: 50,
    minutes: 16,
    content: [
      {"type":"p","text":"Garbage Collection Overview is a core skill in the Java path on InTelleX. You will learn garbage collection overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Garbage Collection Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice garbage collection overview with a small exercise of your own."},
      {"type":"keypoints","items":["Garbage Collection Overview is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-performance",
    title: "Java Performance Tips",
    description: "Allocation pressure, streams vs loops, profiling.",
    level: "advanced",
    section: "Performance",
    order: 51,
    minutes: 16,
    content: [
      {"type":"p","text":"Java Performance Tips is a core skill in the Java path on InTelleX. You will learn java performance tips with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Java Performance Tips","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice java performance tips with a small exercise of your own."},
      {"type":"keypoints","items":["Java Performance Tips is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-security-basics",
    title: "Security Basics",
    description: "Input validation, secrets, and dependency hygiene.",
    level: "advanced",
    section: "Production",
    order: 52,
    minutes: 16,
    content: [
      {"type":"p","text":"Security Basics is a core skill in the Java path on InTelleX. You will learn security basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Security Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice security basics with a small exercise of your own."},
      {"type":"keypoints","items":["Security Basics is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-dockerize",
    title: "Dockerize a Java App",
    description: "Containerize a JAR for deployment.",
    level: "advanced",
    section: "Production",
    order: 53,
    minutes: 16,
    content: [
      {"type":"p","text":"Dockerize a Java App is a core skill in the Java path on InTelleX. You will learn dockerize a java app with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Dockerize a Java App","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"FROM eclipse-temurin:21-jre\nCOPY app.jar /app.jar\nENTRYPOINT [\"java\",\"-jar\",\"/app.jar\"]","title":"Example","language":"dockerfile"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice dockerize a java app with a small exercise of your own."},
      {"type":"keypoints","items":["Dockerize a Java App is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-design-patterns",
    title: "GoF Patterns in Java",
    description: "Singleton, Factory, Strategy with modern taste.",
    level: "advanced",
    section: "Design",
    order: 54,
    minutes: 16,
    content: [
      {"type":"p","text":"GoF Patterns in Java is a core skill in the Java path on InTelleX. You will learn gof patterns in java with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind GoF Patterns in Java","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice gof patterns in java with a small exercise of your own."},
      {"type":"keypoints","items":["GoF Patterns in Java is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-clean-architecture",
    title: "Clean Architecture Sketch",
    description: "Separate domain from frameworks.",
    level: "advanced",
    section: "Design",
    order: 55,
    minutes: 16,
    content: [
      {"type":"p","text":"Clean Architecture Sketch is a core skill in the Java path on InTelleX. You will learn clean architecture sketch with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Clean Architecture Sketch","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice clean architecture sketch with a small exercise of your own."},
      {"type":"keypoints","items":["Clean Architecture Sketch is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-annotations",
    title: "Annotations",
    description: "Built-in and custom annotations for metadata.",
    level: "advanced",
    section: "Modern Java",
    order: 56,
    minutes: 16,
    content: [
      {"type":"p","text":"Annotations is a core skill in the Java path on InTelleX. You will learn annotations with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Annotations","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice annotations with a small exercise of your own."},
      {"type":"keypoints","items":["Annotations is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-reflection-intro",
    title: "Reflection Intro",
    description: "Inspect types at runtime carefully.",
    level: "advanced",
    section: "JVM Internals",
    order: 57,
    minutes: 16,
    content: [
      {"type":"p","text":"Reflection Intro is a core skill in the Java path on InTelleX. You will learn reflection intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Reflection Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice reflection intro with a small exercise of your own."},
      {"type":"keypoints","items":["Reflection Intro is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-modules-overview",
    title: "Java Platform Module System",
    description: "module-info.java and strong encapsulation overview.",
    level: "advanced",
    section: "JVM Internals",
    order: 58,
    minutes: 16,
    content: [
      {"type":"p","text":"Java Platform Module System is a core skill in the Java path on InTelleX. You will learn java platform module system with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Java Platform Module System","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice java platform module system with a small exercise of your own."},
      {"type":"keypoints","items":["Java Platform Module System is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-reactive-preview",
    title: "Reactive Preview",
    description: "When reactive streams help high-concurrency I/O.",
    level: "advanced",
    section: "Toward Backend Java",
    order: 59,
    minutes: 16,
    content: [
      {"type":"p","text":"Reactive Preview is a core skill in the Java path on InTelleX. You will learn reactive preview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Reactive Preview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice reactive preview with a small exercise of your own."},
      {"type":"keypoints","items":["Reactive Preview is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-capstone-todo-api",
    title: "Capstone: Todo API",
    description: "In-memory REST-style service with tests.",
    level: "advanced",
    section: "Capstone",
    order: 60,
    minutes: 20,
    content: [
      {"type":"p","text":"Capstone: Todo API is a core skill in the Java path on InTelleX. You will learn capstone: todo api with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Todo API","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice capstone: todo api with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Todo API is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-capstone-bank",
    title: "Capstone: Bank Account Domain",
    description: "Model accounts, transfers, and invariants.",
    level: "advanced",
    section: "Capstone",
    order: 61,
    minutes: 20,
    content: [
      {"type":"p","text":"Capstone: Bank Account Domain is a core skill in the Java path on InTelleX. You will learn capstone: bank account domain with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Bank Account Domain","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice capstone: bank account domain with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Bank Account Domain is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-capstone-cli-toolkit",
    title: "Capstone: CLI Toolkit",
    description: "Multi-command console tool with subcommands and tests.",
    level: "advanced",
    section: "Capstone",
    order: 62,
    minutes: 18,
    content: [
      {"type":"p","text":"Capstone: CLI Toolkit is a core skill in the Java path on InTelleX. You will learn capstone: cli toolkit with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: CLI Toolkit","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice capstone: cli toolkit with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: CLI Toolkit is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-capstone-file-indexer",
    title: "Capstone: File Indexer",
    description: "Walk a directory, index words, and answer queries.",
    level: "advanced",
    section: "Capstone",
    order: 63,
    minutes: 18,
    content: [
      {"type":"p","text":"Capstone: File Indexer is a core skill in the Java path on InTelleX. You will learn capstone: file indexer with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: File Indexer","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice capstone: file indexer with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: File Indexer is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-interview-review",
    title: "Java Interview Review",
    description: "OOP, collections, concurrency, and JVM checklist.",
    level: "advanced",
    section: "Polish & Next Steps",
    order: 64,
    minutes: 16,
    content: [
      {"type":"p","text":"Java Interview Review is a core skill in the Java path on InTelleX. You will learn java interview review with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Java Interview Review","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice java interview review with a small exercise of your own."},
      {"type":"keypoints","items":["Java Interview Review is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-next-steps",
    title: "Next Steps in Java",
    description: "Spring, Android Kotlin path, or data engineering.",
    level: "advanced",
    section: "Polish & Next Steps",
    order: 65,
    minutes: 16,
    content: [
      {"type":"p","text":"Next Steps in Java is a core skill in the Java path on InTelleX. You will learn next steps in java with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Next Steps in Java","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice next steps in java with a small exercise of your own."},
      {"type":"keypoints","items":["Next Steps in Java is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
