import type { TutorialLesson } from '../types';

export const beginnerLessons: TutorialLesson[] = [
  {
    slug: "welcome-to-java",
    title: "Welcome to Java",
    description: "Why Java remains a top language for backends and Android foundations.",
    level: "beginner",
    section: "Getting Started",
    order: 1,
    minutes: 11,
    content: [
      {"type":"p","text":"Welcome to Java is a core skill in the Java path on InTelleX. You will learn welcome to java with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Welcome to Java","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"public class Hello {\n  public static void main(String[] args) {\n    System.out.println(\"Hello, Java\");\n  }\n}","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice welcome to java with a small exercise of your own."},
      {"type":"keypoints","items":["Welcome to Java is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-jdk-setup",
    title: "Install the JDK",
    description: "Install a modern JDK and verify javac/java.",
    level: "beginner",
    section: "Getting Started",
    order: 2,
    minutes: 11,
    content: [
      {"type":"p","text":"Install the JDK is a core skill in the Java path on InTelleX. You will learn install the jdk with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Install the JDK","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"java -version\njavac -version","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice install the jdk with a small exercise of your own."},
      {"type":"keypoints","items":["Install the JDK is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-first-program",
    title: "Your First Java Program",
    description: "Compile and run a class with a main method.",
    level: "beginner",
    section: "Getting Started",
    order: 3,
    minutes: 11,
    content: [
      {"type":"p","text":"Your First Java Program is a core skill in the Java path on InTelleX. You will learn your first java program with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Your First Java Program","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice your first java program with a small exercise of your own."},
      {"type":"keypoints","items":["Your First Java Program is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-variables",
    title: "Variables & Types",
    description: "Primitives vs reference types.",
    level: "beginner",
    section: "Language Basics",
    order: 4,
    minutes: 11,
    content: [
      {"type":"p","text":"Variables & Types is a core skill in the Java path on InTelleX. You will learn variables & types with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Variables & Types","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"int count = 3;\ndouble price = 9.99;\nboolean ok = true;\nString name = \"Ada\";","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice variables & types with a small exercise of your own."},
      {"type":"keypoints","items":["Variables & Types is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-operators",
    title: "Operators",
    description: "Arithmetic, relational, and logical operators.",
    level: "beginner",
    section: "Language Basics",
    order: 5,
    minutes: 11,
    content: [
      {"type":"p","text":"Operators is a core skill in the Java path on InTelleX. You will learn operators with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Operators","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice operators with a small exercise of your own."},
      {"type":"keypoints","items":["Operators is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-strings",
    title: "Strings",
    description: "Immutable strings, concatenation, and useful methods.",
    level: "beginner",
    section: "Language Basics",
    order: 6,
    minutes: 11,
    content: [
      {"type":"p","text":"Strings is a core skill in the Java path on InTelleX. You will learn strings with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Strings","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"String s = \"Intellex\";\nSystem.out.println(s.length());\nSystem.out.println(s.toUpperCase());","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice strings with a small exercise of your own."},
      {"type":"keypoints","items":["Strings is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-conditionals",
    title: "Conditionals",
    description: "if/else and switch expressions.",
    level: "beginner",
    section: "Control Flow",
    order: 7,
    minutes: 11,
    content: [
      {"type":"p","text":"Conditionals is a core skill in the Java path on InTelleX. You will learn conditionals with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Conditionals","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice conditionals with a small exercise of your own."},
      {"type":"keypoints","items":["Conditionals is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-loops",
    title: "Loops",
    description: "for, while, enhanced for.",
    level: "beginner",
    section: "Control Flow",
    order: 8,
    minutes: 11,
    content: [
      {"type":"p","text":"Loops is a core skill in the Java path on InTelleX. You will learn loops with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Loops","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"for (int i = 0; i < 5; i++) {\n  System.out.println(i);\n}","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice loops with a small exercise of your own."},
      {"type":"keypoints","items":["Loops is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-methods",
    title: "Methods",
    description: "Static and instance methods with return types.",
    level: "beginner",
    section: "Methods",
    order: 9,
    minutes: 11,
    content: [
      {"type":"p","text":"Methods is a core skill in the Java path on InTelleX. You will learn methods with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Methods","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"static int add(int a, int b) {\n  return a + b;\n}","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice methods with a small exercise of your own."},
      {"type":"keypoints","items":["Methods is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-overloading",
    title: "Method Overloading",
    description: "Same name, different parameter lists.",
    level: "beginner",
    section: "Methods",
    order: 10,
    minutes: 11,
    content: [
      {"type":"p","text":"Method Overloading is a core skill in the Java path on InTelleX. You will learn method overloading with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Method Overloading","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice method overloading with a small exercise of your own."},
      {"type":"keypoints","items":["Method Overloading is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-arrays",
    title: "Arrays",
    description: "Fixed-length arrays and iteration.",
    level: "beginner",
    section: "Collections Basics",
    order: 11,
    minutes: 11,
    content: [
      {"type":"p","text":"Arrays is a core skill in the Java path on InTelleX. You will learn arrays with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Arrays","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"int[] nums = {1, 2, 3};\nSystem.out.println(nums[0]);","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice arrays with a small exercise of your own."},
      {"type":"keypoints","items":["Arrays is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-arraylist",
    title: "ArrayList",
    description: "Resizable lists from java.util.",
    level: "beginner",
    section: "Collections Basics",
    order: 12,
    minutes: 11,
    content: [
      {"type":"p","text":"ArrayList is a core skill in the Java path on InTelleX. You will learn arraylist with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind ArrayList","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"import java.util.ArrayList;\nArrayList<String> names = new ArrayList<>();\nnames.add(\"Ada\");","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice arraylist with a small exercise of your own."},
      {"type":"keypoints","items":["ArrayList is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-hashmap",
    title: "HashMap",
    description: "Key-value storage for lookups.",
    level: "beginner",
    section: "Collections Basics",
    order: 13,
    minutes: 11,
    content: [
      {"type":"p","text":"HashMap is a core skill in the Java path on InTelleX. You will learn hashmap with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind HashMap","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"import java.util.HashMap;\nHashMap<String, Integer> ages = new HashMap<>();\nages.put(\"Ada\", 36);","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice hashmap with a small exercise of your own."},
      {"type":"keypoints","items":["HashMap is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-classes",
    title: "Classes & Objects",
    description: "Fields, constructors, and methods.",
    level: "beginner",
    section: "OOP Foundations",
    order: 14,
    minutes: 11,
    content: [
      {"type":"p","text":"Classes & Objects is a core skill in the Java path on InTelleX. You will learn classes & objects with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Classes & Objects","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"class Person {\n  String name;\n  Person(String name) { this.name = name; }\n}","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice classes & objects with a small exercise of your own."},
      {"type":"keypoints","items":["Classes & Objects is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-encapsulation",
    title: "Encapsulation",
    description: "private fields with getters/setters.",
    level: "beginner",
    section: "OOP Foundations",
    order: 15,
    minutes: 11,
    content: [
      {"type":"p","text":"Encapsulation is a core skill in the Java path on InTelleX. You will learn encapsulation with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Encapsulation","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice encapsulation with a small exercise of your own."},
      {"type":"keypoints","items":["Encapsulation is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-inheritance",
    title: "Inheritance",
    description: "extends and method overriding.",
    level: "beginner",
    section: "OOP Foundations",
    order: 16,
    minutes: 11,
    content: [
      {"type":"p","text":"Inheritance is a core skill in the Java path on InTelleX. You will learn inheritance with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Inheritance","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice inheritance with a small exercise of your own."},
      {"type":"keypoints","items":["Inheritance is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-polymorphism",
    title: "Polymorphism",
    description: "Program to interfaces and base types.",
    level: "beginner",
    section: "OOP Foundations",
    order: 17,
    minutes: 11,
    content: [
      {"type":"p","text":"Polymorphism is a core skill in the Java path on InTelleX. You will learn polymorphism with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Polymorphism","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice polymorphism with a small exercise of your own."},
      {"type":"keypoints","items":["Polymorphism is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-interfaces",
    title: "Interfaces",
    description: "Contracts that classes implement.",
    level: "beginner",
    section: "OOP Foundations",
    order: 18,
    minutes: 11,
    content: [
      {"type":"p","text":"Interfaces is a core skill in the Java path on InTelleX. You will learn interfaces with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Interfaces","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"interface Greeter {\n  String greet();\n}","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice interfaces with a small exercise of your own."},
      {"type":"keypoints","items":["Interfaces is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-packages",
    title: "Packages",
    description: "Organize code with package declarations.",
    level: "beginner",
    section: "Projects",
    order: 19,
    minutes: 11,
    content: [
      {"type":"p","text":"Packages is a core skill in the Java path on InTelleX. You will learn packages with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Packages","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice packages with a small exercise of your own."},
      {"type":"keypoints","items":["Packages is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-access-modifiers",
    title: "Access Modifiers",
    description: "public, private, protected, and package-private.",
    level: "beginner",
    section: "Projects",
    order: 20,
    minutes: 11,
    content: [
      {"type":"p","text":"Access Modifiers is a core skill in the Java path on InTelleX. You will learn access modifiers with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Access Modifiers","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice access modifiers with a small exercise of your own."},
      {"type":"keypoints","items":["Access Modifiers is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-static",
    title: "static Members",
    description: "When state belongs to the class.",
    level: "beginner",
    section: "Projects",
    order: 21,
    minutes: 11,
    content: [
      {"type":"p","text":"static Members is a core skill in the Java path on InTelleX. You will learn static members with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind static Members","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice static members with a small exercise of your own."},
      {"type":"keypoints","items":["static Members is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-exceptions-intro",
    title: "Exceptions Intro",
    description: "Checked vs unchecked exceptions.",
    level: "beginner",
    section: "Errors",
    order: 22,
    minutes: 11,
    content: [
      {"type":"p","text":"Exceptions Intro is a core skill in the Java path on InTelleX. You will learn exceptions intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Exceptions Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"try {\n  Integer.parseInt(\"x\");\n} catch (NumberFormatException e) {\n  System.out.println(\"bad number\");\n}","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice exceptions intro with a small exercise of your own."},
      {"type":"keypoints","items":["Exceptions Intro is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-scanner",
    title: "Scanner Input",
    description: "Read console input safely.",
    level: "beginner",
    section: "I/O Basics",
    order: 23,
    minutes: 11,
    content: [
      {"type":"p","text":"Scanner Input is a core skill in the Java path on InTelleX. You will learn scanner input with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Scanner Input","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice scanner input with a small exercise of your own."},
      {"type":"keypoints","items":["Scanner Input is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-files-intro",
    title: "Reading Files",
    description: "NIO Path and Files helpers.",
    level: "beginner",
    section: "I/O Basics",
    order: 24,
    minutes: 11,
    content: [
      {"type":"p","text":"Reading Files is a core skill in the Java path on InTelleX. You will learn reading files with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Reading Files","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice reading files with a small exercise of your own."},
      {"type":"keypoints","items":["Reading Files is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-mini-quiz-app",
    title: "Project: Quiz App",
    description: "Build a console quiz with ArrayList of questions.",
    level: "beginner",
    section: "Projects",
    order: 25,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: Quiz App is a core skill in the Java path on InTelleX. You will learn project: quiz app with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Quiz App","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice project: quiz app with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Quiz App is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
