import type { TutorialLesson } from '../types';

export const intermediateLessons: TutorialLesson[] = [
  {
    slug: "java-equals-hashcode",
    title: "equals & hashCode",
    description: "Correct equality for map keys and sets.",
    level: "intermediate",
    section: "Solid OOP",
    order: 26,
    minutes: 13,
    content: [
      {"type":"p","text":"equals & hashCode is a core skill in the Java path on InTelleX. You will learn equals & hashcode with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind equals & hashCode","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice equals & hashcode with a small exercise of your own."},
      {"type":"keypoints","items":["equals & hashCode is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-records",
    title: "Records",
    description: "Compact immutable data carriers.",
    level: "intermediate",
    section: "Modern Java",
    order: 27,
    minutes: 13,
    content: [
      {"type":"p","text":"Records is a core skill in the Java path on InTelleX. You will learn records with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Records","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"record Point(int x, int y) {}","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice records with a small exercise of your own."},
      {"type":"keypoints","items":["Records is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-enums",
    title: "Enums",
    description: "Typed constants with behavior.",
    level: "intermediate",
    section: "Modern Java",
    order: 28,
    minutes: 13,
    content: [
      {"type":"p","text":"Enums is a core skill in the Java path on InTelleX. You will learn enums with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Enums","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice enums with a small exercise of your own."},
      {"type":"keypoints","items":["Enums is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-generics",
    title: "Generics",
    description: "Type-safe collections and methods.",
    level: "intermediate",
    section: "Modern Java",
    order: 29,
    minutes: 13,
    content: [
      {"type":"p","text":"Generics is a core skill in the Java path on InTelleX. You will learn generics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Generics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"public static <T> void printAll(List<T> items) {\n  for (T item : items) System.out.println(item);\n}","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice generics with a small exercise of your own."},
      {"type":"keypoints","items":["Generics is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-streams",
    title: "Streams API",
    description: "map/filter/reduce style processing.",
    level: "intermediate",
    section: "Modern Java",
    order: 30,
    minutes: 13,
    content: [
      {"type":"p","text":"Streams API is a core skill in the Java path on InTelleX. You will learn streams api with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Streams API","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"list.stream()\n  .filter(s -> s.length() > 3)\n  .map(String::toUpperCase)\n  .forEach(System.out::println);","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice streams api with a small exercise of your own."},
      {"type":"keypoints","items":["Streams API is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-optional",
    title: "Optional",
    description: "Avoid null proliferation with Optional.",
    level: "intermediate",
    section: "Modern Java",
    order: 31,
    minutes: 13,
    content: [
      {"type":"p","text":"Optional is a core skill in the Java path on InTelleX. You will learn optional with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Optional","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice optional with a small exercise of your own."},
      {"type":"keypoints","items":["Optional is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-lambda",
    title: "Lambdas & Functional Interfaces",
    description: "Pass behavior as data.",
    level: "intermediate",
    section: "Modern Java",
    order: 32,
    minutes: 13,
    content: [
      {"type":"p","text":"Lambdas & Functional Interfaces is a core skill in the Java path on InTelleX. You will learn lambdas & functional interfaces with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Lambdas & Functional Interfaces","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice lambdas & functional interfaces with a small exercise of your own."},
      {"type":"keypoints","items":["Lambdas & Functional Interfaces is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-collections-deep",
    title: "Collections Deep Dive",
    description: "List, Set, Map trade-offs.",
    level: "intermediate",
    section: "Collections Advanced",
    order: 33,
    minutes: 13,
    content: [
      {"type":"p","text":"Collections Deep Dive is a core skill in the Java path on InTelleX. You will learn collections deep dive with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Collections Deep Dive","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice collections deep dive with a small exercise of your own."},
      {"type":"keypoints","items":["Collections Deep Dive is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-sorting",
    title: "Sorting & Comparators",
    description: "Comparable vs Comparator.",
    level: "intermediate",
    section: "Collections Advanced",
    order: 34,
    minutes: 13,
    content: [
      {"type":"p","text":"Sorting & Comparators is a core skill in the Java path on InTelleX. You will learn sorting & comparators with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Sorting & Comparators","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice sorting & comparators with a small exercise of your own."},
      {"type":"keypoints","items":["Sorting & Comparators is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-exceptions-advanced",
    title: "Custom Exceptions",
    description: "Create domain-specific exception types.",
    level: "intermediate",
    section: "Reliability",
    order: 35,
    minutes: 13,
    content: [
      {"type":"p","text":"Custom Exceptions is a core skill in the Java path on InTelleX. You will learn custom exceptions with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Custom Exceptions","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice custom exceptions with a small exercise of your own."},
      {"type":"keypoints","items":["Custom Exceptions is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-logging",
    title: "Logging Basics",
    description: "Replace System.out with structured logs.",
    level: "intermediate",
    section: "Reliability",
    order: 36,
    minutes: 13,
    content: [
      {"type":"p","text":"Logging Basics is a core skill in the Java path on InTelleX. You will learn logging basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Logging Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice logging basics with a small exercise of your own."},
      {"type":"keypoints","items":["Logging Basics is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-junit",
    title: "JUnit Testing",
    description: "Write and run unit tests.",
    level: "intermediate",
    section: "Testing",
    order: 37,
    minutes: 13,
    content: [
      {"type":"p","text":"JUnit Testing is a core skill in the Java path on InTelleX. You will learn junit testing with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind JUnit Testing","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"import org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass MathTest {\n  @Test\n  void adds() { assertEquals(5, 2 + 3); }\n}","title":"Example","language":"java"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice junit testing with a small exercise of your own."},
      {"type":"keypoints","items":["JUnit Testing is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-maven-intro",
    title: "Maven Intro",
    description: "pom.xml, dependencies, and phases.",
    level: "intermediate",
    section: "Build Tools",
    order: 38,
    minutes: 13,
    content: [
      {"type":"p","text":"Maven Intro is a core skill in the Java path on InTelleX. You will learn maven intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Maven Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice maven intro with a small exercise of your own."},
      {"type":"keypoints","items":["Maven Intro is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-gradle-intro",
    title: "Gradle Intro",
    description: "Groovy/Kotlin DSL build scripts.",
    level: "intermediate",
    section: "Build Tools",
    order: 39,
    minutes: 13,
    content: [
      {"type":"p","text":"Gradle Intro is a core skill in the Java path on InTelleX. You will learn gradle intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Gradle Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice gradle intro with a small exercise of your own."},
      {"type":"keypoints","items":["Gradle Intro is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-jdbc-intro",
    title: "JDBC Intro",
    description: "Connect to a database from Java.",
    level: "intermediate",
    section: "Data Access",
    order: 40,
    minutes: 13,
    content: [
      {"type":"p","text":"JDBC Intro is a core skill in the Java path on InTelleX. You will learn jdbc intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind JDBC Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice jdbc intro with a small exercise of your own."},
      {"type":"keypoints","items":["JDBC Intro is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-http-client",
    title: "HTTP Client",
    description: "Call APIs with java.net.http.",
    level: "intermediate",
    section: "Networking",
    order: 41,
    minutes: 13,
    content: [
      {"type":"p","text":"HTTP Client is a core skill in the Java path on InTelleX. You will learn http client with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind HTTP Client","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice http client with a small exercise of your own."},
      {"type":"keypoints","items":["HTTP Client is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-json",
    title: "JSON in Java",
    description: "Parse and produce JSON with a library.",
    level: "intermediate",
    section: "Networking",
    order: 42,
    minutes: 13,
    content: [
      {"type":"p","text":"JSON in Java is a core skill in the Java path on InTelleX. You will learn json in java with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind JSON in Java","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice json in java with a small exercise of your own."},
      {"type":"keypoints","items":["JSON in Java is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-threads",
    title: "Threads Basics",
    description: "Runnable, Thread, and executors overview.",
    level: "intermediate",
    section: "Concurrency",
    order: 43,
    minutes: 13,
    content: [
      {"type":"p","text":"Threads Basics is a core skill in the Java path on InTelleX. You will learn threads basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Threads Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice threads basics with a small exercise of your own."},
      {"type":"keypoints","items":["Threads Basics is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-executors",
    title: "ExecutorService",
    description: "Thread pools for concurrent tasks.",
    level: "intermediate",
    section: "Concurrency",
    order: 44,
    minutes: 13,
    content: [
      {"type":"p","text":"ExecutorService is a core skill in the Java path on InTelleX. You will learn executorservice with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind ExecutorService","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice executorservice with a small exercise of your own."},
      {"type":"keypoints","items":["ExecutorService is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-project-library",
    title: "Project: Library Manager",
    description: "CRUD books with classes and ArrayList persistence.",
    level: "intermediate",
    section: "Capstone Labs",
    order: 45,
    minutes: 20,
    content: [
      {"type":"p","text":"Project: Library Manager is a core skill in the Java path on InTelleX. You will learn project: library manager with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Library Manager","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice project: library manager with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Library Manager is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-project-api-client",
    title: "Project: API Client CLI",
    description: "Fetch JSON and display results.",
    level: "intermediate",
    section: "Capstone Labs",
    order: 46,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: API Client CLI is a core skill in the Java path on InTelleX. You will learn project: api client cli with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: API Client CLI","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice project: api client cli with a small exercise of your own."},
      {"type":"keypoints","items":["Project: API Client CLI is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-spring-preview",
    title: "Spring Boot Preview",
    description: "What Spring Boot adds for web APIs.",
    level: "intermediate",
    section: "Toward Backend Java",
    order: 47,
    minutes: 13,
    content: [
      {"type":"p","text":"Spring Boot Preview is a core skill in the Java path on InTelleX. You will learn spring boot preview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Spring Boot Preview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice spring boot preview with a small exercise of your own."},
      {"type":"keypoints","items":["Spring Boot Preview is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "java-rest-controller",
    title: "A Tiny REST Controller",
    description: "Map HTTP endpoints conceptually with Spring.",
    level: "intermediate",
    section: "Toward Backend Java",
    order: 48,
    minutes: 13,
    content: [
      {"type":"p","text":"A Tiny REST Controller is a core skill in the Java path on InTelleX. You will learn a tiny rest controller with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind A Tiny REST Controller","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Java lab folder as you go."},
      {"type":"try","text":"Practice a tiny rest controller with a small exercise of your own."},
      {"type":"keypoints","items":["A Tiny REST Controller is an essential Java skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
