/**
 * Curated YouTube tutorial library — hand-picked, high-quality, free video
 * courses that complement the Intellex tracks. Embedded with youtube-nocookie.
 */

export interface VideoTutorial {
  id: string;
  /** YouTube video id. */
  youtubeId: string;
  title: string;
  channel: string;
  category: string;
  duration: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  description: string;
}

export const VIDEO_CATEGORIES = [
  'All',
  'Web Development',
  'Python',
  'JavaScript',
  'Backend',
  'Databases',
  'DevOps',
  'Data & AI',
  'Mobile',
  'Career',
] as const;

export const VIDEO_TUTORIALS: VideoTutorial[] = [
  {
    id: 'html-full',
    youtubeId: 'kUMe1FH4CHE',
    title: 'HTML Full Course for Beginners',
    channel: 'freeCodeCamp',
    category: 'Web Development',
    duration: '4h',
    level: 'Beginner',
    description: 'Everything you need to write your first real web pages — elements, forms, semantic HTML and accessibility.',
  },
  {
    id: 'css-full',
    youtubeId: 'OXGznpKZ_sA',
    title: 'CSS Full Course — Zero to Hero',
    channel: 'freeCodeCamp',
    category: 'Web Development',
    duration: '11h',
    level: 'Beginner',
    description: 'Selectors, flexbox, grid, animations and responsive design in one deep course.',
  },
  {
    id: 'js-full',
    youtubeId: 'PkZNo7MFNFg',
    title: 'Learn JavaScript — Full Course for Beginners',
    channel: 'freeCodeCamp',
    category: 'JavaScript',
    duration: '3.5h',
    level: 'Beginner',
    description: 'The classic JavaScript foundation course — variables, functions, objects, arrays and ES6.',
  },
  {
    id: 'js-dom',
    youtubeId: '5fb2aPlgoys',
    title: 'JavaScript DOM Manipulation',
    channel: 'freeCodeCamp',
    category: 'JavaScript',
    duration: '2h',
    level: 'Intermediate',
    description: 'Make pages interactive: selecting elements, events, and building small UI widgets from scratch.',
  },
  {
    id: 'react-course',
    youtubeId: 'bMknfKXIFA8',
    title: 'React Course — Beginner Tutorial',
    channel: 'freeCodeCamp',
    category: 'Web Development',
    duration: '12h',
    level: 'Intermediate',
    description: 'Components, props, state, hooks and building complete React projects.',
  },
  {
    id: 'nextjs-course',
    youtubeId: 'ZVnjOPwW4ZA',
    title: 'Next.js Full Course',
    channel: 'JavaScript Mastery',
    category: 'Web Development',
    duration: '5h',
    level: 'Intermediate',
    description: 'App router, server components, API routes and deploying a production Next.js app.',
  },
  {
    id: 'python-full',
    youtubeId: 'rfscVS0vtbw',
    title: 'Learn Python — Full Course for Beginners',
    channel: 'freeCodeCamp',
    category: 'Python',
    duration: '4.5h',
    level: 'Beginner',
    description: 'The most-watched Python course on the internet — syntax, functions, and your first programs.',
  },
  {
    id: 'python-oop',
    youtubeId: 'Ej_02ICOIgs',
    title: 'Object Oriented Programming with Python',
    channel: 'freeCodeCamp',
    category: 'Python',
    duration: '2h',
    level: 'Intermediate',
    description: 'Classes, inheritance, and designing clean Python programs the OOP way.',
  },
  {
    id: 'node-express',
    youtubeId: 'Oe421EPjeBE',
    title: 'Node.js and Express.js — Full Course',
    channel: 'freeCodeCamp',
    category: 'Backend',
    duration: '8h',
    level: 'Intermediate',
    description: 'Build real REST APIs with Node and Express — routing, middleware, MongoDB and deployment.',
  },
  {
    id: 'django-course',
    youtubeId: 'F5mRW0jo-U4',
    title: 'Python Django Web Framework',
    channel: 'freeCodeCamp',
    category: 'Backend',
    duration: '4h',
    level: 'Intermediate',
    description: 'Full Django walkthrough: models, views, templates, admin and a complete project.',
  },
  {
    id: 'sql-course',
    youtubeId: 'HXV3zeQKqGY',
    title: 'SQL Tutorial — Full Database Course',
    channel: 'freeCodeCamp',
    category: 'Databases',
    duration: '4h',
    level: 'Beginner',
    description: 'Relational databases from scratch — queries, joins, keys and database design.',
  },
  {
    id: 'mongodb-course',
    youtubeId: 'c2M-rlkkT5o',
    title: 'MongoDB Full Course',
    channel: 'Bro Code',
    category: 'Databases',
    duration: '1h',
    level: 'Beginner',
    description: 'Documents, collections, CRUD and aggregation — NoSQL fundamentals fast.',
  },
  {
    id: 'docker-course',
    youtubeId: 'fqMOX6JJhGo',
    title: 'Docker Tutorial for Beginners',
    channel: 'freeCodeCamp',
    category: 'DevOps',
    duration: '2h',
    level: 'Beginner',
    description: 'Containers explained properly — images, volumes, networks and docker-compose.',
  },
  {
    id: 'git-course',
    youtubeId: 'RGOj5yH7evk',
    title: 'Git and GitHub for Beginners',
    channel: 'freeCodeCamp',
    category: 'DevOps',
    duration: '1h',
    level: 'Beginner',
    description: 'Version control every developer must know — commits, branches, merges and pull requests.',
  },
  {
    id: 'ml-course',
    youtubeId: 'i_LwzRVP7bg',
    title: 'Machine Learning for Everybody',
    channel: 'freeCodeCamp',
    category: 'Data & AI',
    duration: '4h',
    level: 'Intermediate',
    description: 'A practical, code-first introduction to machine learning with Python.',
  },
  {
    id: 'data-analysis',
    youtubeId: 'r-uOLxNrNk8',
    title: 'Data Analysis with Python',
    channel: 'freeCodeCamp',
    category: 'Data & AI',
    duration: '10h',
    level: 'Intermediate',
    description: 'NumPy, pandas, visualization and real datasets — the full data analysis toolkit.',
  },
  {
    id: 'flutter-course',
    youtubeId: 'VPvVD8t02U8',
    title: 'Flutter Course for Beginners',
    channel: 'freeCodeCamp',
    category: 'Mobile',
    duration: '37h',
    level: 'Beginner',
    description: 'A complete journey to building cross-platform mobile apps with Flutter and Dart.',
  },
  {
    id: 'coding-interview',
    youtubeId: '8hly31xKli0',
    title: 'Algorithms and Data Structures Crash Course',
    channel: 'freeCodeCamp',
    category: 'Career',
    duration: '5h',
    level: 'Intermediate',
    description: 'The data structures and algorithms you need for technical interviews.',
  },
];
