import { Program, LearningMode } from './types';

export const PROGRAMS: Program[] = [
  // ── FULL / LIVE MENTORSHIP PROGRAMS ────────────────────────────
  {
    id: 'fullstack',
    title: 'Full Stack Web Development',
    shortTitle: 'Web Development',
    type: 'full',
    emoji: '🌐',
    duration: '6 months',
    level: 'Beginner → Advanced',
    priceXAF: 320000,
    monthlyXAF: 55000,
    registrationFee: 5000,
    badge: 'Most Popular',
    description:
      'The complete journey from zero to full-stack web developer. Master frontend and backend to build complete, deployable web applications.',
    technologies: ['HTML5', 'CSS3', 'JavaScript', 'React', 'Next.js', 'Node.js', 'Express', 'MongoDB', 'PostgreSQL', 'REST APIs', 'Git & GitHub', 'Deployment'],
    highlights: [
      'Build 5+ real-world projects for your portfolio',
      'Frontend design + backend logic + databases',
      'Authentication, APIs, and deployment covered',
      'Go from zero to job-ready developer',
      'Weekly live Q&A sessions included',
    ],
    accentColor: '#3B82F6',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg',
  },
  {
    id: 'mern',
    title: 'MERN with Next.js Development',
    shortTitle: 'MERN + Next.js',
    type: 'full',
    emoji: '⚛️',
    duration: '4 months',
    level: 'Intermediate',
    priceXAF: 240000,
    monthlyXAF: 60000,
    registrationFee: 5000,
    description:
      'Master the most in-demand JavaScript full-stack combination: MongoDB, Express, React, Next.js, and Node.js. Build modern, scalable apps.',
    technologies: ['React', 'Next.js', 'Node.js', 'Express.js', 'MongoDB', 'Mongoose', 'JWT Auth', 'Redux/Context', 'REST APIs', 'Deployment'],
    highlights: [
      'Industry-standard MERN with Next.js stack',
      'Real-time & interactive applications',
      'Full authentication systems (JWT)',
      'State management with Redux',
      '3+ production-quality projects',
    ],
    accentColor: '#61DAFB',
    logoUrl: '/icons/nextjs.png',
  },
  {
    id: 'pern',
    title: 'PERN with Next.js Development',
    shortTitle: 'PERN + Next.js',
    type: 'full',
    emoji: '🐘',
    duration: '4 months',
    level: 'Intermediate',
    priceXAF: 240000,
    monthlyXAF: 60000,
    registrationFee: 5000,
    description:
      'Build data-driven, enterprise-grade applications with PostgreSQL, Express, React, Next.js, and Node.js. Master relational databases.',
    technologies: ['React', 'Next.js', 'Node.js', 'Express.js', 'PostgreSQL', 'Prisma / Sequelize', 'JWT Auth', 'SQL', 'REST APIs', 'Deployment'],
    highlights: [
      'Relational database design & mastery',
      'Advanced SQL queries & optimization',
      'Enterprise architecture patterns',
      'Data modeling from scratch',
      '3+ production projects',
    ],
    accentColor: '#336791',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg',
  },
  {
    id: 'data-analysis',
    title: 'Data Analysis & Visualization',
    shortTitle: 'Data Analysis',
    type: 'full',
    emoji: '📊',
    duration: '5 months',
    level: 'Beginner → Intermediate',
    priceXAF: 280000,
    monthlyXAF: 58000,
    registrationFee: 5000,
    badge: 'In Demand',
    description:
      'Turn raw data into powerful insights. Master Python analytics, SQL querying, and interactive dashboards used by top companies worldwide.',
    technologies: ['Python', 'Pandas', 'NumPy', 'Matplotlib', 'Seaborn', 'SQL', 'Excel', 'Power BI', 'Statistics'],
    highlights: [
      'Analyze real-world datasets from day one',
      'Build interactive dashboards and visualizations',
      'SQL querying for business intelligence',
      'Statistical thinking and hypothesis testing',
      '4+ portfolio data projects',
    ],
    accentColor: '#F59E0B',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
  },
  {
    id: 'django',
    title: 'Django Web Development',
    shortTitle: 'Django',
    type: 'full',
    emoji: '🟢',
    duration: '3 months',
    level: 'Intermediate',
    priceXAF: 180000,
    monthlyXAF: 60000,
    registrationFee: 5000,
    description:
      "Build robust, secure web applications with Python's most powerful framework. Perfect for APIs, admin systems, and scalable backends.",
    technologies: ['Python', 'Django', 'Django REST Framework', 'PostgreSQL', 'HTML/CSS templates', 'Auth & Permissions', 'Celery basics', 'Deployment'],
    highlights: [
      'Python-powered web development',
      'Full REST API development',
      'Django Admin panel mastery',
      'Built-in security best practices',
      '2+ full-featured projects',
    ],
    accentColor: '#0C4B33',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg',
  },
  {
    id: 'python',
    title: 'Python Programming',
    shortTitle: 'Python',
    type: 'full',
    emoji: '🐍',
    duration: '3 months',
    level: 'Beginner → Intermediate',
    priceXAF: 150000,
    monthlyXAF: 50000,
    registrationFee: 5000,
    description:
      "Master Python from the very beginning to advanced concepts. The most beginner-friendly language — and a gateway to web dev, automation, and AI.",
    technologies: ['Python syntax', 'OOP', 'File I/O', 'APIs & Requests', 'Standard library', 'Data structures', 'Algorithms', 'Scripting & Automation'],
    highlights: [
      'Start from absolute zero',
      'Object-oriented programming deep dive',
      'Working with external APIs',
      'Automation & scripting projects',
      'Solid foundation for AI/ML paths',
    ],
    accentColor: '#3776AB',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
  },
  {
    id: 'javascript',
    title: 'JavaScript Mastery',
    shortTitle: 'JavaScript',
    type: 'full',
    emoji: '✨',
    duration: '3 months',
    level: 'Beginner → Advanced',
    priceXAF: 150000,
    monthlyXAF: 50000,
    registrationFee: 5000,
    description:
      'Deep-dive into the language that powers the entire web. From fundamentals to advanced async patterns, closures, and modern ES6+.',
    technologies: ['ES6+', 'DOM manipulation', 'Async / Await', 'Promises', 'Closures', 'Modules', 'Fetch API', 'Node.js intro', 'Browser APIs'],
    highlights: [
      'Modern JavaScript (ES2024)',
      'Async programming mastery',
      'Browser & Node.js environments',
      'Interview-ready problem solving',
      'Mini projects with every module',
    ],
    accentColor: '#F7DF1E',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
  },
  {
    id: 'flutter-mobile-design',
    title: 'Full Stack Mobile Development (Flutter)',
    shortTitle: 'Mobile Dev (Flutter)',
    type: 'full',
    emoji: '📱',
    duration: '4 months',
    level: 'Beginner → Intermediate',
    priceXAF: 220000,
    monthlyXAF: 55000,
    registrationFee: 5000,
    badge: 'Mobile Focus',
    description:
      'Build full-stack cross-platform mobile apps with Flutter. Learn UI architecture, backend API integration, responsive layouts, and production-ready design systems.',
    technologies: ['Flutter', 'Dart', 'Material 3', 'Adaptive Layouts', 'Animations', 'State Management', 'REST APIs', 'Firebase basics', 'Figma handoff'],
    highlights: [
      'Cross-platform UI workflows for Android and iOS',
      'Design systems and reusable component architecture',
      'Fluid transitions and micro-interactions',
      'End-to-end mobile UI portfolio projects',
      'Mentored design critiques and iteration cycles',
    ],
    accentColor: '#02569B',
    logoUrl: '/icons/flutter.png',
  },
  {
    id: 'react-native-mobile-design',
    title: 'Full Stack Mobile Development (React Native)',
    shortTitle: 'Mobile Dev (React Native)',
    type: 'full',
    emoji: '🧩',
    duration: '4 months',
    level: 'Intermediate',
    priceXAF: 240000,
    monthlyXAF: 60000,
    registrationFee: 5000,
    badge: 'App Builder',
    description:
      'Build full-stack mobile apps with React Native while mastering UX patterns, navigation systems, backend API integration, and scalable UI code for high-performance products.',
    technologies: ['React Native', 'TypeScript', 'Expo', 'Navigation', 'UI Libraries', 'Animations', 'REST APIs', 'Testing basics'],
    highlights: [
      'Reusable mobile components and scalable architecture',
      'Native-like UX patterns and screen transitions',
      'API-driven app interfaces with offline-ready flows',
      'Publishing workflow for Android and iOS',
      'Production-style capstone application',
    ],
    accentColor: '#61DAFB',
    logoUrl: '/icons/react-native.png',
  },

  {
    id: 'cybersecurity',
    title: 'Cybersecurity Fundamentals',
    shortTitle: 'Cybersecurity',
    type: 'full',
    emoji: '🛡️',
    duration: '4 months',
    level: 'Beginner → Intermediate',
    priceXAF: 200000,
    monthlyXAF: 50000,
    registrationFee: 5000,
    description:
      'Master ethical hacking, network security, and digital defense. Learn to think like an attacker so you can defend like a pro. Aligned with EC-Council standards.',
    technologies: ['Network Security', 'Linux', 'Kali Linux', 'Wireshark', 'OWASP Top 10', 'Cryptography', 'Firewalls & VPNs', 'Social Engineering', 'Penetration Testing basics'],
    highlights: [
      'Ethical hacking & penetration testing fundamentals',
      'Network security, firewalls, and intrusion detection',
      'OWASP Top 10 web application vulnerabilities',
      'Hands-on labs using Kali Linux',
      'Intellex Certificate of Completion',
    ],
    accentColor: '#6D28D9',
    logoUrl: 'https://www.globaledulink.co.uk/wp-content/uploads/2020/03/2EC-Council-logo.png',
  },
  {
    id: 'cybersecurity-ceh',
    title: 'Cybersecurity + CEH Certification Prep',
    shortTitle: 'CEH Prep',
    type: 'full',
    emoji: '🏆',
    duration: '5 months',
    level: 'Intermediate',
    priceXAF: 380000,
    monthlyXAF: 75000,
    registrationFee: 5000,
    badge: 'EC-Council',
    description:
      'Full cybersecurity training + structured preparation for the EC-Council Certified Ethical Hacker (CEH) exam. Covers all 20 CEH knowledge domains. EC-Council exam voucher purchased separately through ec-council.org.',
    technologies: ['CEH Syllabus', 'Ethical Hacking', 'Network Security', 'Kali Linux', 'Metasploit', 'Web App Hacking', 'Cryptography', 'IDS & Firewalls', 'Cloud Security', 'Social Engineering'],
    highlights: [
      'Full EC-Council CEH exam preparation (all 20 domains)',
      'Practice exams, mock tests & exam strategy',
      'Official EC-Council courseware alignment',
      'Real-world attack simulation labs',
      'Exam voucher guidance & registration support',
    ],
    accentColor: '#DC2626',
    logoUrl: 'https://www.globaledulink.co.uk/wp-content/uploads/2020/03/2EC-Council-logo.png',
  },

  // ── PARTIAL / MODULE PROGRAMS ───────────────────────────────────
  {
    id: 'webfundamentals',
    title: 'Web Fundamentals',
    shortTitle: 'Web Fundamentals',
    type: 'partial',
    emoji: '🌍',
    duration: '6 weeks',
    level: 'Absolute Beginner',
    priceXAF: 45000,
    registrationFee: 5000,
    description:
      'Your very first step into web development. Build your first website using HTML, CSS, and basic JavaScript. No experience needed.',
    technologies: ['HTML5', 'CSS3', 'Basic JavaScript', 'Responsive design', 'Git basics'],
    highlights: [
      'No prior experience required',
      'Build a real website from scratch',
      'Responsive layouts for mobile & desktop',
      'Perfect launchpad to any full program',
    ],
    accentColor: '#E34F26',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg',
  },
  {
    id: 'htmlcss',
    title: 'HTML & CSS Essentials',
    shortTitle: 'HTML & CSS',
    type: 'partial',
    emoji: '🎨',
    duration: '4 weeks',
    level: 'Beginner',
    priceXAF: 35000,
    registrationFee: 5000,
    description:
      'Design beautiful, professional websites. Master the visual layer of the web — layouts, animations, and mobile-first design.',
    technologies: ['HTML5 semantic tags', 'CSS3', 'Flexbox', 'CSS Grid', 'Responsive design', 'CSS animations & transitions'],
    highlights: [
      'Pixel-perfect web design',
      'Flexbox & Grid mastery',
      'Mobile-first approach',
      'CSS animations & effects',
    ],
    accentColor: '#1572B6',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg',
  },
  {
    id: 'jsessentials',
    title: 'JavaScript Essentials',
    shortTitle: 'JS Essentials',
    type: 'partial',
    emoji: '⚡',
    duration: '6 weeks',
    level: 'Beginner',
    priceXAF: 45000,
    registrationFee: 5000,
    description:
      'The core JavaScript concepts every developer must have. Learn programming thinking and make your web pages truly interactive.',
    technologies: ['Variables & types', 'Functions', 'Arrays & Objects', 'DOM basics', 'Events', 'Conditionals & loops'],
    highlights: [
      'Programming logic from scratch',
      'Interactive web pages',
      'Strong foundation for any framework',
      'Real mini-project each week',
    ],
    accentColor: '#F7DF1E',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
  },
  {
    id: 'react-basics',
    title: 'React & Next.js Fundamentals',
    shortTitle: 'React + Next.js',
    type: 'partial',
    emoji: '⚛',
    duration: '6 weeks',
    level: 'Intermediate',
    priceXAF: 50000,
    registrationFee: 5000,
    description:
      'Get started with modern React and Next.js. Build dynamic, component-based user interfaces and full web apps with App Router.',
    technologies: ['React', 'Next.js', 'JSX', 'Components', 'Props & State', 'React Hooks', 'App Router', 'Fetching APIs'],
    highlights: [
      'Component-based architecture',
      'React Hooks in depth',
      'Next.js routing and navigation',
      'Building modern web apps',
    ],
    accentColor: '#61DAFB',
    logoUrl: '/icons/nextjs.png',
  },
  {
    id: 'python-basics',
    title: 'Python Basics',
    shortTitle: 'Python Basics',
    type: 'partial',
    emoji: '🐍',
    duration: '4 weeks',
    level: 'Absolute Beginner',
    priceXAF: 35000,
    registrationFee: 5000,
    description:
      'Introduction to programming using Python. Learn the fundamentals of coding in the most beginner-friendly language in the world.',
    technologies: ['Python syntax', 'Variables & types', 'Control flow', 'Functions', 'Lists & dicts', 'Basic OOP'],
    highlights: [
      'No prior experience needed',
      'Think like a programmer',
      'Solve real problems with code',
      'Launchpad to full Python program',
    ],
    accentColor: '#3776AB',
    logoUrl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
  },
];

export const LEARNING_MODES: LearningMode[] = [
  {
    id: 'self-paced',
    label: 'Self-Paced',
    description: 'Learn at your own speed with recorded lessons, available 24/7.',
    icon: 'BookOpen',
  },
  {
    id: 'live',
    label: 'Live Classes',
    description: 'Scheduled real-time sessions with instructors. Ask questions live.',
    icon: 'Video',
  },
  {
    id: 'mentorship',
    label: 'Mentorship',
    description: 'Dedicated 1-on-1 guidance. Your personal dev coach throughout.',
    icon: 'GraduationCap',
  },
  {
    id: 'priority',
    label: 'Priority Access',
    description: 'Fast-track intensive: daily support, priority reviews, and direct access.',
    icon: 'Zap',
  },
];

export const getProgramById = (id: string) =>
  PROGRAMS.find((p) => p.id === id);

export const formatPrice = (xaf: number) =>
  new Intl.NumberFormat('fr-CM', {
    style: 'currency',
    currency: 'XAF',
    minimumFractionDigits: 0,
  }).format(xaf);
