import type { TutorialLesson } from '../types';

export const advancedLessons: TutorialLesson[] = [
  {
    slug: "k8s-operators-overview",
    title: "Operators Overview",
    description: "Extend Kubernetes with controllers.",
    level: "advanced",
    section: "Advanced Workloads",
    order: 49,
    minutes: 16,
    content: [
      {"type":"p","text":"Operators Overview is a core skill in the Kubernetes path on InTelleX. You will learn operators overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Operators Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice operators overview with a small exercise of your own."},
      {"type":"keypoints","items":["Operators Overview is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-crds-overview",
    title: "CRDs Overview",
    description: "Custom resources for your platform.",
    level: "advanced",
    section: "Advanced Workloads",
    order: 50,
    minutes: 16,
    content: [
      {"type":"p","text":"CRDs Overview is a core skill in the Kubernetes path on InTelleX. You will learn crds overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind CRDs Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice crds overview with a small exercise of your own."},
      {"type":"keypoints","items":["CRDs Overview is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-multi-environment-strategy",
    title: "Multi-Environment Strategy",
    description: "dev/stage/prod with namespaces or clusters.",
    level: "advanced",
    section: "Production & Capstone",
    order: 51,
    minutes: 16,
    content: [
      {"type":"p","text":"Multi-Environment Strategy is a core skill in the Kubernetes path on InTelleX. You will learn multi-environment strategy with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Multi-Environment Strategy","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice multi-environment strategy with a small exercise of your own."},
      {"type":"keypoints","items":["Multi-Environment Strategy is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-gitops-preview",
    title: "GitOps Preview",
    description: "Argo CD / Flux conceptual flow.",
    level: "advanced",
    section: "Production & Capstone",
    order: 52,
    minutes: 16,
    content: [
      {"type":"p","text":"GitOps Preview is a core skill in the Kubernetes path on InTelleX. You will learn gitops preview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind GitOps Preview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice gitops preview with a small exercise of your own."},
      {"type":"keypoints","items":["GitOps Preview is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-cost-awareness",
    title: "Cost Awareness",
    description: "Requests, bin packing, and idle waste.",
    level: "advanced",
    section: "Production & Capstone",
    order: 53,
    minutes: 16,
    content: [
      {"type":"p","text":"Cost Awareness is a core skill in the Kubernetes path on InTelleX. You will learn cost awareness with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Cost Awareness","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice cost awareness with a small exercise of your own."},
      {"type":"keypoints","items":["Cost Awareness is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-capstone-full-app-chart",
    title: "Capstone: Full App Chart",
    description: "Deploy web + config + ingress via Helm/Kustomize.",
    level: "advanced",
    section: "Production & Capstone",
    order: 54,
    minutes: 22,
    content: [
      {"type":"p","text":"Capstone: Full App Chart is a core skill in the Kubernetes path on InTelleX. You will learn capstone: full app chart with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Full App Chart","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice capstone: full app chart with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Full App Chart is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-capstone-incident-drill",
    title: "Capstone: Incident Drill",
    description: "Break a deploy and recover with kubectl.",
    level: "advanced",
    section: "Production & Capstone",
    order: 55,
    minutes: 18,
    content: [
      {"type":"p","text":"Capstone: Incident Drill is a core skill in the Kubernetes path on InTelleX. You will learn capstone: incident drill with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Incident Drill","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice capstone: incident drill with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Incident Drill is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-cka-style-review",
    title: "CKA-Style Review",
    description: "Practice debugging and YAML fluency.",
    level: "advanced",
    section: "Production & Capstone",
    order: 56,
    minutes: 16,
    content: [
      {"type":"p","text":"CKA-Style Review is a core skill in the Kubernetes path on InTelleX. You will learn cka-style review with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind CKA-Style Review","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice cka-style review with a small exercise of your own."},
      {"type":"keypoints","items":["CKA-Style Review is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-next-steps",
    title: "Next Steps",
    description: "Service mesh, policy engines, platform engineering.",
    level: "advanced",
    section: "Production & Capstone",
    order: 57,
    minutes: 16,
    content: [
      {"type":"p","text":"Next Steps is a core skill in the Kubernetes path on InTelleX. You will learn next steps with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Next Steps","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice next steps with a small exercise of your own."},
      {"type":"keypoints","items":["Next Steps is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-kubernetes-portfolio-tips",
    title: "Kubernetes Portfolio Tips",
    description: "Document architectures and runbooks.",
    level: "advanced",
    section: "Production & Capstone",
    order: 58,
    minutes: 16,
    content: [
      {"type":"p","text":"Kubernetes Portfolio Tips is a core skill in the Kubernetes path on InTelleX. You will learn kubernetes portfolio tips with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Kubernetes Portfolio Tips","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice kubernetes portfolio tips with a small exercise of your own."},
      {"type":"keypoints","items":["Kubernetes Portfolio Tips is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-final-challenge",
    title: "Final Challenge",
    description: "Design a 3-tier app deployment for Kubernetes.",
    level: "advanced",
    section: "Production & Capstone",
    order: 59,
    minutes: 16,
    content: [
      {"type":"p","text":"Final Challenge is a core skill in the Kubernetes path on InTelleX. You will learn final challenge with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Final Challenge","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice final challenge with a small exercise of your own."},
      {"type":"keypoints","items":["Final Challenge is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-glossary-drill",
    title: "Glossary Drill",
    description: "Pod, Node, Control Plane, CNI, CSI, RBAC.",
    level: "advanced",
    section: "Production & Capstone",
    order: 60,
    minutes: 16,
    content: [
      {"type":"p","text":"Glossary Drill is a core skill in the Kubernetes path on InTelleX. You will learn glossary drill with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Glossary Drill","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice glossary drill with a small exercise of your own."},
      {"type":"keypoints","items":["Glossary Drill is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-extra-61",
    title: "Practice Lab 61",
    description: "Hands-on practice lab consolidating earlier k8s skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 61,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 61 is a core skill in the Kubernetes path on InTelleX. You will learn practice lab 61 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 61","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 61 is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-extra-62",
    title: "Practice Lab 62",
    description: "Hands-on practice lab consolidating earlier k8s skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 62,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 62 is a core skill in the Kubernetes path on InTelleX. You will learn practice lab 62 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 62","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 62 is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-extra-63",
    title: "Practice Lab 63",
    description: "Hands-on practice lab consolidating earlier k8s skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 63,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 63 is a core skill in the Kubernetes path on InTelleX. You will learn practice lab 63 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 63","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 63 is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-extra-64",
    title: "Practice Lab 64",
    description: "Hands-on practice lab consolidating earlier k8s skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 64,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 64 is a core skill in the Kubernetes path on InTelleX. You will learn practice lab 64 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 64","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 64 is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-extra-65",
    title: "Practice Lab 65",
    description: "Hands-on practice lab consolidating earlier k8s skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 65,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 65 is a core skill in the Kubernetes path on InTelleX. You will learn practice lab 65 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 65","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 65 is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
