import type { TutorialLesson } from '../types';

export const beginnerLessons: TutorialLesson[] = [
  {
    slug: "k8s-welcome-to-kubernetes",
    title: "Welcome to Kubernetes",
    description: "Containers orchestration at scale.",
    level: "beginner",
    section: "Getting Started",
    order: 1,
    minutes: 11,
    content: [
      {"type":"p","text":"Welcome to Kubernetes is a core skill in the Kubernetes path on InTelleX. Kubernetes schedules containers across machines with declarative desired state."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Welcome to Kubernetes","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice welcome to kubernetes with a small exercise of your own."},
      {"type":"keypoints","items":["Welcome to Kubernetes is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-containers-recap",
    title: "Containers Recap",
    description: "Images, containers, and why orchestration is needed.",
    level: "beginner",
    section: "Getting Started",
    order: 2,
    minutes: 11,
    content: [
      {"type":"p","text":"Containers Recap is a core skill in the Kubernetes path on InTelleX. You will learn containers recap with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Containers Recap","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice containers recap with a small exercise of your own."},
      {"type":"keypoints","items":["Containers Recap is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-cluster-architecture",
    title: "Cluster Architecture",
    description: "Control plane, kubelet, kube-proxy, etcd.",
    level: "beginner",
    section: "Getting Started",
    order: 3,
    minutes: 11,
    content: [
      {"type":"p","text":"Cluster Architecture is a core skill in the Kubernetes path on InTelleX. You will learn cluster architecture with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Cluster Architecture","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice cluster architecture with a small exercise of your own."},
      {"type":"keypoints","items":["Cluster Architecture is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-install-kubectl",
    title: "Install kubectl",
    description: "Talk to clusters from your laptop.",
    level: "beginner",
    section: "Getting Started",
    order: 4,
    minutes: 11,
    content: [
      {"type":"p","text":"Install kubectl is a core skill in the Kubernetes path on InTelleX. You will learn install kubectl with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Install kubectl","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"kubectl version --client\nkubectl config get-contexts","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice install kubectl with a small exercise of your own."},
      {"type":"keypoints","items":["Install kubectl is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-local-cluster-options",
    title: "Local Cluster Options",
    description: "kind, minikube, and k3d overview.",
    level: "beginner",
    section: "Getting Started",
    order: 5,
    minutes: 11,
    content: [
      {"type":"p","text":"Local Cluster Options is a core skill in the Kubernetes path on InTelleX. You will learn local cluster options with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Local Cluster Options","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice local cluster options with a small exercise of your own."},
      {"type":"keypoints","items":["Local Cluster Options is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-pods",
    title: "Pods",
    description: "The smallest deployable unit.",
    level: "beginner",
    section: "Workloads",
    order: 6,
    minutes: 11,
    content: [
      {"type":"p","text":"Pods is a core skill in the Kubernetes path on InTelleX. You will learn pods with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Pods","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"apiVersion: v1\nkind: Pod\nmetadata:\n  name: hello\nspec:\n  containers:\n    - name: web\n      image: nginx","title":"Example","language":"yaml"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice pods with a small exercise of your own."},
      {"type":"keypoints","items":["Pods is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-deployments",
    title: "Deployments",
    description: "Declare replicas and rolling updates.",
    level: "beginner",
    section: "Workloads",
    order: 7,
    minutes: 11,
    content: [
      {"type":"p","text":"Deployments is a core skill in the Kubernetes path on InTelleX. You will learn deployments with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Deployments","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice deployments with a small exercise of your own."},
      {"type":"keypoints","items":["Deployments is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-replicasets",
    title: "ReplicaSets",
    description: "How Deployments keep pods alive.",
    level: "beginner",
    section: "Workloads",
    order: 8,
    minutes: 11,
    content: [
      {"type":"p","text":"ReplicaSets is a core skill in the Kubernetes path on InTelleX. You will learn replicasets with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind ReplicaSets","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice replicasets with a small exercise of your own."},
      {"type":"keypoints","items":["ReplicaSets is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-services",
    title: "Services",
    description: "Stable networking to pods.",
    level: "beginner",
    section: "Workloads",
    order: 9,
    minutes: 11,
    content: [
      {"type":"p","text":"Services is a core skill in the Kubernetes path on InTelleX. You will learn services with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Services","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"apiVersion: v1\nkind: Service\nmetadata:\n  name: web\nspec:\n  selector:\n    app: web\n  ports:\n    - port: 80","title":"Example","language":"yaml"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice services with a small exercise of your own."},
      {"type":"keypoints","items":["Services is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-labels-selectors",
    title: "Labels & Selectors",
    description: "Organize and target objects.",
    level: "beginner",
    section: "Workloads",
    order: 10,
    minutes: 11,
    content: [
      {"type":"p","text":"Labels & Selectors is a core skill in the Kubernetes path on InTelleX. You will learn labels & selectors with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Labels & Selectors","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice labels & selectors with a small exercise of your own."},
      {"type":"keypoints","items":["Labels & Selectors is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-kubectl-get-describe",
    title: "kubectl get/describe",
    description: "Inspect cluster state.",
    level: "beginner",
    section: "kubectl Daily Driver",
    order: 11,
    minutes: 11,
    content: [
      {"type":"p","text":"kubectl get/describe is a core skill in the Kubernetes path on InTelleX. You will learn kubectl get/describe with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind kubectl get/describe","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice kubectl get/describe with a small exercise of your own."},
      {"type":"keypoints","items":["kubectl get/describe is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-kubectl-logs-exec",
    title: "kubectl logs & exec",
    description: "Debug running containers.",
    level: "beginner",
    section: "kubectl Daily Driver",
    order: 12,
    minutes: 11,
    content: [
      {"type":"p","text":"kubectl logs & exec is a core skill in the Kubernetes path on InTelleX. You will learn kubectl logs & exec with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind kubectl logs & exec","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice kubectl logs & exec with a small exercise of your own."},
      {"type":"keypoints","items":["kubectl logs & exec is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-apply-diff",
    title: "Apply & Diff",
    description: "Declarative workflows with apply.",
    level: "beginner",
    section: "kubectl Daily Driver",
    order: 13,
    minutes: 11,
    content: [
      {"type":"p","text":"Apply & Diff is a core skill in the Kubernetes path on InTelleX. You will learn apply & diff with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Apply & Diff","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice apply & diff with a small exercise of your own."},
      {"type":"keypoints","items":["Apply & Diff is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-namespaces",
    title: "Namespaces",
    description: "Isolate environments in one cluster.",
    level: "beginner",
    section: "kubectl Daily Driver",
    order: 14,
    minutes: 11,
    content: [
      {"type":"p","text":"Namespaces is a core skill in the Kubernetes path on InTelleX. You will learn namespaces with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Namespaces","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice namespaces with a small exercise of your own."},
      {"type":"keypoints","items":["Namespaces is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-context-kubeconfig",
    title: "Context & kubeconfig",
    description: "Switch clusters safely.",
    level: "beginner",
    section: "kubectl Daily Driver",
    order: 15,
    minutes: 11,
    content: [
      {"type":"p","text":"Context & kubeconfig is a core skill in the Kubernetes path on InTelleX. You will learn context & kubeconfig with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Context & kubeconfig","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice context & kubeconfig with a small exercise of your own."},
      {"type":"keypoints","items":["Context & kubeconfig is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-configmaps",
    title: "ConfigMaps",
    description: "Inject non-secret config.",
    level: "beginner",
    section: "Configuration",
    order: 16,
    minutes: 11,
    content: [
      {"type":"p","text":"ConfigMaps is a core skill in the Kubernetes path on InTelleX. You will learn configmaps with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind ConfigMaps","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice configmaps with a small exercise of your own."},
      {"type":"keypoints","items":["ConfigMaps is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-secrets",
    title: "Secrets",
    description: "Handle sensitive values carefully.",
    level: "beginner",
    section: "Configuration",
    order: 17,
    minutes: 11,
    content: [
      {"type":"p","text":"Secrets is a core skill in the Kubernetes path on InTelleX. You will learn secrets with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Secrets","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice secrets with a small exercise of your own."},
      {"type":"keypoints","items":["Secrets is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-resource-requests-limits",
    title: "Resource Requests & Limits",
    description: "CPU/memory for scheduling and stability.",
    level: "beginner",
    section: "Configuration",
    order: 18,
    minutes: 11,
    content: [
      {"type":"p","text":"Resource Requests & Limits is a core skill in the Kubernetes path on InTelleX. You will learn resource requests & limits with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Resource Requests & Limits","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice resource requests & limits with a small exercise of your own."},
      {"type":"keypoints","items":["Resource Requests & Limits is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-probes",
    title: "Probes",
    description: "liveness, readiness, startup probes.",
    level: "beginner",
    section: "Configuration",
    order: 19,
    minutes: 11,
    content: [
      {"type":"p","text":"Probes is a core skill in the Kubernetes path on InTelleX. You will learn probes with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Probes","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice probes with a small exercise of your own."},
      {"type":"keypoints","items":["Probes is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-project-deploy-a-web-app",
    title: "Project: Deploy a Web App",
    description: "Deployment + Service + ConfigMap.",
    level: "beginner",
    section: "Configuration",
    order: 20,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: Deploy a Web App is a core skill in the Kubernetes path on InTelleX. You will learn project: deploy a web app with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Deploy a Web App","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice project: deploy a web app with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Deploy a Web App is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-volumes-overview",
    title: "Volumes Overview",
    description: "Ephemeral vs persistent storage.",
    level: "beginner",
    section: "Storage & State",
    order: 21,
    minutes: 11,
    content: [
      {"type":"p","text":"Volumes Overview is a core skill in the Kubernetes path on InTelleX. You will learn volumes overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Volumes Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice volumes overview with a small exercise of your own."},
      {"type":"keypoints","items":["Volumes Overview is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-persistentvolumeclaims",
    title: "PersistentVolumeClaims",
    description: "Request storage abstractly.",
    level: "beginner",
    section: "Storage & State",
    order: 22,
    minutes: 11,
    content: [
      {"type":"p","text":"PersistentVolumeClaims is a core skill in the Kubernetes path on InTelleX. You will learn persistentvolumeclaims with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind PersistentVolumeClaims","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice persistentvolumeclaims with a small exercise of your own."},
      {"type":"keypoints","items":["PersistentVolumeClaims is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-statefulsets",
    title: "StatefulSets",
    description: "Stable identity for stateful apps.",
    level: "beginner",
    section: "Storage & State",
    order: 23,
    minutes: 11,
    content: [
      {"type":"p","text":"StatefulSets is a core skill in the Kubernetes path on InTelleX. You will learn statefulsets with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind StatefulSets","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice statefulsets with a small exercise of your own."},
      {"type":"keypoints","items":["StatefulSets is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-jobs-cronjobs",
    title: "Jobs & CronJobs",
    description: "Batch and scheduled workloads.",
    level: "beginner",
    section: "Storage & State",
    order: 24,
    minutes: 11,
    content: [
      {"type":"p","text":"Jobs & CronJobs is a core skill in the Kubernetes path on InTelleX. You will learn jobs & cronjobs with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Jobs & CronJobs","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice jobs & cronjobs with a small exercise of your own."},
      {"type":"keypoints","items":["Jobs & CronJobs is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-project-redis-on-k8s",
    title: "Project: Redis on K8s",
    description: "Simple stateful workload sketch.",
    level: "beginner",
    section: "Storage & State",
    order: 25,
    minutes: 16,
    content: [
      {"type":"p","text":"Project: Redis on K8s is a core skill in the Kubernetes path on InTelleX. You will learn project: redis on k8s with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Redis on K8s","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice project: redis on k8s with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Redis on K8s is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
