import type { TutorialLesson } from '../types';

export const intermediateLessons: TutorialLesson[] = [
  {
    slug: "k8s-cluster-networking-model",
    title: "Cluster Networking Model",
    description: "Pod IPs and CNI plugins.",
    level: "intermediate",
    section: "Networking",
    order: 26,
    minutes: 13,
    content: [
      {"type":"p","text":"Cluster Networking Model is a core skill in the Kubernetes path on InTelleX. You will learn cluster networking model with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Cluster Networking Model","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice cluster networking model with a small exercise of your own."},
      {"type":"keypoints","items":["Cluster Networking Model is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-clusterip-nodeport-loadbalancer",
    title: "ClusterIP NodePort LoadBalancer",
    description: "Service types compared.",
    level: "intermediate",
    section: "Networking",
    order: 27,
    minutes: 13,
    content: [
      {"type":"p","text":"ClusterIP NodePort LoadBalancer is a core skill in the Kubernetes path on InTelleX. You will learn clusterip nodeport loadbalancer with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind ClusterIP NodePort LoadBalancer","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice clusterip nodeport loadbalancer with a small exercise of your own."},
      {"type":"keypoints","items":["ClusterIP NodePort LoadBalancer is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-ingress-basics",
    title: "Ingress Basics",
    description: "HTTP routing into the cluster.",
    level: "intermediate",
    section: "Networking",
    order: 28,
    minutes: 13,
    content: [
      {"type":"p","text":"Ingress Basics is a core skill in the Kubernetes path on InTelleX. You will learn ingress basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Ingress Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice ingress basics with a small exercise of your own."},
      {"type":"keypoints","items":["Ingress Basics is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-networkpolicies-intro",
    title: "NetworkPolicies Intro",
    description: "Restrict pod traffic.",
    level: "intermediate",
    section: "Networking",
    order: 29,
    minutes: 13,
    content: [
      {"type":"p","text":"NetworkPolicies Intro is a core skill in the Kubernetes path on InTelleX. You will learn networkpolicies intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind NetworkPolicies Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice networkpolicies intro with a small exercise of your own."},
      {"type":"keypoints","items":["NetworkPolicies Intro is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-dns-in-kubernetes",
    title: "DNS in Kubernetes",
    description: "Service discovery via CoreDNS.",
    level: "intermediate",
    section: "Networking",
    order: 30,
    minutes: 13,
    content: [
      {"type":"p","text":"DNS in Kubernetes is a core skill in the Kubernetes path on InTelleX. You will learn dns in kubernetes with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind DNS in Kubernetes","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice dns in kubernetes with a small exercise of your own."},
      {"type":"keypoints","items":["DNS in Kubernetes is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-rolling-updates",
    title: "Rolling Updates",
    description: "Ship new versions with zero-ish downtime.",
    level: "intermediate",
    section: "Scaling & Updates",
    order: 31,
    minutes: 13,
    content: [
      {"type":"p","text":"Rolling Updates is a core skill in the Kubernetes path on InTelleX. You will learn rolling updates with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Rolling Updates","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice rolling updates with a small exercise of your own."},
      {"type":"keypoints","items":["Rolling Updates is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-rollbacks",
    title: "Rollbacks",
    description: "Undo a bad release quickly.",
    level: "intermediate",
    section: "Scaling & Updates",
    order: 32,
    minutes: 13,
    content: [
      {"type":"p","text":"Rollbacks is a core skill in the Kubernetes path on InTelleX. You will learn rollbacks with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Rollbacks","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice rollbacks with a small exercise of your own."},
      {"type":"keypoints","items":["Rollbacks is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-horizontal-pod-autoscaler",
    title: "Horizontal Pod Autoscaler",
    description: "Scale on CPU/custom metrics.",
    level: "intermediate",
    section: "Scaling & Updates",
    order: 33,
    minutes: 13,
    content: [
      {"type":"p","text":"Horizontal Pod Autoscaler is a core skill in the Kubernetes path on InTelleX. You will learn horizontal pod autoscaler with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Horizontal Pod Autoscaler","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice horizontal pod autoscaler with a small exercise of your own."},
      {"type":"keypoints","items":["Horizontal Pod Autoscaler is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-poddisruptionbudgets",
    title: "PodDisruptionBudgets",
    description: "Protect availability during drains.",
    level: "intermediate",
    section: "Scaling & Updates",
    order: 34,
    minutes: 13,
    content: [
      {"type":"p","text":"PodDisruptionBudgets is a core skill in the Kubernetes path on InTelleX. You will learn poddisruptionbudgets with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind PodDisruptionBudgets","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice poddisruptionbudgets with a small exercise of your own."},
      {"type":"keypoints","items":["PodDisruptionBudgets is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-project-zero-downtime-demo",
    title: "Project: Zero-Downtime Demo",
    description: "Update an app while curling the service.",
    level: "intermediate",
    section: "Scaling & Updates",
    order: 35,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: Zero-Downtime Demo is a core skill in the Kubernetes path on InTelleX. You will learn project: zero-downtime demo with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Zero-Downtime Demo","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice project: zero-downtime demo with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Zero-Downtime Demo is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-events-troubleshooting",
    title: "Events & Troubleshooting",
    description: "CrashLoopBackOff and ImagePullBackOff.",
    level: "intermediate",
    section: "Observability & Ops",
    order: 36,
    minutes: 13,
    content: [
      {"type":"p","text":"Events & Troubleshooting is a core skill in the Kubernetes path on InTelleX. You will learn events & troubleshooting with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Events & Troubleshooting","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice events & troubleshooting with a small exercise of your own."},
      {"type":"keypoints","items":["Events & Troubleshooting is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-metrics-overview",
    title: "Metrics Overview",
    description: "metrics-server and resource usage.",
    level: "intermediate",
    section: "Observability & Ops",
    order: 37,
    minutes: 13,
    content: [
      {"type":"p","text":"Metrics Overview is a core skill in the Kubernetes path on InTelleX. You will learn metrics overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Metrics Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice metrics overview with a small exercise of your own."},
      {"type":"keypoints","items":["Metrics Overview is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-logging-patterns",
    title: "Logging Patterns",
    description: "Stdout logs and aggregators.",
    level: "intermediate",
    section: "Observability & Ops",
    order: 38,
    minutes: 13,
    content: [
      {"type":"p","text":"Logging Patterns is a core skill in the Kubernetes path on InTelleX. You will learn logging patterns with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Logging Patterns","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice logging patterns with a small exercise of your own."},
      {"type":"keypoints","items":["Logging Patterns is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-helm-intro",
    title: "Helm Intro",
    description: "Package Kubernetes apps.",
    level: "intermediate",
    section: "Observability & Ops",
    order: 39,
    minutes: 13,
    content: [
      {"type":"p","text":"Helm Intro is a core skill in the Kubernetes path on InTelleX. You will learn helm intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Helm Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice helm intro with a small exercise of your own."},
      {"type":"keypoints","items":["Helm Intro is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-kustomize-intro",
    title: "Kustomize Intro",
    description: "Overlay manifests per environment.",
    level: "intermediate",
    section: "Observability & Ops",
    order: 40,
    minutes: 13,
    content: [
      {"type":"p","text":"Kustomize Intro is a core skill in the Kubernetes path on InTelleX. You will learn kustomize intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Kustomize Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice kustomize intro with a small exercise of your own."},
      {"type":"keypoints","items":["Kustomize Intro is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-rbac-basics",
    title: "RBAC Basics",
    description: "Roles, ClusterRoles, bindings.",
    level: "intermediate",
    section: "Security",
    order: 41,
    minutes: 13,
    content: [
      {"type":"p","text":"RBAC Basics is a core skill in the Kubernetes path on InTelleX. You will learn rbac basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind RBAC Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice rbac basics with a small exercise of your own."},
      {"type":"keypoints","items":["RBAC Basics is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-serviceaccounts",
    title: "ServiceAccounts",
    description: "Identity for pods.",
    level: "intermediate",
    section: "Security",
    order: 42,
    minutes: 13,
    content: [
      {"type":"p","text":"ServiceAccounts is a core skill in the Kubernetes path on InTelleX. You will learn serviceaccounts with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind ServiceAccounts","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice serviceaccounts with a small exercise of your own."},
      {"type":"keypoints","items":["ServiceAccounts is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-pod-security-context",
    title: "Pod Security Context",
    description: "Run as non-root, read-only FS.",
    level: "intermediate",
    section: "Security",
    order: 43,
    minutes: 13,
    content: [
      {"type":"p","text":"Pod Security Context is a core skill in the Kubernetes path on InTelleX. You will learn pod security context with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Pod Security Context","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice pod security context with a small exercise of your own."},
      {"type":"keypoints","items":["Pod Security Context is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-image-supply-chain",
    title: "Image Supply Chain",
    description: "Tags, digests, scanning.",
    level: "intermediate",
    section: "Security",
    order: 44,
    minutes: 13,
    content: [
      {"type":"p","text":"Image Supply Chain is a core skill in the Kubernetes path on InTelleX. You will learn image supply chain with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Image Supply Chain","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice image supply chain with a small exercise of your own."},
      {"type":"keypoints","items":["Image Supply Chain is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-project-locked-down-deploy",
    title: "Project: Locked-Down Deploy",
    description: "Apply security contexts and probes.",
    level: "intermediate",
    section: "Security",
    order: 45,
    minutes: 16,
    content: [
      {"type":"p","text":"Project: Locked-Down Deploy is a core skill in the Kubernetes path on InTelleX. You will learn project: locked-down deploy with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Locked-Down Deploy","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice project: locked-down deploy with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Locked-Down Deploy is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-daemonsets",
    title: "DaemonSets",
    description: "One pod per node for agents.",
    level: "intermediate",
    section: "Advanced Workloads",
    order: 46,
    minutes: 13,
    content: [
      {"type":"p","text":"DaemonSets is a core skill in the Kubernetes path on InTelleX. You will learn daemonsets with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind DaemonSets","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice daemonsets with a small exercise of your own."},
      {"type":"keypoints","items":["DaemonSets is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-init-containers",
    title: "Init Containers",
    description: "Setup tasks before app starts.",
    level: "intermediate",
    section: "Advanced Workloads",
    order: 47,
    minutes: 13,
    content: [
      {"type":"p","text":"Init Containers is a core skill in the Kubernetes path on InTelleX. You will learn init containers with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Init Containers","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice init containers with a small exercise of your own."},
      {"type":"keypoints","items":["Init Containers is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "k8s-sidecars",
    title: "Sidecars",
    description: "Helper containers in a pod.",
    level: "intermediate",
    section: "Advanced Workloads",
    order: 48,
    minutes: 13,
    content: [
      {"type":"p","text":"Sidecars is a core skill in the Kubernetes path on InTelleX. You will learn sidecars with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Sidecars","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Kubernetes lab folder as you go."},
      {"type":"try","text":"Practice sidecars with a small exercise of your own."},
      {"type":"keypoints","items":["Sidecars is an essential Kubernetes skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
