import type { TutorialLesson } from '../types';

export const advancedLessons: TutorialLesson[] = [
  {
    slug: 'sharepoint-team-sites',
    title: 'SharePoint Basics for Team Sites',
    description: 'Navigate SharePoint team sites for document libraries, news, and team home pages beyond simple OneDrive folders.',
    level: 'advanced',
    section: 'Collaboration and Sites',
    order: 35,
    minutes: 15,
    content: [
      { type: 'p', text: 'SharePoint is the backbone of document storage for Microsoft Teams and many organizations. A team site is a website with document libraries, lists, news, and permissions. NGOs, ministries, and companies in Africa use SharePoint for intranets and project portals.' },
      { type: 'h2', text: 'SharePoint vs OneDrive' },
      {
        type: 'table',
        headers: ['OneDrive', 'SharePoint'],
        rows: [
          ['Personal files', 'Team and org files'],
          ['You control sharing', 'Owners control site permissions'],
          ['Simple folder sync', 'Libraries, metadata, workflows'],
          ['Best for individual work', 'Best for departments and projects'],
        ],
      },
      { type: 'h2', text: 'Explore a team site' },
      { type: 'ol', items: ['Open Teams, select team, Files tab, Open in SharePoint (or visit sharepoint.com).', 'Home: news, quick links, site activity.', 'Documents library: folders and files with version history.', 'Recycle bin: recover deleted files within retention period.', 'Site contents: see all lists and libraries.'] },
      { type: 'h2', text: 'Document library actions' },
      { type: 'ul', items: ['Upload, New Word document, sync library with OneDrive app.', 'Column metadata: add Department or Status column for filtering.', 'Views: save filtered sorts (for example Active contracts only).', 'Check in/out for formal documents if enabled by admin.'] },
      { type: 'note', text: 'SharePoint looks different on web vs Teams but stores the same files. Bookmarks the SharePoint URL for large library management.' },
      { type: 'tip', text: 'Search SharePoint from the top bar across sites you have access to. Faster than browsing nested folders.' },
      { type: 'warning', text: 'Deleting a SharePoint site removes team files for everyone. Only owners should delete sites; members should delete only their own drafts.' },
      { type: 'try', text: 'Open a team site library. Create a folder, upload a file, add a custom column, and save a personal view sorted by modified date.' },
      { type: 'keypoints', items: ['SharePoint hosts team documents behind Teams and org portals.', 'Libraries support metadata, views, and permissions at scale.', 'Sync libraries via OneDrive app for offline access.', 'Use search and views instead of deep folder drilling.'] },
    ],
  },
  {
    slug: 'co-authoring-best-practices',
    title: 'Co-Authoring Best Practices',
    description: 'Collaborate smoothly on Word, Excel, and PowerPoint with multiple editors without conflicts or confusion.',
    level: 'advanced',
    section: 'Collaboration and Sites',
    order: 36,
    minutes: 14,
    content: [
      { type: 'p', text: 'Co-authoring lets several people edit the same file at once in Office online or desktop. Colored cursors show who is where. Done well, it speeds group reports. Done poorly, you overwrite each other or break formatting.' },
      { type: 'h2', text: 'Setup for successful co-authoring' },
      { type: 'ol', items: ['Store file on OneDrive or SharePoint, not email attachments.', 'Share with Edit permission for contributors, View for reviewers.', 'Agree who owns which section before editing.', 'Use Word Heading styles so people can jump to their part.', 'Communicate in Teams chat while editing long documents.'] },
      { type: 'h2', text: 'App-specific tips' },
      {
        type: 'table',
        headers: ['App', 'Best practice', 'Avoid'],
        rows: [
          ['Word', 'Work in different sections; use comments', 'Two people editing same paragraph'],
          ['Excel', 'One person per sheet or use Tables', 'Changing structure while others enter data'],
          ['PowerPoint', 'Assign slides by number upfront', 'Simultaneous redesign of master theme'],
        ],
      },
      { type: 'h2', text: 'Presence and sync indicators' },
      { type: 'p', text: 'Colored flags or initials show active editors. "Saving..." or cloud icon means sync in progress. Wait for sync to finish before closing laptop, especially on unstable internet common in rural areas.' },
      { type: 'h3', text: 'Conflict handling' },
      { type: 'ul', items: ['Excel may show conflict dialog if two edit same cell; choose keep yours or theirs carefully.', 'Word rarely blocks; last save wins on overlapping text. Use Track Changes for formal review.', 'If desktop and web both open, prefer one platform per session.'] },
      { type: 'tip', text: 'For thesis groups, split chapters into separate Word files and merge with master document or use section owners with weekly sync meetings.' },
      { type: 'warning', text: 'Do not co-author on "Downloaded copy" offline for days then upload. You will fork versions. Stay synced or check out formally.' },
      { type: 'try', text: 'Three people edit one Word doc for 10 minutes: each owns one heading section. Note any sync delays and how you communicated.' },
      { type: 'keypoints', items: ['Co-authoring requires cloud storage and Edit permissions.', 'Divide sections or sheets to reduce edit conflicts.', 'Watch sync status before closing devices on slow internet.', 'Use comments and chat alongside live editing.'] },
    ],
  },
  {
    slug: 'version-history-restore',
    title: 'Version History and Restore',
    description: 'Recover previous versions of Office files and undo accidental edits or deletions using version history.',
    level: 'advanced',
    section: 'Collaboration and Sites',
    order: 37,
    minutes: 12,
    content: [
      { type: 'p', text: 'Microsoft 365 saves version history for files in OneDrive and SharePoint. When someone deletes a chapter, saves a bad formula, or ransomware strikes, you can often restore an earlier version without starting over.' },
      { type: 'h2', text: 'Open version history' },
      { type: 'ol', items: ['In Word/Excel/PowerPoint online: File, Info, Version history.', 'In OneDrive web: right-click file, Version history.', 'In SharePoint library: click ... next to file, Version history.', 'See list of versions with editor name and timestamp.', 'Open a version to preview. Restore to make it current (old version saved too).'] },
      { type: 'h2', text: 'Restore deleted files' },
      { type: 'ul', items: ['OneDrive Recycle bin: deleted files kept ~30 days (policy varies).', 'SharePoint site Recycle bin: second-stage admin bin may exist.', 'Select file, Restore. Sync again to desktop if needed.'] },
      {
        type: 'table',
        headers: ['Scenario', 'Action'],
        rows: [
          ['Wrong edit today', 'Version history, restore previous'],
          ['File deleted yesterday', 'Recycle bin restore'],
          ['Need copy without overwriting', 'Download old version as separate file'],
        ],
      },
      { type: 'note', text: 'Version history is not unlimited backup. Major releases should also be exported to PDF or copied to Archive folder monthly for critical work.' },
      { type: 'h3', text: 'Compare versions side by side' },
      { type: 'p', text: 'In Word online version history, open two versions in separate browser tabs to see what changed before restoring. In Excel, note which sheet or formula broke before picking an older snapshot to recover.' },
      { type: 'tip', text: 'Rename file to v2 before major restructuring so history stays readable: "Budget_2026_v2.xlsx".' },
      { type: 'warning', text: 'Restoring overwrites current version. Download current copy first if unsure.' },
      { type: 'try', text: 'Edit a document three times. Open version history and restore the first version. Delete a test file and recover from Recycle bin.' },
      { type: 'keypoints', items: ['Version history lists auto-saved snapshots with editor and time.', 'Restore reverts file; download old version to keep both.', 'Recycle bin recovers deleted files within retention period.', 'Combine version history with naming conventions for safety.'] },
    ],
  },
  {
    slug: 'planner-todo-loop',
    title: 'Planner, To Do, and Loop Overview',
    description: 'Manage tasks with Microsoft Planner and To Do, and collaborate on flexible pages with Loop components.',
    level: 'advanced',
    section: 'Collaboration and Sites',
    order: 38,
    minutes: 14,
    content: [
      { type: 'p', text: 'Microsoft 365 includes lightweight task tools. Planner suits team boards with buckets and charts. To Do is personal daily lists. Loop provides shared canvases and components that sync across Teams and Outlook.' },
      { type: 'h2', text: 'Microsoft Planner' },
      { type: 'ol', items: ['In Teams, add Planner tab to channel or open planner.microsoft.com.', 'Create plan linked to team.', 'Buckets: To Do, Doing, Done (or project phases).', 'Tasks: title, assignee, due date, checklist, attachments.', 'Charts view: progress by status, person, or priority.'] },
      { type: 'h2', text: 'Microsoft To Do' },
      { type: 'ul', items: ['Personal tasks sync from Outlook flagged mail.', 'My Day list for daily focus.', 'Shared lists with family or small group.', 'Mobile app works offline for checking tasks.'] },
      { type: 'h2', text: 'Microsoft Loop (practical awareness)' },
      { type: 'p', text: 'Loop workspaces hold collaborative pages. Loop components embed in Teams chat and Outlook email: shared tables, voting lists, progress trackers that stay in sync. Useful for brainstorming retreat agendas or hackathon task boards.' },
      {
        type: 'table',
        headers: ['Tool', 'Best for', 'Not for'],
        rows: [
          ['Planner', 'Team project with deadlines', 'Long document writing'],
          ['To Do', 'Personal errands and follow-ups', 'Complex Gantt charts'],
          ['Loop', 'Live collaborative lists and notes', 'Formal signed contracts'],
        ],
      },
      { type: 'tip', text: 'Link Planner tasks to Teams channel files so assignees open the right Excel or Word doc in one click.' },
      { type: 'note', text: 'Loop availability depends on tenant settings. If disabled, use OneNote or SharePoint lists as fallback.' },
      { type: 'try', text: 'Create a Planner board with three buckets and five tasks for a group project. Assign dates. Mirror your personal next steps in To Do.' },
      { type: 'keypoints', items: ['Planner manages team tasks in buckets with charts.', 'To Do handles personal and flagged email tasks.', 'Loop offers synced collaborative components in chat and mail.', 'Pick the lightest tool that fits the job.'] },
    ],
  },
  {
    slug: 'power-automate-awareness',
    title: 'Power Automate Awareness',
    description: 'Learn what Power Automate is, when to use it, and walk through one simple flow idea for repetitive Office tasks.',
    level: 'advanced',
    section: 'Automation Awareness',
    order: 39,
    minutes: 13,
    content: [
      { type: 'p', text: 'Power Automate (formerly Flow) connects apps with triggers and actions. When X happens, do Y automatically. Examples: save email attachments to OneDrive, post Teams message when Excel row added, remind manager weekly.' },
      { type: 'h2', text: 'Core concepts' },
      {
        type: 'table',
        headers: ['Term', 'Meaning', 'Example'],
        rows: [
          ['Trigger', 'Starts the flow', 'New email arrives'],
          ['Action', 'What happens next', 'Save attachment'],
          ['Condition', 'If/else branch', 'If subject contains Invoice'],
          ['Connector', 'Link to app', 'Outlook, OneDrive, Teams'],
        ],
      },
      { type: 'h2', text: 'Simple flow idea: save invoice attachments' },
      { type: 'ol', items: ['Go to make.powerautomate.com.', 'Create, Automated cloud flow.', 'Trigger: When a new email arrives (V3), folder Inbox.', 'Condition: Subject contains Invoice.', 'Action: Save attachment to OneDrive folder /Finance/Invoices.', 'Test with a sample email. Turn on flow.'] },
      {
        type: 'code',
        title: 'Expression example (awareness level)',
        language: 'text',
        code: `formatDateTime(utcNow(), 'yyyy-MM-dd')
(Use in file name to stamp saved attachments)

concat('Report_', variables('Dept'), '.xlsx')
(Build dynamic file names from flow variables)`
      },
      { type: 'h2', text: 'When automation helps in African offices' },
      { type: 'ul', items: ['Weekly reminder in Teams for timesheet submission.', 'Copy form responses to SharePoint list automatically.', 'Notify supervisor when shared Excel budget cell exceeds threshold.', 'Reduce manual forwarding of registration emails to a folder.'] },
      { type: 'warning', text: 'Flows need proper permissions and can fail silently if mailbox moves. IT should review flows touching confidential data.' },
      { type: 'note', text: 'This course does not require building production flows. Awareness helps you request automation from IT or learn Power Automate later.' },
      { type: 'tip', text: 'Start with templates in Power Automate gallery before building from scratch.' },
      { type: 'try', text: 'Browse three templates at make.powerautomate.com. Sketch on paper a flow your school or workplace could use (trigger, two actions).' },
      { type: 'keypoints', items: ['Power Automate runs trigger-action workflows across Microsoft 365.', 'Common uses: file routing, notifications, form processing.', 'Expressions customize dynamic values in flows.', 'Get IT approval before automating sensitive data.'] },
    ],
  },
  {
    slug: 'excel-dashboards-lite',
    title: 'Excel Dashboards Lite',
    description: 'Build a simple Excel dashboard with KPIs, charts, slicers, and clean layout for management or project reporting.',
    level: 'advanced',
    section: 'Automation Awareness',
    order: 40,
    minutes: 18,
    content: [
      { type: 'p', text: 'A dashboard is one screen that answers key questions at a glance. NGOs report donor metrics; shops track weekly sales; student leaders show event signups. Excel dashboards combine formulas, pivot tables, charts, and slicers without Power BI.' },
      { type: 'h2', text: 'Dashboard structure' },
      {
        type: 'code',
        title: 'Three-sheet model',
        language: 'text',
        code: `Sheet: Data        (raw rows, hidden or protected)
Sheet: Calculations (SUMIFS, pivot cache)
Sheet: Dashboard    (charts, KPI boxes, slicers only)`
      },
      { type: 'h2', text: 'Build KPI boxes' },
      { type: 'ol', items: ['On Dashboard sheet, merge cells for KPI title area.', 'Reference calculations: =Calculations!B5 for total sales.', 'Format large font, thousands separator, label below.', 'Add sparklines (Insert, Sparklines) for mini trends in one cell.', 'Use conditional formatting icons for red/yellow/green status.'] },
      { type: 'h2', text: 'Charts and slicers' },
      { type: 'ol', items: ['Create pivot table from Data sheet.', 'Insert pivot chart on Dashboard.', 'Add slicer for Region or Month linked to pivot.', 'Align objects on grid; turn off gridlines on dashboard for clean look.', 'Set print area if managers want PDF weekly.'] },
      {
        type: 'table',
        headers: ['Design rule', 'Why'],
        rows: [
          ['One screen, no scroll if possible', 'Executives skim on phones'],
          ['Max 4-6 visuals', 'Prevents clutter'],
          ['Consistent colors with org brand', 'Professional trust'],
          ['Hide formula sheets', 'Reduce accidental breaks'],
        ],
      },
      { type: 'tip', text: 'Refresh pivots before meetings: Data, Refresh All. Pin shortcut on Quick Access Toolbar.' },
      { type: 'note', text: 'For large datasets (100k+ rows), consider Power BI. Lite dashboards suit thousands of rows on typical laptops.' },
      { type: 'try', text: 'Build a dashboard for fictional shop sales: 3 KPIs, 1 pivot chart, 1 slicer. Protect formula sheet.' },
      { type: 'keypoints', items: ['Separate Data, Calculations, and Dashboard sheets.', 'KPI boxes highlight top numbers with clear labels.', 'Pivot charts plus slicers enable interactive filtering.', 'Keep visuals few and refresh data before presenting.'] },
    ],
  },
  {
    slug: 'word-mail-merge',
    title: 'Word Mail Merge',
    description: 'Generate personalized letters, certificates, and labels from one Word template and an Excel recipient list.',
    level: 'advanced',
    section: 'Automation Awareness',
    order: 41,
    minutes: 16,
    content: [
      { type: 'p', text: 'Mail merge combines a Word document with a data source (usually Excel) to produce hundreds of personalized outputs: offer letters, certificates, ID labels, fee notices. Essential for school admins, HR, and event organizers.' },
      { type: 'h2', text: 'Prepare Excel data source' },
      { type: 'ol', items: ['Row 1 headers: FirstName, LastName, Email, Amount, Course (no spaces in headers helps).', 'One row per recipient. No blank rows in middle.', 'Save as MergeData.xlsx on OneDrive.', 'Format phone column as Text to preserve leading zeros.'] },
      { type: 'h2', text: 'Create merge document' },
      { type: 'ol', items: ['Open blank Word document.', 'Mailings tab, Start Mail Merge, Letters (or Labels, Email).', 'Select Recipients, Use an Existing List, browse to Excel file.', 'Click in document. Mailings, Insert Merge Field for each placeholder.', 'Preview Results to check first records.', 'Finish and Merge: Edit Individual Documents or Print.'] },
      {
        type: 'code',
        title: 'Example letter with merge fields',
        language: 'text',
        code: `Dear «FirstName» «LastName»,

Congratulations on completing «Course».
Your certificate fee of «Amount» FCFA is recorded.

Regards,
Training Center`
      },
      { type: 'h2', text: 'Email merge via Outlook' },
      { type: 'p', text: 'Choose Email messages in merge type. Map merge field to Subject if needed. Outlook sends individual emails (not one BCC blast). Respect anti-spam policies and consent.' },
      { type: 'warning', text: 'Test merge with 2-row Excel first. Wrong field in amount field has embarrassed many offices.' },
      { type: 'tip', text: 'Save merged output as PDF per person if you need archival copies with names in filename using a macro or manual split for small batches.' },
      { type: 'try', text: 'Merge 5-row Excel list into invitation letters. Preview all records before printing to PDF.' },
      { type: 'keypoints', items: ['Excel holds recipient data; Word holds the template.', 'Insert Merge Fields where personalization goes.', 'Preview Results before Finish and Merge.', 'Email merge sends individualized Outlook messages.'] },
    ],
  },
  {
    slug: 'accessibility-deep-dive',
    title: 'Accessibility Deep Dive',
    description: 'Use the Accessibility Checker and inclusive design practices so Office documents work for people with disabilities.',
    level: 'advanced',
    section: 'Professional Standards',
    order: 42,
    minutes: 15,
    content: [
      { type: 'p', text: 'Accessible documents work for screen reader users, people with low vision, color blindness, and motor difficulties. Many African public sector and international NGO contracts now expect accessible deliverables.' },
      { type: 'h2', text: 'Run Accessibility Checker' },
      { type: 'ol', items: ['Word/Excel/PowerPoint: Review, Check Accessibility.', 'Fix errors (red) first: missing alt text, no header row in table.', 'Review warnings (yellow): contrast, slide reading order.', 'Use Reading Order pane in PowerPoint for logical sequence.', 'Re-run checker before publishing PDF.'] },
      { type: 'h2', text: 'Word and PDF accessibility' },
      {
        type: 'table',
        headers: ['Issue', 'Fix'],
        rows: [
          ['No heading structure', 'Apply Heading 1, 2, 3 styles'],
          ['Images without alt text', 'Meaningful description or mark decorative'],
          ['Color only meaning', 'Add text labels or icons'],
          ['Tables for layout', 'Use real tables with header row'],
        ],
      },
      { type: 'h2', text: 'PowerPoint accessibility' },
      { type: 'ul', items: ['Unique slide titles on every slide.', 'Visible focus order matches reading order.', 'Captions or transcript for embedded video.', 'Avoid text in images; type real text when possible.', 'High contrast theme; test grayscale view.'] },
      { type: 'h2', text: 'Excel accessibility' },
      { type: 'p', text: 'Name sheets clearly. Define table headers. Avoid merged cells in data ranges. Add cell comments for complex formulas if shared widely.' },
      { type: 'note', text: 'Export to accessible PDF: File, Save As PDF, Options, Document structure tags for accessibility if available.' },
      { type: 'tip', text: 'Simulate experience: Word, Read Aloud (Review tab) listens to your document flow.' },
      { type: 'try', text: 'Take an old presentation. Fix all Accessibility Checker errors. Document three improvements in a short note.' },
      { type: 'keypoints', items: ['Accessibility Checker finds fixable barriers in Office files.', 'Structure with headings, alt text, and table headers.', 'PowerPoint needs slide titles and logical reading order.', 'Accessible design helps all users, not only disabilities.'] },
    ],
  },
  {
    slug: 'security-phishing-sharing',
    title: 'Security: Phishing, Sharing Risks, and Sensitivity Labels',
    description: 'Recognize phishing, manage sharing risks, and understand sensitivity labels for protecting organizational data.',
    level: 'advanced',
    section: 'Professional Standards',
    order: 43,
    minutes: 14,
    content: [
      { type: 'p', text: 'Microsoft 365 holds email, files, and chats attackers want. Phishing steals passwords. Overshared links leak contracts. Sensitivity labels (when enabled) classify and protect documents. Everyone using 365 in African banks, telcos, and universities should know these risks.' },
      { type: 'h2', text: 'Recognize phishing' },
      { type: 'ul', items: ['Urgent language: "Your account will close in 1 hour".', 'Sender mismatch: display name Microsoft but email random domain.', 'Links hover to strange URLs not microsoft.com.', 'Attachments you did not expect (.html, .zip invoice).', 'Requests for password, MFA code, or payment to new bank account.'] },
      { type: 'h2', text: 'Sharing link risks' },
      {
        type: 'table',
        headers: ['Risk', 'Mitigation'],
        rows: [
          ['Anyone link forwarded publicly', 'Use Specific people, expiration'],
          ['Edit link to whole folder', 'Share single file View only'],
          ['Guest stays after project ends', 'Remove access in Manage Access'],
          ['Screenshot of confidential Teams chat', 'Train staff; use watermarks on sensitive PDFs'],
        ],
      },
      { type: 'h2', text: 'Sensitivity labels (awareness)' },
      { type: 'p', text: 'Organizations apply labels like Public, Internal, Confidential. Labels may encrypt file, block external share, or add watermark. You see label dropdown on ribbon if admin enabled. Do not downgrade label to share externally without approval.' },
      { type: 'h3', text: 'Report and respond' },
      { type: 'ol', items: ['Report phishing in Outlook: Report message.', 'If you clicked link, change password and notify IT immediately.', 'If you shared wrong file, revoke link and audit access logs with admin.'] },
      { type: 'warning', text: 'WhatsApp "IT support" asking for your Microsoft login is social engineering. Real IT uses ticket systems, not personal chats for passwords.' },
      { type: 'tip', text: 'Enable security defaults or MFA on all accounts. Check recent sign-ins at account.microsoft.com security activity.' },
      { type: 'try', text: 'Review three sample suspicious emails (search "phishing examples"). List red flags. Audit one shared file and tighten permissions.' },
      { type: 'keypoints', items: ['Phishing uses urgency, fake senders, and credential theft.', 'Tighten sharing: specific people, expiration, least privilege.', 'Sensitivity labels enforce org classification when enabled.', 'Report suspicious mail and rotate passwords if compromised.'] },
    ],
  },
  {
    slug: 'choosing-right-app',
    title: 'Choosing the Right App for the Job',
    description: 'Use a decision framework to pick Word, Excel, PowerPoint, Teams, OneNote, Forms, or SharePoint for each task.',
    level: 'advanced',
    section: 'Professional Standards',
    order: 44,
    minutes: 12,
    content: [
      { type: 'p', text: 'Microsoft 365 has overlapping tools. New users open Excel for lists that belong in Lists, or email huge attachments instead of sharing OneDrive links. Choosing the right app saves time and reduces errors.' },
      { type: 'h2', text: 'Decision table' },
      {
        type: 'table',
        headers: ['Need', 'Best app', 'Why not another'],
        rows: [
          ['Write formal report', 'Word', 'Excel is not for long prose'],
          ['Calculate budget', 'Excel', 'Word tables lack formulas'],
          ['Present to audience', 'PowerPoint', 'Word is not slide-based'],
          ['Team chat and meetings', 'Teams', 'Outlook is async email'],
          ['Personal quick notes', 'OneNote', 'Word is heavy per page'],
          ['Collect survey responses', 'Forms', 'Excel manual entry is slow'],
          ['Team file library', 'SharePoint/Teams Files', 'Email attachments fork versions'],
          ['Personal file backup', 'OneDrive', 'SharePoint is team-scoped'],
          ['Task board for group', 'Planner', 'Excel lacks assignee workflow'],
        ],
      },
      { type: 'h2', text: 'Scenario walkthrough' },
      { type: 'p', text: 'Student association plans a charity event. Forms for registration. Excel for budget and pivot on ticket sales. Word for sponsor letter mail merge. PowerPoint for sponsor pitch. Teams channel for committee chat and Files. Planner for task owners. OneNote for meeting minutes.' },
      { type: 'h3', text: 'Questions before you start' },
      { type: 'ol', items: ['Is it narrative, numbers, slides, or conversation?', 'Solo or team? Internal or external?', 'Need version control and co-authoring?', 'Need automation or approval workflow later?'] },
      { type: 'note', text: 'When two apps fit, pick the one your team already uses. Consistency beats theoretical perfection.' },
      { type: 'h3', text: 'Anti-patterns to avoid' },
      { type: 'ul', items: ['Long policy documents emailed as 15 separate attachments instead of one SharePoint folder.', 'Meeting notes trapped in chat scroll instead of OneNote or Word.', 'Sensitive lists stored in Excel on USB with no password or sharing control.'] },
      { type: 'tip', text: 'Pin this decision table in your team Teams channel Resources tab.' },
      { type: 'try', text: 'For five real tasks you do this month, write the best Microsoft app and one sentence why.' },
      { type: 'keypoints', items: ['Match task type to app strengths.', 'Use cloud location (OneDrive vs SharePoint) based on solo vs team.', 'Combine apps in workflows instead of forcing one tool.', 'Prefer tools your organization already standardized.'] },
    ],
  },
  {
    slug: 'keyboard-shortcuts-productivity',
    title: 'Keyboard Shortcuts Productivity Pack',
    description: 'Master high-impact keyboard shortcuts across Word, Excel, PowerPoint, Outlook, and Teams to work faster.',
    level: 'advanced',
    section: 'Professional Standards',
    order: 45,
    minutes: 13,
    content: [
      { type: 'p', text: 'Shortcuts reduce reliance on slow touchpads in hot climates and crowded labs. Learn a focused set across apps rather than hundreds at once. Most use Ctrl on Windows; Cmd on Mac for the same roles.' },
      { type: 'h2', text: 'Universal shortcuts' },
      {
        type: 'table',
        headers: ['Shortcut', 'Action'],
        rows: [
          ['Ctrl+S', 'Save'],
          ['Ctrl+Z / Ctrl+Y', 'Undo / Redo'],
          ['Ctrl+C / Ctrl+V', 'Copy / Paste'],
          ['Ctrl+F', 'Find'],
          ['Ctrl+P', 'Print'],
          ['Alt+Tab', 'Switch apps'],
        ],
      },
      { type: 'h2', text: 'Word and PowerPoint' },
      {
        type: 'code',
        title: 'Word/PPT shortcuts',
        language: 'text',
        code: `Ctrl+B / I / U     Bold, italic, underline
Ctrl+Enter         Page break (Word)
Ctrl+Shift+C       Copy formatting (Word)
Ctrl+D             Duplicate slide (PPT)
F5                 Start slideshow (PPT)
Ctrl+Shift+>       Increase font size`
      },
      { type: 'h2', text: 'Excel' },
      {
        type: 'code',
        title: 'Excel shortcuts',
        language: 'text',
        code: `Ctrl+T              Create table
Ctrl+Shift+L        Toggle filter
Alt+=               AutoSum
F2                  Edit cell
Ctrl+;              Insert today date
Ctrl+Arrow          Jump to edge of data
Ctrl+\`              Show formulas`
      },
      { type: 'h2', text: 'Outlook and Teams' },
      { type: 'ul', items: ['Ctrl+N: new email or chat (context dependent).', 'Ctrl+Enter: send email.', 'Ctrl+1/2/3: Mail, Calendar, Contacts in Outlook.', 'Ctrl+E: search in Teams.', 'Ctrl+Shift+M: new message in Teams.'] },
      { type: 'tip', text: 'Pick five shortcuts from this lesson. Use only those for one week until muscle memory forms. Add five more next week.' },
      { type: 'note', text: 'Screen readers and alternative keyboards may remap keys. Learn equivalents in accessibility settings if needed.' },
      { type: 'try', text: 'Complete a small task without mouse: new Word doc, bold title, save; Excel sum column; send Outlook email. Time yourself.' },
      { type: 'keypoints', items: ['Learn universal save, undo, find, and switch-app shortcuts first.', 'Excel: F2 edit, Ctrl+T table, Alt+= sum.', 'Outlook/Teams: Ctrl+Enter send, Ctrl+E search.', 'Add shortcuts gradually for lasting habit.'] },
    ],
  },
  {
    slug: 'advanced-capstone-job-pack',
    title: 'Capstone: Student and Job Application Pack',
    description: 'Build a complete portfolio pack: Word CV, Excel budget, PowerPoint pitch, and Outlook/Teams workflow documentation.',
    level: 'advanced',
    section: 'Advanced Capstone',
    order: 46,
    minutes: 30,
    content: [
      { type: 'p', text: 'This capstone simulates preparing for internship or job search using Microsoft 365 end to end. You will produce four linked deliverables plus a workflow writeup showing how you use email and Teams professionally.' },
      { type: 'h2', text: 'Deliverable 1: Word CV (2 pages max)' },
      { type: 'ol', items: ['Use a clean template or custom styles.', 'Sections: Profile, Education, Skills, Experience, References.', 'Include Microsoft 365 skills honestly (this course).', 'Header with name and contact; footer with page number.', 'Run spelling, grammar, and Accessibility Checker.'] },
      { type: 'h2', text: 'Deliverable 2: Excel personal budget' },
      { type: 'ol', items: ['12-month or semester budget: income, expenses, savings.', 'Formulas: SUM, AVERAGE, IF for over-budget flag.', 'One chart showing expense categories.', 'Conditional formatting on negative balance cells.', 'Table with filters; sheet named Dashboard optional.'] },
      { type: 'h2', text: 'Deliverable 3: PowerPoint pitch (6-8 slides)' },
      { type: 'ol', items: ['Pitch yourself for internship: problem you solve, skills, project proof, ask.', 'Consistent theme, speaker notes, one chart or image from Excel.', 'Professional transitions only (Fade).', 'Export PDF backup.'] },
      { type: 'h2', text: 'Deliverable 4: Workflow writeup (1 page Word)' },
      {
        type: 'code',
        title: 'Workflow topics to document',
        language: 'text',
        code: `How I apply: Outlook email + calendar scheduling
How I track applications: Excel or Planner
How I collaborate: Teams chat vs channel rules
How I store files: OneDrive folder structure
Security: MFA, sharing settings on CV versions`
      },
      { type: 'h2', text: 'Folder structure' },
      { type: 'p', text: 'OneDrive/ Career/ 2026_JobPack/ with all files and a View-only share link for mentor review.' },
      { type: 'tip', text: 'Ask a career counselor or senior student to review using Word comments. Revise once before calling it final.' },
      { type: 'note', text: 'Tailor CV keywords to job ads common in your market (bilingual, Excel, reporting, admin, NGO field work).' },
      { type: 'try', text: 'Complete all four deliverables and submit share link. Present pitch deck in under 5 minutes to a peer.' },
      { type: 'keypoints', items: ['Capstone integrates Word CV, Excel budget, PPT pitch, workflow doc.', 'Apply course skills: styles, formulas, charts, accessibility.', 'Organize files in OneDrive with professional naming.', 'Peer review and PDF backup complete the package.'] },
    ],
  },
  {
    slug: 'capstone-review-checklist',
    title: 'Capstone Review Checklist',
    description: 'Self-assess and peer-review Microsoft 365 capstone projects with a structured quality checklist.',
    level: 'advanced',
    section: 'Advanced Capstone',
    order: 47,
    minutes: 12,
    content: [
      { type: 'p', text: 'Before submitting or grading a capstone, use a consistent checklist. This lesson provides review criteria for files, collaboration habits, security, and presentation quality relevant to African academic and workplace standards.' },
      { type: 'h2', text: 'File and technical quality' },
      {
        type: 'table',
        headers: ['Check', 'Pass criteria'],
        rows: [
          ['File names', 'Date or version, clear topic, no spaces issues'],
          ['OneDrive location', 'Logical folder, not Desktop-only'],
          ['Word', 'Styles used, no manual heading chaos'],
          ['Excel', 'Formulas work when data changes; no hardcoded errors'],
          ['PowerPoint', 'Readable fonts, alt text on images'],
          ['Links', 'Share link works in incognito; correct permission'],
        ],
      },
      { type: 'h2', text: 'Collaboration and security' },
      { type: 'ul', items: ['Track Changes resolved or intentional comments only.', 'No passwords or ID numbers in filenames or body.', 'External sharing justified and View-only where possible.', 'Version history shows steady progress, not single last-minute dump.'] },
      { type: 'h2', text: 'Presentation and communication' },
      { type: 'ol', items: ['Pitch under time limit with clear ask at end.', 'Speaker notes present, not read verbatim.', 'Workflow doc explains real tools used, not generic fluff.', 'Spelling and French/English consistency if bilingual.'] },
      { type: 'h3', text: 'Peer review protocol' },
      { type: 'p', text: 'Reviewer leaves minimum two comments and one tracked suggestion in Word. Reviewee responds or fixes within 48 hours. Instructor sees comment thread as evidence of collaboration.' },
      { type: 'tip', text: 'Use a spreadsheet rubric mirroring this table. Score 1-4 per row for objective grading.' },
      { type: 'note', text: 'Accessibility is not optional for public sector or UN-adjacent roles. Fail item if checker shows unresolved errors on submitted PDF.' },
      { type: 'try', text: 'Review a partner capstone against every row in the tables. Write three actionable improvements.' },
      { type: 'keypoints', items: ['Check naming, formulas, styles, and share permissions systematically.', 'Security and collaboration matter as much as document beauty.', 'Peer review uses comments and tracked changes professionally.', 'Use rubric scores for fair self and instructor assessment.'] },
    ],
  },
  {
    slug: 'certifications-next-steps',
    title: 'Next Steps: Microsoft Certifications Overview',
    description: 'Explore MOS and Microsoft 365 certification paths and plan continued learning after this tutorial track.',
    level: 'advanced',
    section: 'Advanced Capstone',
    order: 48,
    minutes: 14,
    content: [
      { type: 'p', text: 'Formal certifications validate skills for employers in Cameroon, Nigeria, Kenya, South Africa, and global remote jobs. Microsoft offers credentials from fundamentals to expert. This lesson maps options after completing this course.' },
      { type: 'h2', text: 'Microsoft Office Specialist (MOS)' },
      { type: 'p', text: 'MOS exams test hands-on Word, Excel, and PowerPoint tasks in timed simulations. Good for admin, finance, and entry office roles. Look for authorized testing centers in major cities or online proctored options where available.' },
      {
        type: 'table',
        headers: ['Exam', 'Focus', 'After this course'],
        rows: [
          ['MOS Word Associate', 'Documents, references, mail merge prep', 'Lessons 5-9, 41'],
          ['MOS Excel Associate', 'Formulas, charts, tables', 'Lessons 10-15, 19-22, 40'],
          ['MOS PowerPoint Associate', 'Slides, media, delivery', 'Lessons 16-17, 23-24'],
        ],
      },
      { type: 'h2', text: 'Microsoft 365 Fundamentals (MS-900)' },
      { type: 'p', text: 'MS-900 is conceptual: cloud concepts, Microsoft 365 services, security, compliance, pricing. No deep technical labs. Useful for IT-adjacent roles and understanding org licensing. Study Microsoft Learn free modules.' },
      { type: 'h2', text: 'How to prepare' },
      { type: 'ol', items: ['Review weak lessons from this track.', 'Practice timed tasks in Office without help.', 'Microsoft Learn: browse Microsoft 365 and Office learning paths.', 'Join study group on Teams; teach a topic to lock knowledge.', 'Schedule exam when consistently passing practice tests.'] },
      { type: 'h2', text: 'Beyond certifications' },
      { type: 'ul', items: ['Build portfolio: redacted real reports, dashboards, merge samples.', 'Volunteer digitization for local NGO using Forms and Excel.', 'Learn Power BI next for analytics careers.', 'Explore admin paths: Microsoft 365 Certified: Teams Administrator Associate if IT interests you.'] },
      { type: 'note', text: 'Certification costs vary by country and currency. Some NGOs and universities subsidize exams. Ask career services.' },
      { type: 'tip', text: 'Add certified skills to LinkedIn and CV only after passing. In progress is fine for active study.' },
      { type: 'try', text: 'Pick one MOS exam aligned with your career goal. List five topic areas to review and one practice resource with URL from Microsoft Learn.' },
      { type: 'keypoints', items: ['MOS proves hands-on Word, Excel, PowerPoint skills.', 'MS-900 covers Microsoft 365 concepts for broader IT awareness.', 'Use Microsoft Learn and timed practice for exam prep.', 'Combine certs with portfolio projects for job impact.'] },
    ],
  },
  {
    slug: 'excel-printing-page-setup',
    title: 'Excel Printing and Page Setup',
    description: 'Prepare Excel reports for printing and PDF export with margins, headers, print areas, and fit-to-page settings.',
    level: 'advanced',
    section: 'Professional Standards',
    order: 49,
    minutes: 12,
    content: [
      { type: 'p', text: 'Screen-perfect spreadsheets often print on ten pages of tiny text. Offices in Africa still print hard copies for signatures, archives, and meetings without projectors. Page setup makes Excel output readable on A4 paper.' },
      { type: 'h2', text: 'Page Layout settings' },
      { type: 'ol', items: ['Page Layout tab: Orientation Portrait or Landscape.', 'Margins: Narrow for wide tables; Custom for official letterhead space.', 'Scale: Fit Sheet on One Page wide or tall when needed (watch readability).', 'Print Titles: repeat row 1 on every page for multi-page reports.', 'Header/Footer: company name, date, page number.'] },
      { type: 'h2', text: 'Print area and breaks' },
      { type: 'ul', items: ['Select range, Page Layout, Print Area, Set Print Area.', 'Page Break Preview shows blue lines; drag to adjust.', 'Insert Page Break before major sections manually if needed.', 'Print Gridlines only for drafts; usually off for client reports.'] },
      {
        type: 'table',
        headers: ['Problem', 'Fix'],
        rows: [
          ['Cuts off columns', 'Landscape, shrink scale, or hide nonessential columns'],
          ['No headers on page 2', 'Print Titles, rows to repeat $1:$1'],
          ['Splits table awkwardly', 'Manual page break above section'],
        ],
      },
      { type: 'tip', text: 'Export PDF (Ctrl+P, Microsoft Print to PDF) for WhatsApp sharing when recipients should not edit numbers.' },
      { type: 'h3', text: 'Print preview before paper' },
      { type: 'p', text: 'Always open File, Print preview before sending a large job to a campus or office printer. Confirm page count and readability. Adjust scale early instead of reprinting multiple times at cost per page.' },
      { type: 'note', text: 'Black and white printers lose color conditional formatting meaning. Add symbols or labels for critical flags.' },
      { type: 'try', text: 'Format a 50-row report to print on maximum 3 pages with repeating headers and footer page numbers.' },
      { type: 'keypoints', items: ['Set orientation, margins, and scaling on Page Layout tab.', 'Define Print Area and repeat header rows on each page.', 'Use Page Break Preview before printing or PDF export.', 'Test grayscale readability for conditional formats.'] },
    ],
  },
  {
    slug: 'outlook-contacts-tasks',
    title: 'Outlook Contacts and Tasks',
    description: 'Organize professional contacts and track follow-up tasks in Outlook alongside email and calendar.',
    level: 'advanced',
    section: 'Professional Standards',
    order: 50,
    minutes: 12,
    content: [
      { type: 'p', text: 'Outlook Contacts (People) stores phone numbers, organizations, and notes. Tasks and flagged email integrate with To Do. For job seekers and sales assistants, a clean contact list prevents lost networking opportunities after conferences and campus fairs.' },
      { type: 'h2', text: 'Manage contacts' },
      { type: 'ol', items: ['Open People in Outlook or outlook.com.', 'New Contact: name, email, phone, company, job title.', 'Create contact lists (distribution lists) for recurring groups.', 'Import CSV from event registration if policy allows.', 'Link contact to calendar meeting for quick follow-up.'] },
      { type: 'h2', text: 'Tasks and flagged mail' },
      { type: 'ul', items: ['Flag email for follow-up with due date; appears in To Do.', 'Create task: subject, due date, reminder, categories.', 'Assign priority; mark complete when done.', 'View Tasks in Outlook or Microsoft To Do mobile app.'] },
      {
        type: 'table',
        headers: ['Situation', 'Tool', 'Action'],
        rows: [
          ['Met recruiter at fair', 'Contact', 'Add notes on role discussed'],
          ['Send CV by Friday', 'Flagged email or Task', 'Due date Thursday'],
          ['Weekly networking goal', 'To Do My Day', 'Three outreach messages'],
        ],
      },
      { type: 'h2', text: 'Privacy and data protection' },
      { type: 'p', text: 'Store only professional details you are allowed to keep. GDPR-style rules apply to EU partners; local law may require consent for marketing contact. Do not export org directory to personal Gmail.' },
      { type: 'tip', text: 'Add category @Network to contacts met at events. Search category before follow-up season.' },
      { type: 'note', text: 'Sync contacts to phone carefully; work contacts on personal phone may violate policy.' },
      { type: 'try', text: 'Create five contacts, one contact list, and three tasks with due dates. Flag one email for follow-up and complete it in To Do.' },
      { type: 'keypoints', items: ['People stores professional contact details and notes.', 'Flagged email and Tasks sync with Microsoft To Do.', 'Contact lists speed up group email for clubs and teams.', 'Respect privacy rules when storing and exporting contacts.'] },
    ],
  },
];
