import type { TutorialLesson } from '../types';

export const advancedLessons: TutorialLesson[] = [
  {
    slug: "bash-security-mindset",
    title: "Security Mindset",
    description: "Injection risks in scripts.",
    level: "advanced",
    section: "Advanced Bash",
    order: 49,
    minutes: 16,
    content: [
      {"type":"p","text":"Security Mindset is a core skill in the Bash Scripting path on InTelleX. You will learn security mindset with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Security Mindset","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice security mindset with a small exercise of your own."},
      {"type":"keypoints","items":["Security Mindset is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-capstone-server-bootstrap",
    title: "Capstone: Server Bootstrap",
    description: "Full bootstrap with logging and flags.",
    level: "advanced",
    section: "Advanced Bash",
    order: 50,
    minutes: 20,
    content: [
      {"type":"p","text":"Capstone: Server Bootstrap is a core skill in the Bash Scripting path on InTelleX. You will learn capstone: server bootstrap with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Server Bootstrap","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice capstone: server bootstrap with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Server Bootstrap is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-capstone-dev-toolkit",
    title: "Capstone: Dev Toolkit",
    description: "Multi-command toolkit in one repo.",
    level: "advanced",
    section: "Capstone & Career",
    order: 51,
    minutes: 20,
    content: [
      {"type":"p","text":"Capstone: Dev Toolkit is a core skill in the Bash Scripting path on InTelleX. You will learn capstone: dev toolkit with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Dev Toolkit","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice capstone: dev toolkit with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Dev Toolkit is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-bash-interview-review",
    title: "Bash Interview Review",
    description: "Quoting, pipes, exit codes, set options.",
    level: "advanced",
    section: "Capstone & Career",
    order: 52,
    minutes: 16,
    content: [
      {"type":"p","text":"Bash Interview Review is a core skill in the Bash Scripting path on InTelleX. You will learn bash interview review with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Bash Interview Review","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice bash interview review with a small exercise of your own."},
      {"type":"keypoints","items":["Bash Interview Review is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-next-steps",
    title: "Next Steps",
    description: "Python for larger tools; keep Bash sharp.",
    level: "advanced",
    section: "Capstone & Career",
    order: 53,
    minutes: 16,
    content: [
      {"type":"p","text":"Next Steps is a core skill in the Bash Scripting path on InTelleX. You will learn next steps with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Next Steps","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice next steps with a small exercise of your own."},
      {"type":"keypoints","items":["Next Steps is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-final-challenge",
    title: "Final Challenge",
    description: "Automate a weekly report from logs.",
    level: "advanced",
    section: "Capstone & Career",
    order: 54,
    minutes: 16,
    content: [
      {"type":"p","text":"Final Challenge is a core skill in the Bash Scripting path on InTelleX. You will learn final challenge with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Final Challenge","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice final challenge with a small exercise of your own."},
      {"type":"keypoints","items":["Final Challenge is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-glossary-drill",
    title: "Glossary Drill",
    description: "pipefail, glob, subshell, shebang, IFS.",
    level: "advanced",
    section: "Capstone & Career",
    order: 55,
    minutes: 16,
    content: [
      {"type":"p","text":"Glossary Drill is a core skill in the Bash Scripting path on InTelleX. You will learn glossary drill with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Glossary Drill","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice glossary drill with a small exercise of your own."},
      {"type":"keypoints","items":["Glossary Drill is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-reading-scripts",
    title: "Reading Scripts",
    description: "Audit an unfamiliar script safely.",
    level: "advanced",
    section: "Capstone & Career",
    order: 56,
    minutes: 16,
    content: [
      {"type":"p","text":"Reading Scripts is a core skill in the Bash Scripting path on InTelleX. You will learn reading scripts with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Reading Scripts","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice reading scripts with a small exercise of your own."},
      {"type":"keypoints","items":["Reading Scripts is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-portability-notes",
    title: "Portability Notes",
    description: "bashisms vs POSIX sh.",
    level: "advanced",
    section: "Capstone & Career",
    order: 57,
    minutes: 16,
    content: [
      {"type":"p","text":"Portability Notes is a core skill in the Bash Scripting path on InTelleX. You will learn portability notes with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Portability Notes","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice portability notes with a small exercise of your own."},
      {"type":"keypoints","items":["Portability Notes is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-ci-scripting",
    title: "CI Scripting",
    description: "Scripts that run in GitHub Actions.",
    level: "advanced",
    section: "Capstone & Career",
    order: 58,
    minutes: 16,
    content: [
      {"type":"p","text":"CI Scripting is a core skill in the Bash Scripting path on InTelleX. You will learn ci scripting with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind CI Scripting","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice ci scripting with a small exercise of your own."},
      {"type":"keypoints","items":["CI Scripting is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-portfolio-tips",
    title: "Portfolio Tips",
    description: "Show before/after automation metrics.",
    level: "advanced",
    section: "Capstone & Career",
    order: 59,
    minutes: 16,
    content: [
      {"type":"p","text":"Portfolio Tips is a core skill in the Bash Scripting path on InTelleX. You will learn portfolio tips with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Portfolio Tips","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice portfolio tips with a small exercise of your own."},
      {"type":"keypoints","items":["Portfolio Tips is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-style-guide",
    title: "Style Guide",
    description: "Consistent formatting and function layout.",
    level: "advanced",
    section: "Capstone & Career",
    order: 60,
    minutes: 16,
    content: [
      {"type":"p","text":"Style Guide is a core skill in the Bash Scripting path on InTelleX. You will learn style guide with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Style Guide","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice style guide with a small exercise of your own."},
      {"type":"keypoints","items":["Style Guide is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-extra-61",
    title: "Practice Lab 61",
    description: "Hands-on practice lab consolidating earlier bash skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 61,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 61 is a core skill in the Bash Scripting path on InTelleX. You will learn practice lab 61 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 61","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 61 is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-extra-62",
    title: "Practice Lab 62",
    description: "Hands-on practice lab consolidating earlier bash skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 62,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 62 is a core skill in the Bash Scripting path on InTelleX. You will learn practice lab 62 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 62","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 62 is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-extra-63",
    title: "Practice Lab 63",
    description: "Hands-on practice lab consolidating earlier bash skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 63,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 63 is a core skill in the Bash Scripting path on InTelleX. You will learn practice lab 63 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 63","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 63 is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-extra-64",
    title: "Practice Lab 64",
    description: "Hands-on practice lab consolidating earlier bash skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 64,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 64 is a core skill in the Bash Scripting path on InTelleX. You will learn practice lab 64 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 64","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 64 is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-extra-65",
    title: "Practice Lab 65",
    description: "Hands-on practice lab consolidating earlier bash skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 65,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 65 is a core skill in the Bash Scripting path on InTelleX. You will learn practice lab 65 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 65","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 65 is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
