import type { TutorialLesson } from '../types';

export const beginnerLessons: TutorialLesson[] = [
  {
    slug: "bash-welcome-to-bash-scripting",
    title: "Welcome to Bash Scripting",
    description: "Automate the terminal safely and clearly.",
    level: "beginner",
    section: "Getting Started",
    order: 1,
    minutes: 11,
    content: [
      {"type":"p","text":"Welcome to Bash Scripting is a core skill in the Bash Scripting path on InTelleX. You will learn welcome to bash scripting with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Welcome to Bash Scripting","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice welcome to bash scripting with a small exercise of your own."},
      {"type":"keypoints","items":["Welcome to Bash Scripting is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-what-is-a-shell",
    title: "What is a Shell?",
    description: "bash vs sh vs zsh at a glance.",
    level: "beginner",
    section: "Getting Started",
    order: 2,
    minutes: 11,
    content: [
      {"type":"p","text":"What is a Shell? is a core skill in the Bash Scripting path on InTelleX. You will learn what is a shell? with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind What is a Shell?","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice what is a shell? with a small exercise of your own."},
      {"type":"keypoints","items":["What is a Shell? is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-your-first-script",
    title: "Your First Script",
    description: "Shebang, permissions, execution.",
    level: "beginner",
    section: "Getting Started",
    order: 3,
    minutes: 11,
    content: [
      {"type":"p","text":"Your First Script is a core skill in the Bash Scripting path on InTelleX. You will learn your first script with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Your First Script","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"#!/usr/bin/env bash\nset -euo pipefail\necho \"Hello from Bash\"","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice your first script with a small exercise of your own."},
      {"type":"keypoints","items":["Your First Script is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-chmod-x-path",
    title: "chmod +x & PATH",
    description: "Make scripts runnable.",
    level: "beginner",
    section: "Getting Started",
    order: 4,
    minutes: 11,
    content: [
      {"type":"p","text":"chmod +x & PATH is a core skill in the Bash Scripting path on InTelleX. You will learn chmod +x & path with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind chmod +x & PATH","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice chmod +x & path with a small exercise of your own."},
      {"type":"keypoints","items":["chmod +x & PATH is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-quoting-rules",
    title: "quoting Rules",
    description: "Single vs double quotes and why it matters.",
    level: "beginner",
    section: "Getting Started",
    order: 5,
    minutes: 11,
    content: [
      {"type":"p","text":"quoting Rules is a core skill in the Bash Scripting path on InTelleX. You will learn quoting rules with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind quoting Rules","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"name=\"Ada Lovelace\"\necho \"$name\"\necho '$name'","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice quoting rules with a small exercise of your own."},
      {"type":"keypoints","items":["quoting Rules is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-variables",
    title: "Variables",
    description: "Assign and expand safely.",
    level: "beginner",
    section: "Variables & Input",
    order: 6,
    minutes: 11,
    content: [
      {"type":"p","text":"Variables is a core skill in the Bash Scripting path on InTelleX. You will learn variables with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Variables","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"count=3\necho \"count=${count}\"","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice variables with a small exercise of your own."},
      {"type":"keypoints","items":["Variables is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-environment-variables",
    title: "Environment Variables",
    description: "export and child processes.",
    level: "beginner",
    section: "Variables & Input",
    order: 7,
    minutes: 11,
    content: [
      {"type":"p","text":"Environment Variables is a core skill in the Bash Scripting path on InTelleX. You will learn environment variables with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Environment Variables","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice environment variables with a small exercise of your own."},
      {"type":"keypoints","items":["Environment Variables is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-positional-parameters",
    title: "Positional Parameters",
    description: "$1, $@, $#. ",
    level: "beginner",
    section: "Variables & Input",
    order: 8,
    minutes: 11,
    content: [
      {"type":"p","text":"Positional Parameters is a core skill in the Bash Scripting path on InTelleX. You will learn positional parameters with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Positional Parameters","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"#!/usr/bin/env bash\necho \"Script: $0\"\necho \"First arg: ${1-}\"","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice positional parameters with a small exercise of your own."},
      {"type":"keypoints","items":["Positional Parameters is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-read-input",
    title: "read Input",
    description: "Prompt users interactively.",
    level: "beginner",
    section: "Variables & Input",
    order: 9,
    minutes: 11,
    content: [
      {"type":"p","text":"read Input is a core skill in the Bash Scripting path on InTelleX. You will learn read input with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind read Input","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice read input with a small exercise of your own."},
      {"type":"keypoints","items":["read Input is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-default-values",
    title: "Default Values",
    description: "${var:-default} patterns.",
    level: "beginner",
    section: "Variables & Input",
    order: 10,
    minutes: 11,
    content: [
      {"type":"p","text":"Default Values is a core skill in the Bash Scripting path on InTelleX. You will learn default values with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Default Values","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice default values with a small exercise of your own."},
      {"type":"keypoints","items":["Default Values is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-if-test",
    title: "if & test",
    description: "[[ ]] conditions.",
    level: "beginner",
    section: "Control Flow",
    order: 11,
    minutes: 11,
    content: [
      {"type":"p","text":"if & test is a core skill in the Bash Scripting path on InTelleX. You will learn if & test with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind if & test","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"if [[ -f \"$file\" ]]; then\n  echo \"exists\"\nfi","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice if & test with a small exercise of your own."},
      {"type":"keypoints","items":["if & test is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-loops",
    title: "Loops",
    description: "for, while, until.",
    level: "beginner",
    section: "Control Flow",
    order: 12,
    minutes: 11,
    content: [
      {"type":"p","text":"Loops is a core skill in the Bash Scripting path on InTelleX. You will learn loops with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Loops","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"for f in *.txt; do\n  echo \"$f\"\ndone","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice loops with a small exercise of your own."},
      {"type":"keypoints","items":["Loops is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-case-statements",
    title: "case Statements",
    description: "Menus and routers.",
    level: "beginner",
    section: "Control Flow",
    order: 13,
    minutes: 11,
    content: [
      {"type":"p","text":"case Statements is a core skill in the Bash Scripting path on InTelleX. You will learn case statements with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind case Statements","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice case statements with a small exercise of your own."},
      {"type":"keypoints","items":["case Statements is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-functions",
    title: "Functions",
    description: "Reusable blocks with local vars.",
    level: "beginner",
    section: "Control Flow",
    order: 14,
    minutes: 11,
    content: [
      {"type":"p","text":"Functions is a core skill in the Bash Scripting path on InTelleX. You will learn functions with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Functions","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"greet() {\n  local name=$1\n  echo \"Hi, $name\"\n}","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice functions with a small exercise of your own."},
      {"type":"keypoints","items":["Functions is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-exit-codes",
    title: "Exit Codes",
    description: "$? and set -e discipline.",
    level: "beginner",
    section: "Control Flow",
    order: 15,
    minutes: 11,
    content: [
      {"type":"p","text":"Exit Codes is a core skill in the Bash Scripting path on InTelleX. You will learn exit codes with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Exit Codes","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice exit codes with a small exercise of your own."},
      {"type":"keypoints","items":["Exit Codes is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-pipes-redirection",
    title: "Pipes & Redirection",
    description: "|, >, >>, 2>&1.",
    level: "beginner",
    section: "Text & Pipelines",
    order: 16,
    minutes: 11,
    content: [
      {"type":"p","text":"Pipes & Redirection is a core skill in the Bash Scripting path on InTelleX. You will learn pipes & redirection with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Pipes & Redirection","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"grep error app.log | wc -l","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice pipes & redirection with a small exercise of your own."},
      {"type":"keypoints","items":["Pipes & Redirection is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-grep",
    title: "grep",
    description: "Search with regular expressions.",
    level: "beginner",
    section: "Text & Pipelines",
    order: 17,
    minutes: 11,
    content: [
      {"type":"p","text":"grep is a core skill in the Bash Scripting path on InTelleX. You will learn grep with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind grep","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice grep with a small exercise of your own."},
      {"type":"keypoints","items":["grep is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-sed-basics",
    title: "sed Basics",
    description: "Stream edits.",
    level: "beginner",
    section: "Text & Pipelines",
    order: 18,
    minutes: 11,
    content: [
      {"type":"p","text":"sed Basics is a core skill in the Bash Scripting path on InTelleX. You will learn sed basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind sed Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"sed -i 's/foo/bar/g' file.txt","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice sed basics with a small exercise of your own."},
      {"type":"keypoints","items":["sed Basics is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-awk-basics",
    title: "awk Basics",
    description: "Column processing.",
    level: "beginner",
    section: "Text & Pipelines",
    order: 19,
    minutes: 11,
    content: [
      {"type":"p","text":"awk Basics is a core skill in the Bash Scripting path on InTelleX. You will learn awk basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind awk Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"awk -F, '{print $1}' data.csv","title":"Example","language":"bash"},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice awk basics with a small exercise of your own."},
      {"type":"keypoints","items":["awk Basics is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-project-log-summarizer",
    title: "Project: Log Summarizer",
    description: "Count errors by day from a logfile.",
    level: "beginner",
    section: "Text & Pipelines",
    order: 20,
    minutes: 16,
    content: [
      {"type":"p","text":"Project: Log Summarizer is a core skill in the Bash Scripting path on InTelleX. You will learn project: log summarizer with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Log Summarizer","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice project: log summarizer with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Log Summarizer is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-globs",
    title: "Globs",
    description: "Wildcards and nullglob.",
    level: "beginner",
    section: "Files & Safety",
    order: 21,
    minutes: 11,
    content: [
      {"type":"p","text":"Globs is a core skill in the Bash Scripting path on InTelleX. You will learn globs with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Globs","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice globs with a small exercise of your own."},
      {"type":"keypoints","items":["Globs is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-find-xargs",
    title: "find + xargs",
    description: "Act on many files safely.",
    level: "beginner",
    section: "Files & Safety",
    order: 22,
    minutes: 11,
    content: [
      {"type":"p","text":"find + xargs is a core skill in the Bash Scripting path on InTelleX. You will learn find + xargs with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind find + xargs","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice find + xargs with a small exercise of your own."},
      {"type":"keypoints","items":["find + xargs is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-set-euo-pipefail",
    title: "set -euo pipefail",
    description: "Hard mode for reliable scripts.",
    level: "beginner",
    section: "Files & Safety",
    order: 23,
    minutes: 11,
    content: [
      {"type":"p","text":"set -euo pipefail is a core skill in the Bash Scripting path on InTelleX. You will learn set -euo pipefail with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind set -euo pipefail","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice set -euo pipefail with a small exercise of your own."},
      {"type":"keypoints","items":["set -euo pipefail is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-trap-cleanup",
    title: "Trap & Cleanup",
    description: "Remove temp files on exit.",
    level: "beginner",
    section: "Files & Safety",
    order: 24,
    minutes: 11,
    content: [
      {"type":"p","text":"Trap & Cleanup is a core skill in the Bash Scripting path on InTelleX. You will learn trap & cleanup with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Trap & Cleanup","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice trap & cleanup with a small exercise of your own."},
      {"type":"keypoints","items":["Trap & Cleanup is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-project-safe-backup-script",
    title: "Project: Safe Backup Script",
    description: "Copy a directory with timestamp.",
    level: "beginner",
    section: "Files & Safety",
    order: 25,
    minutes: 16,
    content: [
      {"type":"p","text":"Project: Safe Backup Script is a core skill in the Bash Scripting path on InTelleX. You will learn project: safe backup script with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Safe Backup Script","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice project: safe backup script with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Safe Backup Script is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
