import type { TutorialLesson } from '../types';

export const intermediateLessons: TutorialLesson[] = [
  {
    slug: "bash-arrays",
    title: "Arrays",
    description: "Indexed arrays and iteration.",
    level: "intermediate",
    section: "Intermediate Scripting",
    order: 26,
    minutes: 13,
    content: [
      {"type":"p","text":"Arrays is a core skill in the Bash Scripting path on InTelleX. You will learn arrays with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Arrays","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice arrays with a small exercise of your own."},
      {"type":"keypoints","items":["Arrays is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-associative-arrays",
    title: "Associative Arrays",
    description: "Key-value maps in bash 4+.",
    level: "intermediate",
    section: "Intermediate Scripting",
    order: 27,
    minutes: 13,
    content: [
      {"type":"p","text":"Associative Arrays is a core skill in the Bash Scripting path on InTelleX. You will learn associative arrays with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Associative Arrays","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice associative arrays with a small exercise of your own."},
      {"type":"keypoints","items":["Associative Arrays is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-here-documents",
    title: "Here Documents",
    description: "Multi-line input to commands.",
    level: "intermediate",
    section: "Intermediate Scripting",
    order: 28,
    minutes: 13,
    content: [
      {"type":"p","text":"Here Documents is a core skill in the Bash Scripting path on InTelleX. You will learn here documents with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Here Documents","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice here documents with a small exercise of your own."},
      {"type":"keypoints","items":["Here Documents is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-getopts",
    title: "getopts",
    description: "Parse flags professionally.",
    level: "intermediate",
    section: "Intermediate Scripting",
    order: 29,
    minutes: 13,
    content: [
      {"type":"p","text":"getopts is a core skill in the Bash Scripting path on InTelleX. You will learn getopts with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind getopts","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice getopts with a small exercise of your own."},
      {"type":"keypoints","items":["getopts is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-project-cli-with-flags",
    title: "Project: CLI with Flags",
    description: "Build -h/-v/-o options.",
    level: "intermediate",
    section: "Intermediate Scripting",
    order: 30,
    minutes: 16,
    content: [
      {"type":"p","text":"Project: CLI with Flags is a core skill in the Bash Scripting path on InTelleX. You will learn project: cli with flags with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: CLI with Flags","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice project: cli with flags with a small exercise of your own."},
      {"type":"keypoints","items":["Project: CLI with Flags is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-background-jobs",
    title: "Background Jobs",
    description: "& and wait.",
    level: "intermediate",
    section: "Process & Jobs",
    order: 31,
    minutes: 13,
    content: [
      {"type":"p","text":"Background Jobs is a core skill in the Bash Scripting path on InTelleX. You will learn background jobs with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Background Jobs","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice background jobs with a small exercise of your own."},
      {"type":"keypoints","items":["Background Jobs is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-subshells",
    title: "Subshells",
    description: "( ) vs { }.",
    level: "intermediate",
    section: "Process & Jobs",
    order: 32,
    minutes: 13,
    content: [
      {"type":"p","text":"Subshells is a core skill in the Bash Scripting path on InTelleX. You will learn subshells with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Subshells","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice subshells with a small exercise of your own."},
      {"type":"keypoints","items":["Subshells is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-command-substitution",
    title: "Command Substitution",
    description: "$(...) patterns.",
    level: "intermediate",
    section: "Process & Jobs",
    order: 33,
    minutes: 13,
    content: [
      {"type":"p","text":"Command Substitution is a core skill in the Bash Scripting path on InTelleX. You will learn command substitution with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Command Substitution","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice command substitution with a small exercise of your own."},
      {"type":"keypoints","items":["Command Substitution is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-parallel-ish-loops",
    title: "Parallel-ish Loops",
    description: "When to use xargs -P.",
    level: "intermediate",
    section: "Process & Jobs",
    order: 34,
    minutes: 13,
    content: [
      {"type":"p","text":"Parallel-ish Loops is a core skill in the Bash Scripting path on InTelleX. You will learn parallel-ish loops with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Parallel-ish Loops","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice parallel-ish loops with a small exercise of your own."},
      {"type":"keypoints","items":["Parallel-ish Loops is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-project-health-check",
    title: "Project: Health Check",
    description: "Ping endpoints and report status.",
    level: "intermediate",
    section: "Process & Jobs",
    order: 35,
    minutes: 14,
    content: [
      {"type":"p","text":"Project: Health Check is a core skill in the Bash Scripting path on InTelleX. You will learn project: health check with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Health Check","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice project: health check with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Health Check is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-idempotent-scripts",
    title: "Idempotent Scripts",
    description: "Safe to run twice.",
    level: "intermediate",
    section: "Automation Patterns",
    order: 36,
    minutes: 13,
    content: [
      {"type":"p","text":"Idempotent Scripts is a core skill in the Bash Scripting path on InTelleX. You will learn idempotent scripts with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Idempotent Scripts","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice idempotent scripts with a small exercise of your own."},
      {"type":"keypoints","items":["Idempotent Scripts is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-logging-patterns",
    title: "Logging Patterns",
    description: "Timestamps and levels.",
    level: "intermediate",
    section: "Automation Patterns",
    order: 37,
    minutes: 13,
    content: [
      {"type":"p","text":"Logging Patterns is a core skill in the Bash Scripting path on InTelleX. You will learn logging patterns with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Logging Patterns","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice logging patterns with a small exercise of your own."},
      {"type":"keypoints","items":["Logging Patterns is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-config-files",
    title: "Config Files",
    description: "Source a config safely.",
    level: "intermediate",
    section: "Automation Patterns",
    order: 38,
    minutes: 13,
    content: [
      {"type":"p","text":"Config Files is a core skill in the Bash Scripting path on InTelleX. You will learn config files with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Config Files","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice config files with a small exercise of your own."},
      {"type":"keypoints","items":["Config Files is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-cron-integration",
    title: "Cron Integration",
    description: "Schedule your scripts.",
    level: "intermediate",
    section: "Automation Patterns",
    order: 39,
    minutes: 13,
    content: [
      {"type":"p","text":"Cron Integration is a core skill in the Bash Scripting path on InTelleX. You will learn cron integration with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Cron Integration","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice cron integration with a small exercise of your own."},
      {"type":"keypoints","items":["Cron Integration is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-project-deploy-hook",
    title: "Project: Deploy Hook",
    description: "Pull, build, restart service.",
    level: "intermediate",
    section: "Automation Patterns",
    order: 40,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: Deploy Hook is a core skill in the Bash Scripting path on InTelleX. You will learn project: deploy hook with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Deploy Hook","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice project: deploy hook with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Deploy Hook is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-bash-x",
    title: "bash -x",
    description: "Trace execution.",
    level: "intermediate",
    section: "Debugging & Testing",
    order: 41,
    minutes: 13,
    content: [
      {"type":"p","text":"bash -x is a core skill in the Bash Scripting path on InTelleX. You will learn bash -x with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind bash -x","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice bash -x with a small exercise of your own."},
      {"type":"keypoints","items":["bash -x is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-shellcheck",
    title: "Shellcheck",
    description: "Static analysis for scripts.",
    level: "intermediate",
    section: "Debugging & Testing",
    order: 42,
    minutes: 13,
    content: [
      {"type":"p","text":"Shellcheck is a core skill in the Bash Scripting path on InTelleX. You will learn shellcheck with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Shellcheck","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice shellcheck with a small exercise of your own."},
      {"type":"keypoints","items":["Shellcheck is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-bats-testing-overview",
    title: "Bats Testing Overview",
    description: "Test shell scripts.",
    level: "intermediate",
    section: "Debugging & Testing",
    order: 43,
    minutes: 13,
    content: [
      {"type":"p","text":"Bats Testing Overview is a core skill in the Bash Scripting path on InTelleX. You will learn bats testing overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Bats Testing Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice bats testing overview with a small exercise of your own."},
      {"type":"keypoints","items":["Bats Testing Overview is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-common-pitfalls",
    title: "Common Pitfalls",
    description: "Word splitting and globbing bugs.",
    level: "intermediate",
    section: "Debugging & Testing",
    order: 44,
    minutes: 13,
    content: [
      {"type":"p","text":"Common Pitfalls is a core skill in the Bash Scripting path on InTelleX. You will learn common pitfalls with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Common Pitfalls","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice common pitfalls with a small exercise of your own."},
      {"type":"keypoints","items":["Common Pitfalls is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-project-refactor-a-messy-script",
    title: "Project: Refactor a Messy Script",
    description: "Harden an unsafe script.",
    level: "intermediate",
    section: "Debugging & Testing",
    order: 45,
    minutes: 16,
    content: [
      {"type":"p","text":"Project: Refactor a Messy Script is a core skill in the Bash Scripting path on InTelleX. You will learn project: refactor a messy script with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Refactor a Messy Script","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice project: refactor a messy script with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Refactor a Messy Script is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-namerefs",
    title: "Namerefs",
    description: "declare -n techniques.",
    level: "intermediate",
    section: "Advanced Bash",
    order: 46,
    minutes: 13,
    content: [
      {"type":"p","text":"Namerefs is a core skill in the Bash Scripting path on InTelleX. You will learn namerefs with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Namerefs","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice namerefs with a small exercise of your own."},
      {"type":"keypoints","items":["Namerefs is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-coprocesses-overview",
    title: "Coprocesses Overview",
    description: "Advanced IPC glimpse.",
    level: "intermediate",
    section: "Advanced Bash",
    order: 47,
    minutes: 13,
    content: [
      {"type":"p","text":"Coprocesses Overview is a core skill in the Bash Scripting path on InTelleX. You will learn coprocesses overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Coprocesses Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice coprocesses overview with a small exercise of your own."},
      {"type":"keypoints","items":["Coprocesses Overview is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "bash-performance-tips",
    title: "Performance Tips",
    description: "Avoid useless cats and subshells.",
    level: "intermediate",
    section: "Advanced Bash",
    order: 48,
    minutes: 13,
    content: [
      {"type":"p","text":"Performance Tips is a core skill in the Bash Scripting path on InTelleX. You will learn performance tips with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Performance Tips","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself — reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Bash Scripting lab folder as you go."},
      {"type":"try","text":"Practice performance tips with a small exercise of your own."},
      {"type":"keypoints","items":["Performance Tips is an essential Bash Scripting skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
