import type { TutorialLesson } from '../types';

export const advancedLessons: TutorialLesson[] = [
  {
    slug: "arduino-pid-intuition",
    title: "PID Intuition",
    description: "Proportional control for smoother motion.",
    level: "advanced",
    section: "Robotics Basics",
    order: 49,
    minutes: 16,
    content: [
      {"type":"p","text":"PID Intuition is a core skill in the Arduino path on InTelleX. You will learn pid intuition with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind PID Intuition","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice pid intuition with a small exercise of your own."},
      {"type":"keypoints","items":["PID Intuition is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-project-mini-robot",
    title: "Project: Mini Robot",
    description: "Combine sensors and motors.",
    level: "advanced",
    section: "Robotics Basics",
    order: 50,
    minutes: 20,
    content: [
      {"type":"p","text":"Project: Mini Robot is a core skill in the Arduino path on InTelleX. You will learn project: mini robot with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Mini Robot","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice project: mini robot with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Mini Robot is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-schematics-wiring-discipline",
    title: "Schematics & Wiring Discipline",
    description: "Document connections clearly.",
    level: "advanced",
    section: "Professional Practices",
    order: 51,
    minutes: 16,
    content: [
      {"type":"p","text":"Schematics & Wiring Discipline is a core skill in the Arduino path on InTelleX. You will learn schematics & wiring discipline with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Schematics & Wiring Discipline","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice schematics & wiring discipline with a small exercise of your own."},
      {"type":"keypoints","items":["Schematics & Wiring Discipline is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-version-control-for-firmware",
    title: "Version Control for Firmware",
    description: "Git habits for sketches.",
    level: "advanced",
    section: "Professional Practices",
    order: 52,
    minutes: 16,
    content: [
      {"type":"p","text":"Version Control for Firmware is a core skill in the Arduino path on InTelleX. You will learn version control for firmware with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Version Control for Firmware","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice version control for firmware with a small exercise of your own."},
      {"type":"keypoints","items":["Version Control for Firmware is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-testing-on-hardware",
    title: "Testing on Hardware",
    description: "Bring-up checklists.",
    level: "advanced",
    section: "Professional Practices",
    order: 53,
    minutes: 16,
    content: [
      {"type":"p","text":"Testing on Hardware is a core skill in the Arduino path on InTelleX. You will learn testing on hardware with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Testing on Hardware","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice testing on hardware with a small exercise of your own."},
      {"type":"keypoints","items":["Testing on Hardware is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-capstone-home-automation-node",
    title: "Capstone: Home Automation Node",
    description: "Button, relay, sensor, serial protocol.",
    level: "advanced",
    section: "Professional Practices",
    order: 54,
    minutes: 20,
    content: [
      {"type":"p","text":"Capstone: Home Automation Node is a core skill in the Arduino path on InTelleX. You will learn capstone: home automation node with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Home Automation Node","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice capstone: home automation node with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Home Automation Node is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-capstone-data-logger",
    title: "Capstone: Data Logger",
    description: "Log readings to SD or serial CSV.",
    level: "advanced",
    section: "Professional Practices",
    order: 55,
    minutes: 18,
    content: [
      {"type":"p","text":"Capstone: Data Logger is a core skill in the Arduino path on InTelleX. You will learn capstone: data logger with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Capstone: Data Logger","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice capstone: data logger with a small exercise of your own."},
      {"type":"keypoints","items":["Capstone: Data Logger is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-arduino-interview-portfolio",
    title: "Arduino Interview & Portfolio",
    description: "Show projects with photos, schematics, and code.",
    level: "advanced",
    section: "Professional Practices",
    order: 56,
    minutes: 16,
    content: [
      {"type":"p","text":"Arduino Interview & Portfolio is a core skill in the Arduino path on InTelleX. You will learn arduino interview & portfolio with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Arduino Interview & Portfolio","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice arduino interview & portfolio with a small exercise of your own."},
      {"type":"keypoints","items":["Arduino Interview & Portfolio is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-next-steps",
    title: "Next Steps",
    description: "PCB design, FreeRTOS, or ROS for robots.",
    level: "advanced",
    section: "Professional Practices",
    order: 57,
    minutes: 16,
    content: [
      {"type":"p","text":"Next Steps is a core skill in the Arduino path on InTelleX. You will learn next steps with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Next Steps","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice next steps with a small exercise of your own."},
      {"type":"keypoints","items":["Next Steps is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-safety-ethics",
    title: "Safety & Ethics",
    description: "Mains power, batteries, and responsible making.",
    level: "advanced",
    section: "Professional Practices",
    order: 58,
    minutes: 16,
    content: [
      {"type":"p","text":"Safety & Ethics is a core skill in the Arduino path on InTelleX. You will learn safety & ethics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Safety & Ethics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice safety & ethics with a small exercise of your own."},
      {"type":"keypoints","items":["Safety & Ethics is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-community-open-hardware",
    title: "Community & Open Hardware",
    description: "Licenses and sharing designs.",
    level: "advanced",
    section: "Professional Practices",
    order: 59,
    minutes: 16,
    content: [
      {"type":"p","text":"Community & Open Hardware is a core skill in the Arduino path on InTelleX. You will learn community & open hardware with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Community & Open Hardware","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice community & open hardware with a small exercise of your own."},
      {"type":"keypoints","items":["Community & Open Hardware is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-final-challenge-brief",
    title: "Final Challenge Brief",
    description: "Design a 1-week build with bill of materials.",
    level: "advanced",
    section: "Professional Practices",
    order: 60,
    minutes: 16,
    content: [
      {"type":"p","text":"Final Challenge Brief is a core skill in the Arduino path on InTelleX. You will learn final challenge brief with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Final Challenge Brief","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice final challenge brief with a small exercise of your own."},
      {"type":"keypoints","items":["Final Challenge Brief is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-extra-61",
    title: "Practice Lab 61",
    description: "Hands-on practice lab consolidating earlier arduino skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 61,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 61 is a core skill in the Arduino path on InTelleX. You will learn practice lab 61 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 61","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 61 is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-extra-62",
    title: "Practice Lab 62",
    description: "Hands-on practice lab consolidating earlier arduino skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 62,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 62 is a core skill in the Arduino path on InTelleX. You will learn practice lab 62 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 62","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 62 is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-extra-63",
    title: "Practice Lab 63",
    description: "Hands-on practice lab consolidating earlier arduino skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 63,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 63 is a core skill in the Arduino path on InTelleX. You will learn practice lab 63 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 63","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 63 is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-extra-64",
    title: "Practice Lab 64",
    description: "Hands-on practice lab consolidating earlier arduino skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 64,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 64 is a core skill in the Arduino path on InTelleX. You will learn practice lab 64 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 64","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 64 is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-extra-65",
    title: "Practice Lab 65",
    description: "Hands-on practice lab consolidating earlier arduino skills.",
    level: "advanced",
    section: "Practice Labs",
    order: 65,
    minutes: 16,
    content: [
      {"type":"p","text":"Practice Lab 65 is a core skill in the Arduino path on InTelleX. You will learn practice lab 65 with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Practice Lab 65","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Build a tiny program that combines three earlier ideas."},
      {"type":"keypoints","items":["Practice Lab 65 is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
