import type { TutorialLesson } from '../types';

export const beginnerLessons: TutorialLesson[] = [
  {
    slug: "arduino-welcome-to-arduino",
    title: "Welcome to Arduino",
    description: "Microcontrollers, boards, and the maker mindset.",
    level: "beginner",
    section: "Getting Started",
    order: 1,
    minutes: 11,
    content: [
      {"type":"p","text":"Welcome to Arduino is a core skill in the Arduino path on InTelleX. You will learn welcome to arduino with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Welcome to Arduino","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"// Empty sketch\nvoid setup() {}\nvoid loop() {}","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice welcome to arduino with a small exercise of your own."},
      {"type":"keypoints","items":["Welcome to Arduino is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-install-arduino-ide",
    title: "Install Arduino IDE",
    description: "Install the IDE or Arduino CLI and open the serial monitor.",
    level: "beginner",
    section: "Getting Started",
    order: 2,
    minutes: 11,
    content: [
      {"type":"p","text":"Install Arduino IDE is a core skill in the Arduino path on InTelleX. You will learn install arduino ide with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Install Arduino IDE","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice install arduino ide with a small exercise of your own."},
      {"type":"keypoints","items":["Install Arduino IDE is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-board-anatomy",
    title: "Board Anatomy",
    description: "Pins, power, USB, reset, and voltage rails.",
    level: "beginner",
    section: "Getting Started",
    order: 3,
    minutes: 11,
    content: [
      {"type":"p","text":"Board Anatomy is a core skill in the Arduino path on InTelleX. You will learn board anatomy with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Board Anatomy","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice board anatomy with a small exercise of your own."},
      {"type":"keypoints","items":["Board Anatomy is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-your-first-sketch",
    title: "Your First Sketch",
    description: "Upload Blink and understand setup/loop.",
    level: "beginner",
    section: "Getting Started",
    order: 4,
    minutes: 11,
    content: [
      {"type":"p","text":"Your First Sketch is a core skill in the Arduino path on InTelleX. You will learn your first sketch with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Your First Sketch","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"void setup() {\n  pinMode(LED_BUILTIN, OUTPUT);\n}\nvoid loop() {\n  digitalWrite(LED_BUILTIN, HIGH);\n  delay(500);\n  digitalWrite(LED_BUILTIN, LOW);\n  delay(500);\n}","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice your first sketch with a small exercise of your own."},
      {"type":"keypoints","items":["Your First Sketch is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-serial-monitor-basics",
    title: "Serial Monitor Basics",
    description: "Debug with Serial.begin and println.",
    level: "beginner",
    section: "Getting Started",
    order: 5,
    minutes: 11,
    content: [
      {"type":"p","text":"Serial Monitor Basics is a core skill in the Arduino path on InTelleX. You will learn serial monitor basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Serial Monitor Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"h2","text":"Example"},
      {"type":"code","code":"void setup() {\n  Serial.begin(9600);\n  Serial.println(\"Hello Arduino\");\n}","title":"Example","language":"cpp"},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice serial monitor basics with a small exercise of your own."},
      {"type":"keypoints","items":["Serial Monitor Basics is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-digitalwrite-pinmode",
    title: "digitalWrite & pinMode",
    description: "Drive LEDs and read button logic levels.",
    level: "beginner",
    section: "Digital I/O",
    order: 6,
    minutes: 11,
    content: [
      {"type":"p","text":"digitalWrite & pinMode is a core skill in the Arduino path on InTelleX. You will learn digitalwrite & pinmode with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind digitalWrite & pinMode","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice digitalwrite & pinmode with a small exercise of your own."},
      {"type":"keypoints","items":["digitalWrite & pinMode is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-buttons-pull-ups",
    title: "Buttons & Pull-ups",
    description: "INPUT_PULLUP and debouncing ideas.",
    level: "beginner",
    section: "Digital I/O",
    order: 7,
    minutes: 11,
    content: [
      {"type":"p","text":"Buttons & Pull-ups is a core skill in the Arduino path on InTelleX. You will learn buttons & pull-ups with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Buttons & Pull-ups","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice buttons & pull-ups with a small exercise of your own."},
      {"type":"keypoints","items":["Buttons & Pull-ups is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-pwm-with-analogwrite",
    title: "PWM with analogWrite",
    description: "Fade an LED using pulse-width modulation.",
    level: "beginner",
    section: "Digital I/O",
    order: 8,
    minutes: 11,
    content: [
      {"type":"p","text":"PWM with analogWrite is a core skill in the Arduino path on InTelleX. You will learn pwm with analogwrite with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind PWM with analogWrite","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice pwm with analogwrite with a small exercise of your own."},
      {"type":"keypoints","items":["PWM with analogWrite is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-multiple-leds",
    title: "Multiple LEDs",
    description: "Patterns with arrays of pins.",
    level: "beginner",
    section: "Digital I/O",
    order: 9,
    minutes: 11,
    content: [
      {"type":"p","text":"Multiple LEDs is a core skill in the Arduino path on InTelleX. You will learn multiple leds with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Multiple LEDs","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice multiple leds with a small exercise of your own."},
      {"type":"keypoints","items":["Multiple LEDs is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-tone-buzzers",
    title: "Tone & Buzzers",
    description: "Generate simple tones.",
    level: "beginner",
    section: "Digital I/O",
    order: 10,
    minutes: 11,
    content: [
      {"type":"p","text":"Tone & Buzzers is a core skill in the Arduino path on InTelleX. You will learn tone & buzzers with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Tone & Buzzers","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice tone & buzzers with a small exercise of your own."},
      {"type":"keypoints","items":["Tone & Buzzers is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-analogread",
    title: "analogRead",
    description: "Read potentiometers and sensors (0-1023).",
    level: "beginner",
    section: "Analog Sensing",
    order: 11,
    minutes: 11,
    content: [
      {"type":"p","text":"analogRead is a core skill in the Arduino path on InTelleX. You will learn analogread with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind analogRead","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice analogread with a small exercise of your own."},
      {"type":"keypoints","items":["analogRead is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-mapping-values",
    title: "Mapping Values",
    description: "map() and constrain() for usable ranges.",
    level: "beginner",
    section: "Analog Sensing",
    order: 12,
    minutes: 11,
    content: [
      {"type":"p","text":"Mapping Values is a core skill in the Arduino path on InTelleX. You will learn mapping values with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Mapping Values","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice mapping values with a small exercise of your own."},
      {"type":"keypoints","items":["Mapping Values is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-smoothing-readings",
    title: "Smoothing Readings",
    description: "Average noisy analog signals.",
    level: "beginner",
    section: "Analog Sensing",
    order: 13,
    minutes: 11,
    content: [
      {"type":"p","text":"Smoothing Readings is a core skill in the Arduino path on InTelleX. You will learn smoothing readings with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Smoothing Readings","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice smoothing readings with a small exercise of your own."},
      {"type":"keypoints","items":["Smoothing Readings is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-threshold-triggers",
    title: "Threshold Triggers",
    description: "Turn devices on when a sensor crosses a value.",
    level: "beginner",
    section: "Analog Sensing",
    order: 14,
    minutes: 11,
    content: [
      {"type":"p","text":"Threshold Triggers is a core skill in the Arduino path on InTelleX. You will learn threshold triggers with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Threshold Triggers","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice threshold triggers with a small exercise of your own."},
      {"type":"keypoints","items":["Threshold Triggers is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-project-night-light",
    title: "Project: Night Light",
    description: "LDR + LED automatic night light.",
    level: "beginner",
    section: "Analog Sensing",
    order: 15,
    minutes: 16,
    content: [
      {"type":"p","text":"Project: Night Light is a core skill in the Arduino path on InTelleX. You will learn project: night light with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Night Light","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice project: night light with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Night Light is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-millis-timing",
    title: "millis() Timing",
    description: "Non-blocking timing instead of long delay().",
    level: "beginner",
    section: "Timing & Structure",
    order: 16,
    minutes: 11,
    content: [
      {"type":"p","text":"millis() Timing is a core skill in the Arduino path on InTelleX. You will learn millis() timing with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind millis() Timing","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice millis() timing with a small exercise of your own."},
      {"type":"keypoints","items":["millis() Timing is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-state-machines",
    title: "State Machines",
    description: "Model device behavior with states.",
    level: "beginner",
    section: "Timing & Structure",
    order: 17,
    minutes: 11,
    content: [
      {"type":"p","text":"State Machines is a core skill in the Arduino path on InTelleX. You will learn state machines with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind State Machines","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice state machines with a small exercise of your own."},
      {"type":"keypoints","items":["State Machines is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-functions-in-sketches",
    title: "Functions in Sketches",
    description: "Keep loop() readable with helpers.",
    level: "beginner",
    section: "Timing & Structure",
    order: 18,
    minutes: 11,
    content: [
      {"type":"p","text":"Functions in Sketches is a core skill in the Arduino path on InTelleX. You will learn functions in sketches with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Functions in Sketches","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice functions in sketches with a small exercise of your own."},
      {"type":"keypoints","items":["Functions in Sketches is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-arrays-of-sensors",
    title: "Arrays of Sensors",
    description: "Scale I/O cleanly.",
    level: "beginner",
    section: "Timing & Structure",
    order: 19,
    minutes: 11,
    content: [
      {"type":"p","text":"Arrays of Sensors is a core skill in the Arduino path on InTelleX. You will learn arrays of sensors with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Arrays of Sensors","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice arrays of sensors with a small exercise of your own."},
      {"type":"keypoints","items":["Arrays of Sensors is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-eeprom-intro",
    title: "EEPROM Intro",
    description: "Persist small settings on the board.",
    level: "beginner",
    section: "Timing & Structure",
    order: 20,
    minutes: 11,
    content: [
      {"type":"p","text":"EEPROM Intro is a core skill in the Arduino path on InTelleX. You will learn eeprom intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind EEPROM Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice eeprom intro with a small exercise of your own."},
      {"type":"keypoints","items":["EEPROM Intro is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-using-libraries",
    title: "Using Libraries",
    description: "Install and include third-party libraries.",
    level: "beginner",
    section: "Libraries & Modules",
    order: 21,
    minutes: 11,
    content: [
      {"type":"p","text":"Using Libraries is a core skill in the Arduino path on InTelleX. You will learn using libraries with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Using Libraries","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice using libraries with a small exercise of your own."},
      {"type":"keypoints","items":["Using Libraries is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-ultrasonic-distance",
    title: "Ultrasonic Distance",
    description: "HC-SR04 distance sensing.",
    level: "beginner",
    section: "Libraries & Modules",
    order: 22,
    minutes: 11,
    content: [
      {"type":"p","text":"Ultrasonic Distance is a core skill in the Arduino path on InTelleX. You will learn ultrasonic distance with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Ultrasonic Distance","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice ultrasonic distance with a small exercise of your own."},
      {"type":"keypoints","items":["Ultrasonic Distance is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-dht-temperature",
    title: "DHT Temperature",
    description: "Read temperature and humidity.",
    level: "beginner",
    section: "Libraries & Modules",
    order: 23,
    minutes: 11,
    content: [
      {"type":"p","text":"DHT Temperature is a core skill in the Arduino path on InTelleX. You will learn dht temperature with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind DHT Temperature","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice dht temperature with a small exercise of your own."},
      {"type":"keypoints","items":["DHT Temperature is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-servo-motors",
    title: "Servo Motors",
    description: "Position control with Servo.h.",
    level: "beginner",
    section: "Libraries & Modules",
    order: 24,
    minutes: 11,
    content: [
      {"type":"p","text":"Servo Motors is a core skill in the Arduino path on InTelleX. You will learn servo motors with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Servo Motors","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice servo motors with a small exercise of your own."},
      {"type":"keypoints","items":["Servo Motors is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-lcd-display",
    title: "LCD Display",
    description: "Print sensor data to an LCD.",
    level: "beginner",
    section: "Libraries & Modules",
    order: 25,
    minutes: 11,
    content: [
      {"type":"p","text":"LCD Display is a core skill in the Arduino path on InTelleX. You will learn lcd display with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind LCD Display","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice lcd display with a small exercise of your own."},
      {"type":"keypoints","items":["LCD Display is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
