import type { TutorialLesson } from '../types';

export const intermediateLessons: TutorialLesson[] = [
  {
    slug: "arduino-i2c-basics",
    title: "I2C Basics",
    description: "Wire library and device addresses.",
    level: "intermediate",
    section: "Communication",
    order: 26,
    minutes: 13,
    content: [
      {"type":"p","text":"I2C Basics is a core skill in the Arduino path on InTelleX. You will learn i2c basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind I2C Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice i2c basics with a small exercise of your own."},
      {"type":"keypoints","items":["I2C Basics is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-spi-basics",
    title: "SPI Basics",
    description: "When SPI is the right bus.",
    level: "intermediate",
    section: "Communication",
    order: 27,
    minutes: 13,
    content: [
      {"type":"p","text":"SPI Basics is a core skill in the Arduino path on InTelleX. You will learn spi basics with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind SPI Basics","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice spi basics with a small exercise of your own."},
      {"type":"keypoints","items":["SPI Basics is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-uart-devices",
    title: "UART Devices",
    description: "Talk to GPS/Bluetooth modules.",
    level: "intermediate",
    section: "Communication",
    order: 28,
    minutes: 13,
    content: [
      {"type":"p","text":"UART Devices is a core skill in the Arduino path on InTelleX. You will learn uart devices with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind UART Devices","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice uart devices with a small exercise of your own."},
      {"type":"keypoints","items":["UART Devices is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-project-weather-station",
    title: "Project: Weather Station",
    description: "Sensor + display + serial logging.",
    level: "intermediate",
    section: "Communication",
    order: 29,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: Weather Station is a core skill in the Arduino path on InTelleX. You will learn project: weather station with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Weather Station","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice project: weather station with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Weather Station is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-project-smart-plant",
    title: "Project: Smart Plant",
    description: "Moisture sensor watering reminder.",
    level: "intermediate",
    section: "Communication",
    order: 30,
    minutes: 18,
    content: [
      {"type":"p","text":"Project: Smart Plant is a core skill in the Arduino path on InTelleX. You will learn project: smart plant with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Smart Plant","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice project: smart plant with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Smart Plant is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-current-voltage-limits",
    title: "Current & Voltage Limits",
    description: "Protect pins and understand loads.",
    level: "intermediate",
    section: "Intermediate Electronics",
    order: 31,
    minutes: 13,
    content: [
      {"type":"p","text":"Current & Voltage Limits is a core skill in the Arduino path on InTelleX. You will learn current & voltage limits with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Current & Voltage Limits","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice current & voltage limits with a small exercise of your own."},
      {"type":"keypoints","items":["Current & Voltage Limits is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-transistors-as-switches",
    title: "Transistors as Switches",
    description: "Drive motors and relays safely.",
    level: "intermediate",
    section: "Intermediate Electronics",
    order: 32,
    minutes: 13,
    content: [
      {"type":"p","text":"Transistors as Switches is a core skill in the Arduino path on InTelleX. You will learn transistors as switches with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Transistors as Switches","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice transistors as switches with a small exercise of your own."},
      {"type":"keypoints","items":["Transistors as Switches is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-motor-drivers",
    title: "Motor Drivers",
    description: "H-bridges and L298-style modules.",
    level: "intermediate",
    section: "Intermediate Electronics",
    order: 33,
    minutes: 13,
    content: [
      {"type":"p","text":"Motor Drivers is a core skill in the Arduino path on InTelleX. You will learn motor drivers with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Motor Drivers","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice motor drivers with a small exercise of your own."},
      {"type":"keypoints","items":["Motor Drivers is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-power-supplies",
    title: "Power Supplies",
    description: "USB vs barrel jack vs batteries.",
    level: "intermediate",
    section: "Intermediate Electronics",
    order: 34,
    minutes: 13,
    content: [
      {"type":"p","text":"Power Supplies is a core skill in the Arduino path on InTelleX. You will learn power supplies with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Power Supplies","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice power supplies with a small exercise of your own."},
      {"type":"keypoints","items":["Power Supplies is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-debugging-hardware",
    title: "Debugging Hardware",
    description: "Multimeter checks and common faults.",
    level: "intermediate",
    section: "Intermediate Electronics",
    order: 35,
    minutes: 13,
    content: [
      {"type":"p","text":"Debugging Hardware is a core skill in the Arduino path on InTelleX. You will learn debugging hardware with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Debugging Hardware","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice debugging hardware with a small exercise of your own."},
      {"type":"keypoints","items":["Debugging Hardware is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-external-interrupts",
    title: "External Interrupts",
    description: "attachInterrupt for fast events.",
    level: "intermediate",
    section: "Interrupts & Timing Advanced",
    order: 36,
    minutes: 13,
    content: [
      {"type":"p","text":"External Interrupts is a core skill in the Arduino path on InTelleX. You will learn external interrupts with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind External Interrupts","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice external interrupts with a small exercise of your own."},
      {"type":"keypoints","items":["External Interrupts is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-timers-overview",
    title: "Timers Overview",
    description: "How hardware timers enable precision.",
    level: "intermediate",
    section: "Interrupts & Timing Advanced",
    order: 37,
    minutes: 13,
    content: [
      {"type":"p","text":"Timers Overview is a core skill in the Arduino path on InTelleX. You will learn timers overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Timers Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice timers overview with a small exercise of your own."},
      {"type":"keypoints","items":["Timers Overview is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-low-power-ideas",
    title: "Low Power Ideas",
    description: "Sleep modes for battery projects.",
    level: "intermediate",
    section: "Interrupts & Timing Advanced",
    order: 38,
    minutes: 13,
    content: [
      {"type":"p","text":"Low Power Ideas is a core skill in the Arduino path on InTelleX. You will learn low power ideas with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Low Power Ideas","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice low power ideas with a small exercise of your own."},
      {"type":"keypoints","items":["Low Power Ideas is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-watchdog-timer",
    title: "Watchdog Timer",
    description: "Recover from hung firmware.",
    level: "intermediate",
    section: "Interrupts & Timing Advanced",
    order: 39,
    minutes: 13,
    content: [
      {"type":"p","text":"Watchdog Timer is a core skill in the Arduino path on InTelleX. You will learn watchdog timer with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Watchdog Timer","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice watchdog timer with a small exercise of your own."},
      {"type":"keypoints","items":["Watchdog Timer is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-project-reaction-game",
    title: "Project: Reaction Game",
    description: "Button timing game with scoring.",
    level: "intermediate",
    section: "Interrupts & Timing Advanced",
    order: 40,
    minutes: 16,
    content: [
      {"type":"p","text":"Project: Reaction Game is a core skill in the Arduino path on InTelleX. You will learn project: reaction game with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Reaction Game","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice project: reaction game with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Reaction Game is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-esp8266-esp32-overview",
    title: "ESP8266/ESP32 Overview",
    description: "Wi-Fi capable Arduino-compatible boards.",
    level: "intermediate",
    section: "IoT & Networking",
    order: 41,
    minutes: 13,
    content: [
      {"type":"p","text":"ESP8266/ESP32 Overview is a core skill in the Arduino path on InTelleX. You will learn esp8266/esp32 overview with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind ESP8266/ESP32 Overview","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice esp8266/esp32 overview with a small exercise of your own."},
      {"type":"keypoints","items":["ESP8266/ESP32 Overview is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-wi-fi-connect-sketch",
    title: "Wi-Fi Connect Sketch",
    description: "Join a network and print the IP.",
    level: "intermediate",
    section: "IoT & Networking",
    order: 42,
    minutes: 13,
    content: [
      {"type":"p","text":"Wi-Fi Connect Sketch is a core skill in the Arduino path on InTelleX. You will learn wi-fi connect sketch with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Wi-Fi Connect Sketch","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice wi-fi connect sketch with a small exercise of your own."},
      {"type":"keypoints","items":["Wi-Fi Connect Sketch is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-http-requests",
    title: "HTTP Requests",
    description: "Push sensor readings to a webhook.",
    level: "intermediate",
    section: "IoT & Networking",
    order: 43,
    minutes: 13,
    content: [
      {"type":"p","text":"HTTP Requests is a core skill in the Arduino path on InTelleX. You will learn http requests with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind HTTP Requests","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice http requests with a small exercise of your own."},
      {"type":"keypoints","items":["HTTP Requests is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-mqtt-intro",
    title: "MQTT Intro",
    description: "Publish/subscribe for IoT telemetry.",
    level: "intermediate",
    section: "IoT & Networking",
    order: 44,
    minutes: 13,
    content: [
      {"type":"p","text":"MQTT Intro is a core skill in the Arduino path on InTelleX. You will learn mqtt intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind MQTT Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice mqtt intro with a small exercise of your own."},
      {"type":"keypoints","items":["MQTT Intro is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-project-room-monitor",
    title: "Project: Room Monitor",
    description: "Temp/humidity to serial + optional cloud.",
    level: "intermediate",
    section: "IoT & Networking",
    order: 45,
    minutes: 20,
    content: [
      {"type":"p","text":"Project: Room Monitor is a core skill in the Arduino path on InTelleX. You will learn project: room monitor with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Project: Room Monitor","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice project: room monitor with a small exercise of your own."},
      {"type":"keypoints","items":["Project: Room Monitor is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-chassis-drive",
    title: "Chassis & Drive",
    description: "Differential drive robots.",
    level: "intermediate",
    section: "Robotics Basics",
    order: 46,
    minutes: 13,
    content: [
      {"type":"p","text":"Chassis & Drive is a core skill in the Arduino path on InTelleX. You will learn chassis & drive with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Chassis & Drive","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice chassis & drive with a small exercise of your own."},
      {"type":"keypoints","items":["Chassis & Drive is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-line-following-intro",
    title: "Line Following Intro",
    description: "IR sensors and simple control.",
    level: "intermediate",
    section: "Robotics Basics",
    order: 47,
    minutes: 13,
    content: [
      {"type":"p","text":"Line Following Intro is a core skill in the Arduino path on InTelleX. You will learn line following intro with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Line Following Intro","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice line following intro with a small exercise of your own."},
      {"type":"keypoints","items":["Line Following Intro is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
  {
    slug: "arduino-obstacle-avoidance",
    title: "Obstacle Avoidance",
    description: "Ultrasonic + motor decisions.",
    level: "intermediate",
    section: "Robotics Basics",
    order: 48,
    minutes: 13,
    content: [
      {"type":"p","text":"Obstacle Avoidance is a core skill in the Arduino path on InTelleX. You will learn obstacle avoidance with clear examples."},
      {"type":"p","text":"Read carefully, type every example yourself, and finish the practice prompt before moving on."},
      {"type":"h2","text":"What you will learn"},
      {"type":"ul","items":["Core ideas behind Obstacle Avoidance","Worked examples you can run","Common mistakes to avoid"]},
      {"type":"tip","text":"Type the example yourself - reading alone is not enough."},
      {"type":"note","text":"Keep notes in your Arduino lab folder as you go."},
      {"type":"try","text":"Practice obstacle avoidance with a small exercise of your own."},
      {"type":"keypoints","items":["Obstacle Avoidance is an essential Arduino skill.","Practice with real commands or code, not only theory.","Move on only when the practice prompt feels easy."]},
    ],
  },
];
